<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;

/**
 * BridgePropertySeeder — DEV / STAGING ONLY
 *
 * Populates bridge_properties with representative sample MLS records so the
 * /stellar/buyer/results matching flow can be browser-tested without a live
 * Bridge/Stellar MLS API connection.
 *
 * PRODUCTION GUARD: this seeder aborts immediately in the production environment.
 *
 * Usage (manual invocation only):
 *   php artisan db:seed --class=BridgePropertySeeder
 *
 * DO NOT add this class to DatabaseSeeder::run() — it must never run
 * automatically during deploy or a full db:seed call.
 *
 * Matching notes for browser testing:
 *   - All Active + Residential records will pass the import_unavailable and
 *     no_inventory guards in StellarBuyerResultsController.
 *   - To reach actual match results (not the no_location state) create a
 *     BuyerCriteriaAuction or TenantCriteriaAuction with preferred_cities
 *     containing one of: Orlando, Tampa, Sarasota, Naples, Jacksonville,
 *     Fort Lauderdale, Boca Raton, Gainesville, Clearwater, or Ocala;
 *     OR preferred_zip_codes containing one of the postal codes below.
 *   - Price range $200k–$950k with 2–5 beds covers the seeded Residential inventory.
 *
 * Commercial Lease matching (Tenant commercial lease offer listings):
 *   - Three Active/Commercial Lease records seeded: Tampa (office, $3,500/mo, 2-yr lease),
 *     Orlando (retail, $2,200/mo, 1-yr lease), Fort Lauderdale (mixed-use, $5,800/mo, 3-5yr).
 *   - PropertyType = 'Commercial Lease' confirmed from live Bridge API import 2026-06-23.
 *   - list_price = monthly rent for commercial lease records.
 *   - LeaseTerm in raw_json is the Bridge field used for lease-term scoring.
 */
class BridgePropertySeeder extends Seeder
{
    public function run(): void
    {
        if (App::environment('production')) {
            $this->command->error(
                'BridgePropertySeeder is not allowed in the production environment. Aborting.'
            );
            return;
        }

        $this->command->info('Seeding bridge_properties with sample MLS data (dev/staging only)…');

        $now = now()->toDateTimeString();

        $records = $this->sampleRecords($now);

        foreach ($records as $record) {
            DB::table('bridge_properties')->updateOrInsert(
                ['listing_key' => $record['listing_key']],
                $record
            );
        }

        $total                   = DB::table('bridge_properties')->count();
        $activeResidential       = DB::table('bridge_properties')->where('standard_status', 'Active')->where('property_type', 'Residential')->count();
        $activeIncome            = DB::table('bridge_properties')->where('standard_status', 'Active')->where('property_type', 'Income')->count();
        $activeCommercialSale    = DB::table('bridge_properties')->where('standard_status', 'Active')->where('property_type', 'Commercial Sale')->count();
        $activeCommercialLease   = DB::table('bridge_properties')->where('standard_status', 'Active')->where('property_type', 'Commercial Lease')->count();
        $activeBusinessOpp       = DB::table('bridge_properties')->where('standard_status', 'Active')->where('property_type', 'Business Opportunity')->count();
        $activeVacantLand        = DB::table('bridge_properties')->where('standard_status', 'Active')->where('property_type', 'Vacant Land')->count();

        $this->command->info("Done. bridge_properties total rows: {$total}.");
        $this->command->info("  Active/Residential: {$activeResidential}");
        $this->command->info("  Active/Income: {$activeIncome}");
        $this->command->info("  Active/Commercial Sale: {$activeCommercialSale}");
        $this->command->info("  Active/Commercial Lease: {$activeCommercialLease}");
        $this->command->info("  Active/Business Opportunity: {$activeBusinessOpp}");
        $this->command->info("  Active/Vacant Land: {$activeVacantLand}");
    }

    // -------------------------------------------------------------------------

    private function sampleRecords(string $now): array
    {
        return [

            // ─────────────────────────────────────────────────────────────────
            // ACTIVE / RESIDENTIAL — buyer-matching targets
            // ─────────────────────────────────────────────────────────────────

            // Orlando — mid-range, family home with pool & garage
            [
                'listing_key'             => 'SEED-ORL-001',
                'listing_id'              => 'ORL-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Active',
                'list_price'              => 425000.00,
                'unparsed_address'        => '4521 Lake Nona Blvd, Orlando, FL 32827',
                'city'                    => 'Orlando',
                'state_or_province'       => 'FL',
                'postal_code'             => '32827',
                'county_or_parish'        => 'Orange',
                'bedrooms_total'          => 4,
                'bathrooms_total_integer' => 3,
                'living_area'             => 2350,
                'lot_size_sqft'           => 8500,
                'year_built'              => 2018,
                'latitude'                => 28.3772,
                'longitude'               => -81.2525,
                'pool_private_yn'         => true,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 185.00,
                'tax_annual_amount'       => 4800.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-ORL-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Tampa — starter home, no HOA
            [
                'listing_key'             => 'SEED-TPA-001',
                'listing_id'              => 'TPA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Active',
                'list_price'              => 319000.00,
                'unparsed_address'        => '7812 N Himes Ave, Tampa, FL 33614',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33614',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => 3,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1580,
                'lot_size_sqft'           => 6200,
                'year_built'              => 2005,
                'latitude'                => 27.9991,
                'longitude'               => -82.4895,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 3100.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-TPA-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Tampa — upscale waterfront townhome
            [
                'listing_key'             => 'SEED-TPA-002',
                'listing_id'              => 'TPA-002',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Townhouse',
                'mls_status'              => 'Active',
                'list_price'              => 649000.00,
                'unparsed_address'        => '2210 Bayshore Blvd Unit 12, Tampa, FL 33629',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33629',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => 3,
                'bathrooms_total_integer' => 3,
                'living_area'             => 2100,
                'lot_size_sqft'           => 2800,
                'year_built'              => 2016,
                'latitude'                => 27.9209,
                'longitude'               => -82.4893,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => true,
                'water_view_yn'           => true,
                'view_yn'                 => true,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 450.00,
                'tax_annual_amount'       => 8200.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-TPA-002', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Sarasota — luxury pool home
            [
                'listing_key'             => 'SEED-SRQ-001',
                'listing_id'              => 'SRQ-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Active',
                'list_price'              => 875000.00,
                'unparsed_address'        => '3301 Gulf Gate Dr, Sarasota, FL 34231',
                'city'                    => 'Sarasota',
                'state_or_province'       => 'FL',
                'postal_code'             => '34231',
                'county_or_parish'        => 'Sarasota',
                'bedrooms_total'          => 5,
                'bathrooms_total_integer' => 4,
                'living_area'             => 3800,
                'lot_size_sqft'           => 14000,
                'year_built'              => 2012,
                'latitude'                => 27.2775,
                'longitude'               => -82.5115,
                'pool_private_yn'         => true,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 320.00,
                'tax_annual_amount'       => 11500.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-SRQ-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Naples — high-end condo, waterfront view
            [
                'listing_key'             => 'SEED-NAP-001',
                'listing_id'              => 'NAP-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Condominium',
                'mls_status'              => 'Active',
                'list_price'              => 945000.00,
                'unparsed_address'        => '100 Gulf Shore Blvd N Apt 801, Naples, FL 34102',
                'city'                    => 'Naples',
                'state_or_province'       => 'FL',
                'postal_code'             => '34102',
                'county_or_parish'        => 'Collier',
                'bedrooms_total'          => 3,
                'bathrooms_total_integer' => 3,
                'living_area'             => 2250,
                'lot_size_sqft'           => null,
                'year_built'              => 2008,
                'latitude'                => 26.1420,
                'longitude'               => -81.7948,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => true,
                'water_view_yn'           => true,
                'view_yn'                 => true,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 1200.00,
                'tax_annual_amount'       => 9800.00,
                'pets_allowed'            => 'No',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-NAP-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Jacksonville — affordable new construction
            [
                'listing_key'             => 'SEED-JAX-001',
                'listing_id'              => 'JAX-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Active',
                'list_price'              => 278000.00,
                'unparsed_address'        => '5890 Bartram Park Blvd, Jacksonville, FL 32258',
                'city'                    => 'Jacksonville',
                'state_or_province'       => 'FL',
                'postal_code'             => '32258',
                'county_or_parish'        => 'Duval',
                'bedrooms_total'          => 3,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1720,
                'lot_size_sqft'           => 6800,
                'year_built'              => 2024,
                'latitude'                => 30.1072,
                'longitude'               => -81.5658,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => true,
                'association_fee'         => 95.00,
                'tax_annual_amount'       => 2100.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => true,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-JAX-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Fort Lauderdale — mid-range with pool, good for buyer matching
            [
                'listing_key'             => 'SEED-FLL-001',
                'listing_id'              => 'FLL-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Active',
                'list_price'              => 540000.00,
                'unparsed_address'        => '3411 NE 26th Ave, Fort Lauderdale, FL 33306',
                'city'                    => 'Fort Lauderdale',
                'state_or_province'       => 'FL',
                'postal_code'             => '33306',
                'county_or_parish'        => 'Broward',
                'bedrooms_total'          => 4,
                'bathrooms_total_integer' => 3,
                'living_area'             => 2050,
                'lot_size_sqft'           => 7500,
                'year_built'              => 2000,
                'latitude'                => 26.1607,
                'longitude'               => -80.1095,
                'pool_private_yn'         => true,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 6700.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-FLL-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Boca Raton — 55+ senior community
            [
                'listing_key'             => 'SEED-BCA-001',
                'listing_id'              => 'BCA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Villa',
                'mls_status'              => 'Active',
                'list_price'              => 385000.00,
                'unparsed_address'        => '6200 Via De Sonrisa Del Sur, Boca Raton, FL 33433',
                'city'                    => 'Boca Raton',
                'state_or_province'       => 'FL',
                'postal_code'             => '33433',
                'county_or_parish'        => 'Palm Beach',
                'bedrooms_total'          => 2,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1480,
                'lot_size_sqft'           => 4200,
                'year_built'              => 1992,
                'latitude'                => 26.3683,
                'longitude'               => -80.1253,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => true,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 510.00,
                'tax_annual_amount'       => 3900.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-BCA-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Gainesville — college-area budget home
            [
                'listing_key'             => 'SEED-GNV-001',
                'listing_id'              => 'GNV-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Active',
                'list_price'              => 219000.00,
                'unparsed_address'        => '3402 NW 16th Pl, Gainesville, FL 32605',
                'city'                    => 'Gainesville',
                'state_or_province'       => 'FL',
                'postal_code'             => '32605',
                'county_or_parish'        => 'Alachua',
                'bedrooms_total'          => 3,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1350,
                'lot_size_sqft'           => 9100,
                'year_built'              => 1985,
                'latitude'                => 29.6797,
                'longitude'               => -82.3635,
                'pool_private_yn'         => false,
                'garage_yn'               => false,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 2050.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-GNV-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Clearwater — beach area condo, tenant-rental target
            [
                'listing_key'             => 'SEED-CLW-001',
                'listing_id'              => 'CLW-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Condominium',
                'mls_status'              => 'Active',
                'list_price'              => 465000.00,
                'unparsed_address'        => '1880 N Fort Harrison Ave, Clearwater, FL 33755',
                'city'                    => 'Clearwater',
                'state_or_province'       => 'FL',
                'postal_code'             => '33755',
                'county_or_parish'        => 'Pinellas',
                'bedrooms_total'          => 2,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1180,
                'lot_size_sqft'           => null,
                'year_built'              => 2001,
                'latitude'                => 27.9659,
                'longitude'               => -82.7990,
                'pool_private_yn'         => false,
                'garage_yn'               => false,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 380.00,
                'tax_annual_amount'       => 4600.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-CLW-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Ocala — rural / horse country
            [
                'listing_key'             => 'SEED-OCA-001',
                'listing_id'              => 'OCA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Active',
                'list_price'              => 345000.00,
                'unparsed_address'        => '14805 SW 80th Ave, Ocala, FL 34473',
                'city'                    => 'Ocala',
                'state_or_province'       => 'FL',
                'postal_code'             => '34473',
                'county_or_parish'        => 'Marion',
                'bedrooms_total'          => 4,
                'bathrooms_total_integer' => 2,
                'living_area'             => 2200,
                'lot_size_sqft'           => 43560,
                'year_built'              => 2003,
                'latitude'                => 29.0844,
                'longitude'               => -82.1401,
                'pool_private_yn'         => true,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 2800.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-OCA-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // PENDING — for contrast / filter testing
            // ─────────────────────────────────────────────────────────────────

            [
                'listing_key'             => 'SEED-TPA-003-PENDING',
                'listing_id'              => 'TPA-003',
                'standard_status'         => 'Pending',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Pending',
                'list_price'              => 410000.00,
                'unparsed_address'        => '4499 Swann Ave, Tampa, FL 33609',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33609',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => 4,
                'bathrooms_total_integer' => 3,
                'living_area'             => 2000,
                'lot_size_sqft'           => 7200,
                'year_built'              => 2010,
                'latitude'                => 27.9341,
                'longitude'               => -82.5129,
                'pool_private_yn'         => true,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 5200.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-TPA-003-PENDING', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // CLOSED — for contrast / filter testing
            // ─────────────────────────────────────────────────────────────────

            [
                'listing_key'             => 'SEED-ORL-002-CLOSED',
                'listing_id'              => 'ORL-002',
                'standard_status'         => 'Closed',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Single Family Residence',
                'mls_status'              => 'Closed',
                'list_price'              => 395000.00,
                'unparsed_address'        => '1020 Lake Destiny Rd, Orlando, FL 32810',
                'city'                    => 'Orlando',
                'state_or_province'       => 'FL',
                'postal_code'             => '32810',
                'county_or_parish'        => 'Orange',
                'bedrooms_total'          => 3,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1680,
                'lot_size_sqft'           => 7800,
                'year_built'              => 1998,
                'latitude'                => 28.5774,
                'longitude'               => -81.4159,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 3800.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-ORL-002-CLOSED', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ACTIVE / RESIDENTIAL — Rental-friendly (tenant matching targets)
            // These are for-sale listings but with characteristics that overlap
            // with tenant criteria (pets allowed, condo, price bands typical of
            // rental-priced purchases).
            // ─────────────────────────────────────────────────────────────────

            // Clearwater rental-friendly condo (pets, no senior)
            [
                'listing_key'             => 'SEED-CLW-002',
                'listing_id'              => 'CLW-002',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Condominium',
                'mls_status'              => 'Active',
                'list_price'              => 295000.00,
                'unparsed_address'        => '2675 Ulmerton Rd Apt 44, Clearwater, FL 33762',
                'city'                    => 'Clearwater',
                'state_or_province'       => 'FL',
                'postal_code'             => '33762',
                'county_or_parish'        => 'Pinellas',
                'bedrooms_total'          => 2,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1020,
                'lot_size_sqft'           => null,
                'year_built'              => 1995,
                'latitude'                => 27.8898,
                'longitude'               => -82.7196,
                'pool_private_yn'         => false,
                'garage_yn'               => false,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 290.00,
                'tax_annual_amount'       => 2600.00,
                'pets_allowed'            => 'Dogs',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-CLW-002', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ACTIVE / COMMERCIAL LEASE — tenant commercial lease matching targets
            //
            // PropertyType = 'Commercial Lease' confirmed from live Bridge/Stellar
            // OData API import on 2026-06-23. list_price = monthly rent for these
            // records (Bridge field confirmed populated in live sample).
            // ─────────────────────────────────────────────────────────────────

            // Tampa — office suite, 2-year lease, mid-size
            [
                'listing_key'             => 'SEED-COM-TPA-001',
                'listing_id'              => 'COM-TPA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Commercial Lease',
                'property_sub_type'       => 'Office',
                'mls_status'              => 'Active',
                'list_price'              => 3500.00,
                'unparsed_address'        => '4830 W Kennedy Blvd Suite 220, Tampa, FL 33609',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33609',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => null,
                'bathrooms_total_integer' => null,
                'living_area'             => 1800,
                'lot_size_sqft'           => null,
                'year_built'              => 2005,
                'latitude'                => 27.9464,
                'longitude'               => -82.5063,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => null,
                'pets_allowed'            => null,
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode([
                    'ListingKey'  => 'SEED-COM-TPA-001',
                    'LeaseTerm'   => '24 Months',
                    'seeded'      => true,
                ]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Orlando — retail space, 1-year lease, smaller unit
            [
                'listing_key'             => 'SEED-COM-ORL-001',
                'listing_id'              => 'COM-ORL-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Commercial Lease',
                'property_sub_type'       => 'Retail',
                'mls_status'              => 'Active',
                'list_price'              => 2200.00,
                'unparsed_address'        => '7600 Dr Phillips Blvd Suite 104, Orlando, FL 32819',
                'city'                    => 'Orlando',
                'state_or_province'       => 'FL',
                'postal_code'             => '32819',
                'county_or_parish'        => 'Orange',
                'bedrooms_total'          => null,
                'bathrooms_total_integer' => null,
                'living_area'             => 1100,
                'lot_size_sqft'           => null,
                'year_built'              => 1998,
                'latitude'                => 28.4542,
                'longitude'               => -81.4783,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => null,
                'pets_allowed'            => null,
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode([
                    'ListingKey'  => 'SEED-COM-ORL-001',
                    'LeaseTerm'   => '12 Months',
                    'seeded'      => true,
                ]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // Fort Lauderdale — mixed-use flex space, 3–5 year lease
            [
                'listing_key'             => 'SEED-COM-FLL-001',
                'listing_id'              => 'COM-FLL-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Commercial Lease',
                'property_sub_type'       => 'Mixed Use',
                'mls_status'              => 'Active',
                'list_price'              => 5800.00,
                'unparsed_address'        => '200 E Broward Blvd Suite 300, Fort Lauderdale, FL 33301',
                'city'                    => 'Fort Lauderdale',
                'state_or_province'       => 'FL',
                'postal_code'             => '33301',
                'county_or_parish'        => 'Broward',
                'bedrooms_total'          => null,
                'bathrooms_total_integer' => null,
                'living_area'             => 3200,
                'lot_size_sqft'           => null,
                'year_built'              => 2012,
                'latitude'                => 26.1224,
                'longitude'               => -80.1373,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => null,
                'pets_allowed'            => null,
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode([
                    'ListingKey'  => 'SEED-COM-FLL-001',
                    'LeaseTerm'   => '48 Months',
                    'seeded'      => true,
                ]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ACTIVE / INCOME — buyer matching (multi-family / investment)
            // ─────────────────────────────────────────────────────────────────

            // Tampa — 4-unit apartment building
            [
                'listing_key'             => 'SEED-INC-TPA-001',
                'listing_id'              => 'INC-TPA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Income',
                'property_sub_type'       => 'Multi Family',
                'mls_status'              => 'Active',
                'list_price'              => 685000.00,
                'unparsed_address'        => '3310 N Armenia Ave, Tampa, FL 33607',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33607',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => 8,
                'bathrooms_total_integer' => 4,
                'living_area'             => 3600,
                'lot_size_sqft'           => 9200,
                'year_built'              => 1971,
                'latitude'                => 27.9773,
                'longitude'               => -82.4814,
                'pool_private_yn'         => false,
                'garage_yn'               => false,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 6800.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode([
                    'ListingKey'         => 'SEED-INC-TPA-001',
                    'GrossScheduledIncome' => 54000,
                    'NetOperatingIncome'   => 38000,
                    'CapRate'              => 5.55,
                    'seeded'             => true,
                ]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ACTIVE / COMMERCIAL SALE — buyer matching (commercial purchase)
            // ─────────────────────────────────────────────────────────────────

            // Tampa — retail/office strip
            [
                'listing_key'             => 'SEED-CMS-TPA-001',
                'listing_id'              => 'CMS-TPA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Commercial Sale',
                'property_sub_type'       => 'Retail',
                'mls_status'              => 'Active',
                'list_price'              => 1250000.00,
                'unparsed_address'        => '4800 W Kennedy Blvd, Tampa, FL 33609',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33609',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => null,
                'bathrooms_total_integer' => 2,
                'living_area'             => 4800,
                'lot_size_sqft'           => 12000,
                'year_built'              => 2001,
                'latitude'                => 27.9482,
                'longitude'               => -82.5095,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 18500.00,
                'pets_allowed'            => null,
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode([
                    'ListingKey' => 'SEED-CMS-TPA-001',
                    'Zoning'     => 'CG',
                    'seeded'     => true,
                ]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ACTIVE / BUSINESS OPPORTUNITY — buyer matching
            // ─────────────────────────────────────────────────────────────────

            // Tampa — established restaurant for sale
            [
                'listing_key'             => 'SEED-BIZ-TPA-001',
                'listing_id'              => 'BIZ-TPA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Business Opportunity',
                'property_sub_type'       => 'Restaurant/Bar',
                'mls_status'              => 'Active',
                'list_price'              => 320000.00,
                'unparsed_address'        => '1515 E 7th Ave, Tampa, FL 33605',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33605',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => null,
                'bathrooms_total_integer' => null,
                'living_area'             => 2200,
                'lot_size_sqft'           => null,
                'year_built'              => 2008,
                'latitude'                => 27.9552,
                'longitude'               => -82.4386,
                'pool_private_yn'         => false,
                'garage_yn'               => false,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => null,
                'pets_allowed'            => null,
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode([
                    'ListingKey'         => 'SEED-BIZ-TPA-001',
                    'GrossScheduledIncome' => 480000,
                    'seeded'             => true,
                ]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ACTIVE / VACANT LAND — buyer matching
            // ─────────────────────────────────────────────────────────────────

            // Tampa — buildable lot near Westchase
            [
                'listing_key'             => 'SEED-LND-TPA-001',
                'listing_id'              => 'LND-TPA-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Vacant Land',
                'property_sub_type'       => 'Residential',
                'mls_status'              => 'Active',
                'list_price'              => 185000.00,
                'unparsed_address'        => 'Vacant Lot on Sheldon Rd, Tampa, FL 33626',
                'city'                    => 'Tampa',
                'state_or_province'       => 'FL',
                'postal_code'             => '33626',
                'county_or_parish'        => 'Hillsborough',
                'bedrooms_total'          => null,
                'bathrooms_total_integer' => null,
                'living_area'             => null,
                'lot_size_sqft'           => 9600,
                'year_built'              => null,
                'latitude'                => 28.0516,
                'longitude'               => -82.6241,
                'pool_private_yn'         => false,
                'garage_yn'               => false,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => false,
                'new_construction_yn'     => false,
                'association_fee'         => null,
                'tax_annual_amount'       => 1200.00,
                'pets_allowed'            => null,
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode([
                    'ListingKey' => 'SEED-LND-TPA-001',
                    'Zoning'     => 'RSC-6',
                    'seeded'     => true,
                ]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],

            // St. Petersburg — small townhome, tenant-buyer overlap
            [
                'listing_key'             => 'SEED-STP-001',
                'listing_id'              => 'STP-001',
                'standard_status'         => 'Active',
                'property_type'           => 'Residential',
                'property_sub_type'       => 'Townhouse',
                'mls_status'              => 'Active',
                'list_price'              => 338000.00,
                'unparsed_address'        => '4012 5th Ave N, Saint Petersburg, FL 33713',
                'city'                    => 'Saint Petersburg',
                'state_or_province'       => 'FL',
                'postal_code'             => '33713',
                'county_or_parish'        => 'Pinellas',
                'bedrooms_total'          => 2,
                'bathrooms_total_integer' => 2,
                'living_area'             => 1340,
                'lot_size_sqft'           => 2500,
                'year_built'              => 2014,
                'latitude'                => 27.7734,
                'longitude'               => -82.6655,
                'pool_private_yn'         => false,
                'garage_yn'               => true,
                'waterfront_yn'           => false,
                'water_view_yn'           => false,
                'view_yn'                 => false,
                'senior_community_yn'     => false,
                'association_yn'          => true,
                'new_construction_yn'     => false,
                'association_fee'         => 220.00,
                'tax_annual_amount'       => 3400.00,
                'pets_allowed'            => 'Yes',
                'cdd_yn'                  => false,
                'modification_timestamp'  => $now,
                'imported_at'             => $now,
                'raw_json'                => json_encode(['ListingKey' => 'SEED-STP-001', 'seeded' => true]),
                'created_at'              => $now,
                'updated_at'              => $now,
            ],
        ];
    }
}
