<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsCitiesSeeder extends Seeder
{
    public function run()
    {
        $stateIds = DB::table('us_states')->pluck('id', 'abbreviation')->toArray();
        
        $cities = $this->getCitiesData();
        
        $now = now();
        $batch = [];
        
        foreach ($cities as $city) {
            if (!isset($stateIds[$city['state']])) {
                continue;
            }
            
            $batch[] = [
                'name' => $city['name'],
                'fips_code' => $city['fips'] ?? null,
                'state_id' => $stateIds[$city['state']],
                'county_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ];
            
            if (count($batch) >= 500) {
                DB::table('us_cities')->insertOrIgnore($batch);
                $batch = [];
            }
        }
        
        if (!empty($batch)) {
            DB::table('us_cities')->insertOrIgnore($batch);
        }
    }
    
    private function getCitiesData()
    {
        return [
            ['name' => 'Birmingham', 'state' => 'AL'],
            ['name' => 'Montgomery', 'state' => 'AL'],
            ['name' => 'Huntsville', 'state' => 'AL'],
            ['name' => 'Mobile', 'state' => 'AL'],
            ['name' => 'Tuscaloosa', 'state' => 'AL'],
            ['name' => 'Hoover', 'state' => 'AL'],
            ['name' => 'Dothan', 'state' => 'AL'],
            ['name' => 'Auburn', 'state' => 'AL'],
            ['name' => 'Decatur', 'state' => 'AL'],
            ['name' => 'Madison', 'state' => 'AL'],
            ['name' => 'Florence', 'state' => 'AL'],
            ['name' => 'Gadsden', 'state' => 'AL'],
            ['name' => 'Anchorage', 'state' => 'AK'],
            ['name' => 'Fairbanks', 'state' => 'AK'],
            ['name' => 'Juneau', 'state' => 'AK'],
            ['name' => 'Sitka', 'state' => 'AK'],
            ['name' => 'Ketchikan', 'state' => 'AK'],
            ['name' => 'Wasilla', 'state' => 'AK'],
            ['name' => 'Kenai', 'state' => 'AK'],
            ['name' => 'Kodiak', 'state' => 'AK'],
            ['name' => 'Bethel', 'state' => 'AK'],
            ['name' => 'Palmer', 'state' => 'AK'],
            ['name' => 'Phoenix', 'state' => 'AZ'],
            ['name' => 'Tucson', 'state' => 'AZ'],
            ['name' => 'Mesa', 'state' => 'AZ'],
            ['name' => 'Chandler', 'state' => 'AZ'],
            ['name' => 'Scottsdale', 'state' => 'AZ'],
            ['name' => 'Glendale', 'state' => 'AZ'],
            ['name' => 'Gilbert', 'state' => 'AZ'],
            ['name' => 'Tempe', 'state' => 'AZ'],
            ['name' => 'Peoria', 'state' => 'AZ'],
            ['name' => 'Surprise', 'state' => 'AZ'],
            ['name' => 'Yuma', 'state' => 'AZ'],
            ['name' => 'Avondale', 'state' => 'AZ'],
            ['name' => 'Goodyear', 'state' => 'AZ'],
            ['name' => 'Flagstaff', 'state' => 'AZ'],
            ['name' => 'Buckeye', 'state' => 'AZ'],
            ['name' => 'Lake Havasu City', 'state' => 'AZ'],
            ['name' => 'Casa Grande', 'state' => 'AZ'],
            ['name' => 'Sierra Vista', 'state' => 'AZ'],
            ['name' => 'Maricopa', 'state' => 'AZ'],
            ['name' => 'Little Rock', 'state' => 'AR'],
            ['name' => 'Fort Smith', 'state' => 'AR'],
            ['name' => 'Fayetteville', 'state' => 'AR'],
            ['name' => 'Springdale', 'state' => 'AR'],
            ['name' => 'Jonesboro', 'state' => 'AR'],
            ['name' => 'North Little Rock', 'state' => 'AR'],
            ['name' => 'Conway', 'state' => 'AR'],
            ['name' => 'Rogers', 'state' => 'AR'],
            ['name' => 'Pine Bluff', 'state' => 'AR'],
            ['name' => 'Bentonville', 'state' => 'AR'],
            ['name' => 'Hot Springs', 'state' => 'AR'],
            ['name' => 'Benton', 'state' => 'AR'],
            ['name' => 'Los Angeles', 'state' => 'CA'],
            ['name' => 'San Diego', 'state' => 'CA'],
            ['name' => 'San Jose', 'state' => 'CA'],
            ['name' => 'San Francisco', 'state' => 'CA'],
            ['name' => 'Fresno', 'state' => 'CA'],
            ['name' => 'Sacramento', 'state' => 'CA'],
            ['name' => 'Long Beach', 'state' => 'CA'],
            ['name' => 'Oakland', 'state' => 'CA'],
            ['name' => 'Bakersfield', 'state' => 'CA'],
            ['name' => 'Anaheim', 'state' => 'CA'],
            ['name' => 'Santa Ana', 'state' => 'CA'],
            ['name' => 'Riverside', 'state' => 'CA'],
            ['name' => 'Stockton', 'state' => 'CA'],
            ['name' => 'Irvine', 'state' => 'CA'],
            ['name' => 'Chula Vista', 'state' => 'CA'],
            ['name' => 'Fremont', 'state' => 'CA'],
            ['name' => 'San Bernardino', 'state' => 'CA'],
            ['name' => 'Modesto', 'state' => 'CA'],
            ['name' => 'Fontana', 'state' => 'CA'],
            ['name' => 'Moreno Valley', 'state' => 'CA'],
            ['name' => 'Glendale', 'state' => 'CA'],
            ['name' => 'Huntington Beach', 'state' => 'CA'],
            ['name' => 'Santa Clarita', 'state' => 'CA'],
            ['name' => 'Garden Grove', 'state' => 'CA'],
            ['name' => 'Oceanside', 'state' => 'CA'],
            ['name' => 'Rancho Cucamonga', 'state' => 'CA'],
            ['name' => 'Ontario', 'state' => 'CA'],
            ['name' => 'Santa Rosa', 'state' => 'CA'],
            ['name' => 'Elk Grove', 'state' => 'CA'],
            ['name' => 'Corona', 'state' => 'CA'],
            ['name' => 'Lancaster', 'state' => 'CA'],
            ['name' => 'Palmdale', 'state' => 'CA'],
            ['name' => 'Salinas', 'state' => 'CA'],
            ['name' => 'Pomona', 'state' => 'CA'],
            ['name' => 'Hayward', 'state' => 'CA'],
            ['name' => 'Escondido', 'state' => 'CA'],
            ['name' => 'Sunnyvale', 'state' => 'CA'],
            ['name' => 'Torrance', 'state' => 'CA'],
            ['name' => 'Pasadena', 'state' => 'CA'],
            ['name' => 'Orange', 'state' => 'CA'],
            ['name' => 'Fullerton', 'state' => 'CA'],
            ['name' => 'Thousand Oaks', 'state' => 'CA'],
            ['name' => 'Roseville', 'state' => 'CA'],
            ['name' => 'Concord', 'state' => 'CA'],
            ['name' => 'Simi Valley', 'state' => 'CA'],
            ['name' => 'Santa Clara', 'state' => 'CA'],
            ['name' => 'Victorville', 'state' => 'CA'],
            ['name' => 'Vallejo', 'state' => 'CA'],
            ['name' => 'Berkeley', 'state' => 'CA'],
            ['name' => 'El Monte', 'state' => 'CA'],
            ['name' => 'Downey', 'state' => 'CA'],
            ['name' => 'Costa Mesa', 'state' => 'CA'],
            ['name' => 'Inglewood', 'state' => 'CA'],
            ['name' => 'Carlsbad', 'state' => 'CA'],
            ['name' => 'San Buenaventura', 'state' => 'CA'],
            ['name' => 'Fairfield', 'state' => 'CA'],
            ['name' => 'West Covina', 'state' => 'CA'],
            ['name' => 'Murrieta', 'state' => 'CA'],
            ['name' => 'Richmond', 'state' => 'CA'],
            ['name' => 'Norwalk', 'state' => 'CA'],
            ['name' => 'Antioch', 'state' => 'CA'],
            ['name' => 'Temecula', 'state' => 'CA'],
            ['name' => 'Burbank', 'state' => 'CA'],
            ['name' => 'Daly City', 'state' => 'CA'],
            ['name' => 'Rialto', 'state' => 'CA'],
            ['name' => 'El Cajon', 'state' => 'CA'],
            ['name' => 'San Mateo', 'state' => 'CA'],
            ['name' => 'Clovis', 'state' => 'CA'],
            ['name' => 'Compton', 'state' => 'CA'],
            ['name' => 'Jurupa Valley', 'state' => 'CA'],
            ['name' => 'Vista', 'state' => 'CA'],
            ['name' => 'South Gate', 'state' => 'CA'],
            ['name' => 'Mission Viejo', 'state' => 'CA'],
            ['name' => 'Vacaville', 'state' => 'CA'],
            ['name' => 'Carson', 'state' => 'CA'],
            ['name' => 'Hesperia', 'state' => 'CA'],
            ['name' => 'Santa Maria', 'state' => 'CA'],
            ['name' => 'Redding', 'state' => 'CA'],
            ['name' => 'Westminster', 'state' => 'CA'],
            ['name' => 'Santa Monica', 'state' => 'CA'],
            ['name' => 'Chico', 'state' => 'CA'],
            ['name' => 'Newport Beach', 'state' => 'CA'],
            ['name' => 'San Leandro', 'state' => 'CA'],
            ['name' => 'San Marcos', 'state' => 'CA'],
            ['name' => 'Whittier', 'state' => 'CA'],
            ['name' => 'Hawthorne', 'state' => 'CA'],
            ['name' => 'Citrus Heights', 'state' => 'CA'],
            ['name' => 'Alhambra', 'state' => 'CA'],
            ['name' => 'Tracy', 'state' => 'CA'],
            ['name' => 'Livermore', 'state' => 'CA'],
            ['name' => 'Buena Park', 'state' => 'CA'],
            ['name' => 'Menifee', 'state' => 'CA'],
            ['name' => 'Hemet', 'state' => 'CA'],
            ['name' => 'Lakewood', 'state' => 'CA'],
            ['name' => 'Merced', 'state' => 'CA'],
            ['name' => 'Chino', 'state' => 'CA'],
            ['name' => 'Indio', 'state' => 'CA'],
            ['name' => 'Redwood City', 'state' => 'CA'],
            ['name' => 'Lake Forest', 'state' => 'CA'],
            ['name' => 'Napa', 'state' => 'CA'],
            ['name' => 'Tustin', 'state' => 'CA'],
            ['name' => 'Bellflower', 'state' => 'CA'],
            ['name' => 'Mountain View', 'state' => 'CA'],
            ['name' => 'Chino Hills', 'state' => 'CA'],
            ['name' => 'Baldwin Park', 'state' => 'CA'],
            ['name' => 'Alameda', 'state' => 'CA'],
            ['name' => 'Upland', 'state' => 'CA'],
            ['name' => 'San Ramon', 'state' => 'CA'],
            ['name' => 'Folsom', 'state' => 'CA'],
            ['name' => 'Pleasanton', 'state' => 'CA'],
            ['name' => 'Lynwood', 'state' => 'CA'],
            ['name' => 'Denver', 'state' => 'CO'],
            ['name' => 'Colorado Springs', 'state' => 'CO'],
            ['name' => 'Aurora', 'state' => 'CO'],
            ['name' => 'Fort Collins', 'state' => 'CO'],
            ['name' => 'Lakewood', 'state' => 'CO'],
            ['name' => 'Thornton', 'state' => 'CO'],
            ['name' => 'Arvada', 'state' => 'CO'],
            ['name' => 'Westminster', 'state' => 'CO'],
            ['name' => 'Pueblo', 'state' => 'CO'],
            ['name' => 'Centennial', 'state' => 'CO'],
            ['name' => 'Boulder', 'state' => 'CO'],
            ['name' => 'Greeley', 'state' => 'CO'],
            ['name' => 'Longmont', 'state' => 'CO'],
            ['name' => 'Loveland', 'state' => 'CO'],
            ['name' => 'Grand Junction', 'state' => 'CO'],
            ['name' => 'Broomfield', 'state' => 'CO'],
            ['name' => 'Castle Rock', 'state' => 'CO'],
            ['name' => 'Commerce City', 'state' => 'CO'],
            ['name' => 'Parker', 'state' => 'CO'],
            ['name' => 'Littleton', 'state' => 'CO'],
            ['name' => 'Bridgeport', 'state' => 'CT'],
            ['name' => 'New Haven', 'state' => 'CT'],
            ['name' => 'Stamford', 'state' => 'CT'],
            ['name' => 'Hartford', 'state' => 'CT'],
            ['name' => 'Waterbury', 'state' => 'CT'],
            ['name' => 'Norwalk', 'state' => 'CT'],
            ['name' => 'Danbury', 'state' => 'CT'],
            ['name' => 'New Britain', 'state' => 'CT'],
            ['name' => 'Meriden', 'state' => 'CT'],
            ['name' => 'Bristol', 'state' => 'CT'],
            ['name' => 'West Haven', 'state' => 'CT'],
            ['name' => 'Milford', 'state' => 'CT'],
            ['name' => 'Middletown', 'state' => 'CT'],
            ['name' => 'Norwich', 'state' => 'CT'],
            ['name' => 'Shelton', 'state' => 'CT'],
            ['name' => 'Wilmington', 'state' => 'DE'],
            ['name' => 'Dover', 'state' => 'DE'],
            ['name' => 'Newark', 'state' => 'DE'],
            ['name' => 'Middletown', 'state' => 'DE'],
            ['name' => 'Smyrna', 'state' => 'DE'],
            ['name' => 'Milford', 'state' => 'DE'],
            ['name' => 'Seaford', 'state' => 'DE'],
            ['name' => 'Georgetown', 'state' => 'DE'],
            ['name' => 'Elsmere', 'state' => 'DE'],
            ['name' => 'New Castle', 'state' => 'DE'],
            ['name' => 'Washington', 'state' => 'DC'],
            ['name' => 'Jacksonville', 'state' => 'FL'],
            ['name' => 'Miami', 'state' => 'FL'],
            ['name' => 'Tampa', 'state' => 'FL'],
            ['name' => 'Orlando', 'state' => 'FL'],
            ['name' => 'St. Petersburg', 'state' => 'FL'],
            ['name' => 'Hialeah', 'state' => 'FL'],
            ['name' => 'Tallahassee', 'state' => 'FL'],
            ['name' => 'Fort Lauderdale', 'state' => 'FL'],
            ['name' => 'Port St. Lucie', 'state' => 'FL'],
            ['name' => 'Cape Coral', 'state' => 'FL'],
            ['name' => 'Pembroke Pines', 'state' => 'FL'],
            ['name' => 'Hollywood', 'state' => 'FL'],
            ['name' => 'Miramar', 'state' => 'FL'],
            ['name' => 'Gainesville', 'state' => 'FL'],
            ['name' => 'Coral Springs', 'state' => 'FL'],
            ['name' => 'Miami Gardens', 'state' => 'FL'],
            ['name' => 'Clearwater', 'state' => 'FL'],
            ['name' => 'Palm Bay', 'state' => 'FL'],
            ['name' => 'Pompano Beach', 'state' => 'FL'],
            ['name' => 'West Palm Beach', 'state' => 'FL'],
            ['name' => 'Lakeland', 'state' => 'FL'],
            ['name' => 'Davie', 'state' => 'FL'],
            ['name' => 'Miami Beach', 'state' => 'FL'],
            ['name' => 'Sunrise', 'state' => 'FL'],
            ['name' => 'Plantation', 'state' => 'FL'],
            ['name' => 'Boca Raton', 'state' => 'FL'],
            ['name' => 'Deltona', 'state' => 'FL'],
            ['name' => 'Largo', 'state' => 'FL'],
            ['name' => 'Deerfield Beach', 'state' => 'FL'],
            ['name' => 'Palm Coast', 'state' => 'FL'],
            ['name' => 'Melbourne', 'state' => 'FL'],
            ['name' => 'Boynton Beach', 'state' => 'FL'],
            ['name' => 'Lauderhill', 'state' => 'FL'],
            ['name' => 'Weston', 'state' => 'FL'],
            ['name' => 'Fort Myers', 'state' => 'FL'],
            ['name' => 'Kissimmee', 'state' => 'FL'],
            ['name' => 'Homestead', 'state' => 'FL'],
            ['name' => 'Tamarac', 'state' => 'FL'],
            ['name' => 'Delray Beach', 'state' => 'FL'],
            ['name' => 'Daytona Beach', 'state' => 'FL'],
            ['name' => 'North Miami', 'state' => 'FL'],
            ['name' => 'Wellington', 'state' => 'FL'],
            ['name' => 'North Port', 'state' => 'FL'],
            ['name' => 'Jupiter', 'state' => 'FL'],
            ['name' => 'Ocala', 'state' => 'FL'],
            ['name' => 'Port Orange', 'state' => 'FL'],
            ['name' => 'Margate', 'state' => 'FL'],
            ['name' => 'Coconut Creek', 'state' => 'FL'],
            ['name' => 'Sanford', 'state' => 'FL'],
            ['name' => 'Sarasota', 'state' => 'FL'],
            ['name' => 'Pensacola', 'state' => 'FL'],
            ['name' => 'Bradenton', 'state' => 'FL'],
            ['name' => 'Pinellas Park', 'state' => 'FL'],
            ['name' => 'Coral Gables', 'state' => 'FL'],
            ['name' => 'Doral', 'state' => 'FL'],
            ['name' => 'Bonita Springs', 'state' => 'FL'],
            ['name' => 'Apopka', 'state' => 'FL'],
            ['name' => 'Titusville', 'state' => 'FL'],
            ['name' => 'North Miami Beach', 'state' => 'FL'],
            ['name' => 'Oakland Park', 'state' => 'FL'],
            ['name' => 'Fort Pierce', 'state' => 'FL'],
            ['name' => 'Winter Haven', 'state' => 'FL'],
            ['name' => 'Winter Garden', 'state' => 'FL'],
            ['name' => 'St. Cloud', 'state' => 'FL'],
            ['name' => 'Atlanta', 'state' => 'GA'],
            ['name' => 'Augusta', 'state' => 'GA'],
            ['name' => 'Columbus', 'state' => 'GA'],
            ['name' => 'Macon', 'state' => 'GA'],
            ['name' => 'Savannah', 'state' => 'GA'],
            ['name' => 'Athens', 'state' => 'GA'],
            ['name' => 'Sandy Springs', 'state' => 'GA'],
            ['name' => 'Roswell', 'state' => 'GA'],
            ['name' => 'Johns Creek', 'state' => 'GA'],
            ['name' => 'Albany', 'state' => 'GA'],
            ['name' => 'Warner Robins', 'state' => 'GA'],
            ['name' => 'Alpharetta', 'state' => 'GA'],
            ['name' => 'Marietta', 'state' => 'GA'],
            ['name' => 'Valdosta', 'state' => 'GA'],
            ['name' => 'Smyrna', 'state' => 'GA'],
            ['name' => 'Dunwoody', 'state' => 'GA'],
            ['name' => 'Brookhaven', 'state' => 'GA'],
            ['name' => 'Peachtree Corners', 'state' => 'GA'],
            ['name' => 'Gainesville', 'state' => 'GA'],
            ['name' => 'Newnan', 'state' => 'GA'],
            ['name' => 'Honolulu', 'state' => 'HI'],
            ['name' => 'Pearl City', 'state' => 'HI'],
            ['name' => 'Hilo', 'state' => 'HI'],
            ['name' => 'Kailua', 'state' => 'HI'],
            ['name' => 'Waipahu', 'state' => 'HI'],
            ['name' => 'Kaneohe', 'state' => 'HI'],
            ['name' => 'Mililani Town', 'state' => 'HI'],
            ['name' => 'Kahului', 'state' => 'HI'],
            ['name' => 'Ewa Gentry', 'state' => 'HI'],
            ['name' => 'Kapolei', 'state' => 'HI'],
            ['name' => 'Boise', 'state' => 'ID'],
            ['name' => 'Meridian', 'state' => 'ID'],
            ['name' => 'Nampa', 'state' => 'ID'],
            ['name' => 'Idaho Falls', 'state' => 'ID'],
            ['name' => 'Pocatello', 'state' => 'ID'],
            ['name' => 'Caldwell', 'state' => 'ID'],
            ['name' => 'Coeur d Alene', 'state' => 'ID'],
            ['name' => 'Twin Falls', 'state' => 'ID'],
            ['name' => 'Lewiston', 'state' => 'ID'],
            ['name' => 'Post Falls', 'state' => 'ID'],
            ['name' => 'Rexburg', 'state' => 'ID'],
            ['name' => 'Eagle', 'state' => 'ID'],
            ['name' => 'Chicago', 'state' => 'IL'],
            ['name' => 'Aurora', 'state' => 'IL'],
            ['name' => 'Rockford', 'state' => 'IL'],
            ['name' => 'Joliet', 'state' => 'IL'],
            ['name' => 'Naperville', 'state' => 'IL'],
            ['name' => 'Springfield', 'state' => 'IL'],
            ['name' => 'Peoria', 'state' => 'IL'],
            ['name' => 'Elgin', 'state' => 'IL'],
            ['name' => 'Waukegan', 'state' => 'IL'],
            ['name' => 'Champaign', 'state' => 'IL'],
            ['name' => 'Bloomington', 'state' => 'IL'],
            ['name' => 'Decatur', 'state' => 'IL'],
            ['name' => 'Evanston', 'state' => 'IL'],
            ['name' => 'Des Plaines', 'state' => 'IL'],
            ['name' => 'Berwyn', 'state' => 'IL'],
            ['name' => 'Wheaton', 'state' => 'IL'],
            ['name' => 'Belleville', 'state' => 'IL'],
            ['name' => 'Elmhurst', 'state' => 'IL'],
            ['name' => 'Urbana', 'state' => 'IL'],
            ['name' => 'Moline', 'state' => 'IL'],
            ['name' => 'Indianapolis', 'state' => 'IN'],
            ['name' => 'Fort Wayne', 'state' => 'IN'],
            ['name' => 'Evansville', 'state' => 'IN'],
            ['name' => 'South Bend', 'state' => 'IN'],
            ['name' => 'Carmel', 'state' => 'IN'],
            ['name' => 'Bloomington', 'state' => 'IN'],
            ['name' => 'Fishers', 'state' => 'IN'],
            ['name' => 'Hammond', 'state' => 'IN'],
            ['name' => 'Gary', 'state' => 'IN'],
            ['name' => 'Lafayette', 'state' => 'IN'],
            ['name' => 'Muncie', 'state' => 'IN'],
            ['name' => 'Terre Haute', 'state' => 'IN'],
            ['name' => 'Kokomo', 'state' => 'IN'],
            ['name' => 'Anderson', 'state' => 'IN'],
            ['name' => 'Noblesville', 'state' => 'IN'],
            ['name' => 'Greenwood', 'state' => 'IN'],
            ['name' => 'Elkhart', 'state' => 'IN'],
            ['name' => 'Mishawaka', 'state' => 'IN'],
            ['name' => 'Lawrence', 'state' => 'IN'],
            ['name' => 'Jeffersonville', 'state' => 'IN'],
            ['name' => 'Des Moines', 'state' => 'IA'],
            ['name' => 'Cedar Rapids', 'state' => 'IA'],
            ['name' => 'Davenport', 'state' => 'IA'],
            ['name' => 'Sioux City', 'state' => 'IA'],
            ['name' => 'Iowa City', 'state' => 'IA'],
            ['name' => 'Waterloo', 'state' => 'IA'],
            ['name' => 'Ames', 'state' => 'IA'],
            ['name' => 'West Des Moines', 'state' => 'IA'],
            ['name' => 'Council Bluffs', 'state' => 'IA'],
            ['name' => 'Ankeny', 'state' => 'IA'],
            ['name' => 'Dubuque', 'state' => 'IA'],
            ['name' => 'Urbandale', 'state' => 'IA'],
            ['name' => 'Cedar Falls', 'state' => 'IA'],
            ['name' => 'Marion', 'state' => 'IA'],
            ['name' => 'Bettendorf', 'state' => 'IA'],
            ['name' => 'Wichita', 'state' => 'KS'],
            ['name' => 'Overland Park', 'state' => 'KS'],
            ['name' => 'Kansas City', 'state' => 'KS'],
            ['name' => 'Olathe', 'state' => 'KS'],
            ['name' => 'Topeka', 'state' => 'KS'],
            ['name' => 'Lawrence', 'state' => 'KS'],
            ['name' => 'Shawnee', 'state' => 'KS'],
            ['name' => 'Manhattan', 'state' => 'KS'],
            ['name' => 'Lenexa', 'state' => 'KS'],
            ['name' => 'Salina', 'state' => 'KS'],
            ['name' => 'Hutchinson', 'state' => 'KS'],
            ['name' => 'Leavenworth', 'state' => 'KS'],
            ['name' => 'Leawood', 'state' => 'KS'],
            ['name' => 'Dodge City', 'state' => 'KS'],
            ['name' => 'Garden City', 'state' => 'KS'],
            ['name' => 'Louisville', 'state' => 'KY'],
            ['name' => 'Lexington', 'state' => 'KY'],
            ['name' => 'Bowling Green', 'state' => 'KY'],
            ['name' => 'Owensboro', 'state' => 'KY'],
            ['name' => 'Covington', 'state' => 'KY'],
            ['name' => 'Hopkinsville', 'state' => 'KY'],
            ['name' => 'Richmond', 'state' => 'KY'],
            ['name' => 'Florence', 'state' => 'KY'],
            ['name' => 'Georgetown', 'state' => 'KY'],
            ['name' => 'Elizabethtown', 'state' => 'KY'],
            ['name' => 'Nicholasville', 'state' => 'KY'],
            ['name' => 'Henderson', 'state' => 'KY'],
            ['name' => 'Frankfort', 'state' => 'KY'],
            ['name' => 'Paducah', 'state' => 'KY'],
            ['name' => 'Ashland', 'state' => 'KY'],
            ['name' => 'New Orleans', 'state' => 'LA'],
            ['name' => 'Baton Rouge', 'state' => 'LA'],
            ['name' => 'Shreveport', 'state' => 'LA'],
            ['name' => 'Metairie', 'state' => 'LA'],
            ['name' => 'Lafayette', 'state' => 'LA'],
            ['name' => 'Lake Charles', 'state' => 'LA'],
            ['name' => 'Kenner', 'state' => 'LA'],
            ['name' => 'Bossier City', 'state' => 'LA'],
            ['name' => 'Monroe', 'state' => 'LA'],
            ['name' => 'Alexandria', 'state' => 'LA'],
            ['name' => 'Houma', 'state' => 'LA'],
            ['name' => 'Marrero', 'state' => 'LA'],
            ['name' => 'New Iberia', 'state' => 'LA'],
            ['name' => 'Laplace', 'state' => 'LA'],
            ['name' => 'Slidell', 'state' => 'LA'],
            ['name' => 'Portland', 'state' => 'ME'],
            ['name' => 'Lewiston', 'state' => 'ME'],
            ['name' => 'Bangor', 'state' => 'ME'],
            ['name' => 'South Portland', 'state' => 'ME'],
            ['name' => 'Auburn', 'state' => 'ME'],
            ['name' => 'Biddeford', 'state' => 'ME'],
            ['name' => 'Sanford', 'state' => 'ME'],
            ['name' => 'Saco', 'state' => 'ME'],
            ['name' => 'Westbrook', 'state' => 'ME'],
            ['name' => 'Augusta', 'state' => 'ME'],
            ['name' => 'Baltimore', 'state' => 'MD'],
            ['name' => 'Frederick', 'state' => 'MD'],
            ['name' => 'Rockville', 'state' => 'MD'],
            ['name' => 'Gaithersburg', 'state' => 'MD'],
            ['name' => 'Bowie', 'state' => 'MD'],
            ['name' => 'Hagerstown', 'state' => 'MD'],
            ['name' => 'Annapolis', 'state' => 'MD'],
            ['name' => 'College Park', 'state' => 'MD'],
            ['name' => 'Salisbury', 'state' => 'MD'],
            ['name' => 'Laurel', 'state' => 'MD'],
            ['name' => 'Greenbelt', 'state' => 'MD'],
            ['name' => 'Cumberland', 'state' => 'MD'],
            ['name' => 'Cambridge', 'state' => 'MD'],
            ['name' => 'Westminster', 'state' => 'MD'],
            ['name' => 'Hyattsville', 'state' => 'MD'],
            ['name' => 'Boston', 'state' => 'MA'],
            ['name' => 'Worcester', 'state' => 'MA'],
            ['name' => 'Springfield', 'state' => 'MA'],
            ['name' => 'Lowell', 'state' => 'MA'],
            ['name' => 'Cambridge', 'state' => 'MA'],
            ['name' => 'New Bedford', 'state' => 'MA'],
            ['name' => 'Brockton', 'state' => 'MA'],
            ['name' => 'Quincy', 'state' => 'MA'],
            ['name' => 'Lynn', 'state' => 'MA'],
            ['name' => 'Fall River', 'state' => 'MA'],
            ['name' => 'Newton', 'state' => 'MA'],
            ['name' => 'Lawrence', 'state' => 'MA'],
            ['name' => 'Somerville', 'state' => 'MA'],
            ['name' => 'Framingham', 'state' => 'MA'],
            ['name' => 'Haverhill', 'state' => 'MA'],
            ['name' => 'Waltham', 'state' => 'MA'],
            ['name' => 'Malden', 'state' => 'MA'],
            ['name' => 'Brookline', 'state' => 'MA'],
            ['name' => 'Plymouth', 'state' => 'MA'],
            ['name' => 'Medford', 'state' => 'MA'],
            ['name' => 'Detroit', 'state' => 'MI'],
            ['name' => 'Grand Rapids', 'state' => 'MI'],
            ['name' => 'Warren', 'state' => 'MI'],
            ['name' => 'Sterling Heights', 'state' => 'MI'],
            ['name' => 'Ann Arbor', 'state' => 'MI'],
            ['name' => 'Lansing', 'state' => 'MI'],
            ['name' => 'Flint', 'state' => 'MI'],
            ['name' => 'Dearborn', 'state' => 'MI'],
            ['name' => 'Livonia', 'state' => 'MI'],
            ['name' => 'Troy', 'state' => 'MI'],
            ['name' => 'Westland', 'state' => 'MI'],
            ['name' => 'Farmington Hills', 'state' => 'MI'],
            ['name' => 'Kalamazoo', 'state' => 'MI'],
            ['name' => 'Wyoming', 'state' => 'MI'],
            ['name' => 'Southfield', 'state' => 'MI'],
            ['name' => 'Rochester Hills', 'state' => 'MI'],
            ['name' => 'Taylor', 'state' => 'MI'],
            ['name' => 'Pontiac', 'state' => 'MI'],
            ['name' => 'St. Clair Shores', 'state' => 'MI'],
            ['name' => 'Royal Oak', 'state' => 'MI'],
            ['name' => 'Minneapolis', 'state' => 'MN'],
            ['name' => 'St. Paul', 'state' => 'MN'],
            ['name' => 'Rochester', 'state' => 'MN'],
            ['name' => 'Duluth', 'state' => 'MN'],
            ['name' => 'Bloomington', 'state' => 'MN'],
            ['name' => 'Brooklyn Park', 'state' => 'MN'],
            ['name' => 'Plymouth', 'state' => 'MN'],
            ['name' => 'St. Cloud', 'state' => 'MN'],
            ['name' => 'Eagan', 'state' => 'MN'],
            ['name' => 'Woodbury', 'state' => 'MN'],
            ['name' => 'Maple Grove', 'state' => 'MN'],
            ['name' => 'Eden Prairie', 'state' => 'MN'],
            ['name' => 'Coon Rapids', 'state' => 'MN'],
            ['name' => 'Burnsville', 'state' => 'MN'],
            ['name' => 'Blaine', 'state' => 'MN'],
            ['name' => 'Lakeville', 'state' => 'MN'],
            ['name' => 'Minnetonka', 'state' => 'MN'],
            ['name' => 'Apple Valley', 'state' => 'MN'],
            ['name' => 'Edina', 'state' => 'MN'],
            ['name' => 'St. Louis Park', 'state' => 'MN'],
            ['name' => 'Jackson', 'state' => 'MS'],
            ['name' => 'Gulfport', 'state' => 'MS'],
            ['name' => 'Southaven', 'state' => 'MS'],
            ['name' => 'Hattiesburg', 'state' => 'MS'],
            ['name' => 'Biloxi', 'state' => 'MS'],
            ['name' => 'Meridian', 'state' => 'MS'],
            ['name' => 'Tupelo', 'state' => 'MS'],
            ['name' => 'Olive Branch', 'state' => 'MS'],
            ['name' => 'Greenville', 'state' => 'MS'],
            ['name' => 'Horn Lake', 'state' => 'MS'],
            ['name' => 'Clinton', 'state' => 'MS'],
            ['name' => 'Pearl', 'state' => 'MS'],
            ['name' => 'Starkville', 'state' => 'MS'],
            ['name' => 'Ridgeland', 'state' => 'MS'],
            ['name' => 'Columbus', 'state' => 'MS'],
            ['name' => 'Kansas City', 'state' => 'MO'],
            ['name' => 'St. Louis', 'state' => 'MO'],
            ['name' => 'Springfield', 'state' => 'MO'],
            ['name' => 'Columbia', 'state' => 'MO'],
            ['name' => 'Independence', 'state' => 'MO'],
            ['name' => 'Lee\'s Summit', 'state' => 'MO'],
            ['name' => 'O\'Fallon', 'state' => 'MO'],
            ['name' => 'St. Joseph', 'state' => 'MO'],
            ['name' => 'St. Charles', 'state' => 'MO'],
            ['name' => 'St. Peters', 'state' => 'MO'],
            ['name' => 'Blue Springs', 'state' => 'MO'],
            ['name' => 'Florissant', 'state' => 'MO'],
            ['name' => 'Joplin', 'state' => 'MO'],
            ['name' => 'Chesterfield', 'state' => 'MO'],
            ['name' => 'Jefferson City', 'state' => 'MO'],
            ['name' => 'Cape Girardeau', 'state' => 'MO'],
            ['name' => 'Wildwood', 'state' => 'MO'],
            ['name' => 'University City', 'state' => 'MO'],
            ['name' => 'Ballwin', 'state' => 'MO'],
            ['name' => 'Raytown', 'state' => 'MO'],
            ['name' => 'Billings', 'state' => 'MT'],
            ['name' => 'Missoula', 'state' => 'MT'],
            ['name' => 'Great Falls', 'state' => 'MT'],
            ['name' => 'Bozeman', 'state' => 'MT'],
            ['name' => 'Butte', 'state' => 'MT'],
            ['name' => 'Helena', 'state' => 'MT'],
            ['name' => 'Kalispell', 'state' => 'MT'],
            ['name' => 'Havre', 'state' => 'MT'],
            ['name' => 'Anaconda', 'state' => 'MT'],
            ['name' => 'Miles City', 'state' => 'MT'],
            ['name' => 'Omaha', 'state' => 'NE'],
            ['name' => 'Lincoln', 'state' => 'NE'],
            ['name' => 'Bellevue', 'state' => 'NE'],
            ['name' => 'Grand Island', 'state' => 'NE'],
            ['name' => 'Kearney', 'state' => 'NE'],
            ['name' => 'Fremont', 'state' => 'NE'],
            ['name' => 'Hastings', 'state' => 'NE'],
            ['name' => 'Norfolk', 'state' => 'NE'],
            ['name' => 'North Platte', 'state' => 'NE'],
            ['name' => 'Columbus', 'state' => 'NE'],
            ['name' => 'Papillion', 'state' => 'NE'],
            ['name' => 'La Vista', 'state' => 'NE'],
            ['name' => 'Las Vegas', 'state' => 'NV'],
            ['name' => 'Henderson', 'state' => 'NV'],
            ['name' => 'Reno', 'state' => 'NV'],
            ['name' => 'North Las Vegas', 'state' => 'NV'],
            ['name' => 'Sparks', 'state' => 'NV'],
            ['name' => 'Carson City', 'state' => 'NV'],
            ['name' => 'Fernley', 'state' => 'NV'],
            ['name' => 'Elko', 'state' => 'NV'],
            ['name' => 'Mesquite', 'state' => 'NV'],
            ['name' => 'Boulder City', 'state' => 'NV'],
            ['name' => 'Fallon', 'state' => 'NV'],
            ['name' => 'Winnemucca', 'state' => 'NV'],
            ['name' => 'Manchester', 'state' => 'NH'],
            ['name' => 'Nashua', 'state' => 'NH'],
            ['name' => 'Concord', 'state' => 'NH'],
            ['name' => 'Derry', 'state' => 'NH'],
            ['name' => 'Dover', 'state' => 'NH'],
            ['name' => 'Rochester', 'state' => 'NH'],
            ['name' => 'Salem', 'state' => 'NH'],
            ['name' => 'Merrimack', 'state' => 'NH'],
            ['name' => 'Hudson', 'state' => 'NH'],
            ['name' => 'Londonderry', 'state' => 'NH'],
            ['name' => 'Keene', 'state' => 'NH'],
            ['name' => 'Bedford', 'state' => 'NH'],
            ['name' => 'Portsmouth', 'state' => 'NH'],
            ['name' => 'Goffstown', 'state' => 'NH'],
            ['name' => 'Laconia', 'state' => 'NH'],
            ['name' => 'Newark', 'state' => 'NJ'],
            ['name' => 'Jersey City', 'state' => 'NJ'],
            ['name' => 'Paterson', 'state' => 'NJ'],
            ['name' => 'Elizabeth', 'state' => 'NJ'],
            ['name' => 'Edison', 'state' => 'NJ'],
            ['name' => 'Woodbridge', 'state' => 'NJ'],
            ['name' => 'Lakewood', 'state' => 'NJ'],
            ['name' => 'Toms River', 'state' => 'NJ'],
            ['name' => 'Hamilton', 'state' => 'NJ'],
            ['name' => 'Trenton', 'state' => 'NJ'],
            ['name' => 'Clifton', 'state' => 'NJ'],
            ['name' => 'Camden', 'state' => 'NJ'],
            ['name' => 'Brick', 'state' => 'NJ'],
            ['name' => 'Cherry Hill', 'state' => 'NJ'],
            ['name' => 'Passaic', 'state' => 'NJ'],
            ['name' => 'Middletown', 'state' => 'NJ'],
            ['name' => 'Union City', 'state' => 'NJ'],
            ['name' => 'Old Bridge', 'state' => 'NJ'],
            ['name' => 'Gloucester Township', 'state' => 'NJ'],
            ['name' => 'East Orange', 'state' => 'NJ'],
            ['name' => 'Albuquerque', 'state' => 'NM'],
            ['name' => 'Las Cruces', 'state' => 'NM'],
            ['name' => 'Rio Rancho', 'state' => 'NM'],
            ['name' => 'Santa Fe', 'state' => 'NM'],
            ['name' => 'Roswell', 'state' => 'NM'],
            ['name' => 'Farmington', 'state' => 'NM'],
            ['name' => 'Clovis', 'state' => 'NM'],
            ['name' => 'Hobbs', 'state' => 'NM'],
            ['name' => 'Alamogordo', 'state' => 'NM'],
            ['name' => 'Carlsbad', 'state' => 'NM'],
            ['name' => 'Gallup', 'state' => 'NM'],
            ['name' => 'Deming', 'state' => 'NM'],
            ['name' => 'Los Lunas', 'state' => 'NM'],
            ['name' => 'Sunland Park', 'state' => 'NM'],
            ['name' => 'Las Vegas', 'state' => 'NM'],
            ['name' => 'New York City', 'state' => 'NY'],
            ['name' => 'Buffalo', 'state' => 'NY'],
            ['name' => 'Rochester', 'state' => 'NY'],
            ['name' => 'Yonkers', 'state' => 'NY'],
            ['name' => 'Syracuse', 'state' => 'NY'],
            ['name' => 'Albany', 'state' => 'NY'],
            ['name' => 'New Rochelle', 'state' => 'NY'],
            ['name' => 'Mount Vernon', 'state' => 'NY'],
            ['name' => 'Schenectady', 'state' => 'NY'],
            ['name' => 'Utica', 'state' => 'NY'],
            ['name' => 'White Plains', 'state' => 'NY'],
            ['name' => 'Hempstead', 'state' => 'NY'],
            ['name' => 'Troy', 'state' => 'NY'],
            ['name' => 'Niagara Falls', 'state' => 'NY'],
            ['name' => 'Binghamton', 'state' => 'NY'],
            ['name' => 'Freeport', 'state' => 'NY'],
            ['name' => 'Valley Stream', 'state' => 'NY'],
            ['name' => 'Long Beach', 'state' => 'NY'],
            ['name' => 'Spring Valley', 'state' => 'NY'],
            ['name' => 'Rome', 'state' => 'NY'],
            ['name' => 'Charlotte', 'state' => 'NC'],
            ['name' => 'Raleigh', 'state' => 'NC'],
            ['name' => 'Greensboro', 'state' => 'NC'],
            ['name' => 'Durham', 'state' => 'NC'],
            ['name' => 'Winston-Salem', 'state' => 'NC'],
            ['name' => 'Fayetteville', 'state' => 'NC'],
            ['name' => 'Cary', 'state' => 'NC'],
            ['name' => 'Wilmington', 'state' => 'NC'],
            ['name' => 'High Point', 'state' => 'NC'],
            ['name' => 'Concord', 'state' => 'NC'],
            ['name' => 'Greenville', 'state' => 'NC'],
            ['name' => 'Asheville', 'state' => 'NC'],
            ['name' => 'Gastonia', 'state' => 'NC'],
            ['name' => 'Jacksonville', 'state' => 'NC'],
            ['name' => 'Chapel Hill', 'state' => 'NC'],
            ['name' => 'Rocky Mount', 'state' => 'NC'],
            ['name' => 'Burlington', 'state' => 'NC'],
            ['name' => 'Huntersville', 'state' => 'NC'],
            ['name' => 'Kannapolis', 'state' => 'NC'],
            ['name' => 'Apex', 'state' => 'NC'],
            ['name' => 'Fargo', 'state' => 'ND'],
            ['name' => 'Bismarck', 'state' => 'ND'],
            ['name' => 'Grand Forks', 'state' => 'ND'],
            ['name' => 'Minot', 'state' => 'ND'],
            ['name' => 'West Fargo', 'state' => 'ND'],
            ['name' => 'Williston', 'state' => 'ND'],
            ['name' => 'Dickinson', 'state' => 'ND'],
            ['name' => 'Mandan', 'state' => 'ND'],
            ['name' => 'Jamestown', 'state' => 'ND'],
            ['name' => 'Wahpeton', 'state' => 'ND'],
            ['name' => 'Columbus', 'state' => 'OH'],
            ['name' => 'Cleveland', 'state' => 'OH'],
            ['name' => 'Cincinnati', 'state' => 'OH'],
            ['name' => 'Toledo', 'state' => 'OH'],
            ['name' => 'Akron', 'state' => 'OH'],
            ['name' => 'Dayton', 'state' => 'OH'],
            ['name' => 'Parma', 'state' => 'OH'],
            ['name' => 'Canton', 'state' => 'OH'],
            ['name' => 'Youngstown', 'state' => 'OH'],
            ['name' => 'Lorain', 'state' => 'OH'],
            ['name' => 'Hamilton', 'state' => 'OH'],
            ['name' => 'Springfield', 'state' => 'OH'],
            ['name' => 'Kettering', 'state' => 'OH'],
            ['name' => 'Elyria', 'state' => 'OH'],
            ['name' => 'Lakewood', 'state' => 'OH'],
            ['name' => 'Cuyahoga Falls', 'state' => 'OH'],
            ['name' => 'Euclid', 'state' => 'OH'],
            ['name' => 'Dublin', 'state' => 'OH'],
            ['name' => 'Middletown', 'state' => 'OH'],
            ['name' => 'Newark', 'state' => 'OH'],
            ['name' => 'Oklahoma City', 'state' => 'OK'],
            ['name' => 'Tulsa', 'state' => 'OK'],
            ['name' => 'Norman', 'state' => 'OK'],
            ['name' => 'Broken Arrow', 'state' => 'OK'],
            ['name' => 'Lawton', 'state' => 'OK'],
            ['name' => 'Edmond', 'state' => 'OK'],
            ['name' => 'Moore', 'state' => 'OK'],
            ['name' => 'Midwest City', 'state' => 'OK'],
            ['name' => 'Enid', 'state' => 'OK'],
            ['name' => 'Stillwater', 'state' => 'OK'],
            ['name' => 'Muskogee', 'state' => 'OK'],
            ['name' => 'Bartlesville', 'state' => 'OK'],
            ['name' => 'Shawnee', 'state' => 'OK'],
            ['name' => 'Owasso', 'state' => 'OK'],
            ['name' => 'Ponca City', 'state' => 'OK'],
            ['name' => 'Portland', 'state' => 'OR'],
            ['name' => 'Eugene', 'state' => 'OR'],
            ['name' => 'Salem', 'state' => 'OR'],
            ['name' => 'Gresham', 'state' => 'OR'],
            ['name' => 'Hillsboro', 'state' => 'OR'],
            ['name' => 'Beaverton', 'state' => 'OR'],
            ['name' => 'Bend', 'state' => 'OR'],
            ['name' => 'Medford', 'state' => 'OR'],
            ['name' => 'Springfield', 'state' => 'OR'],
            ['name' => 'Corvallis', 'state' => 'OR'],
            ['name' => 'Albany', 'state' => 'OR'],
            ['name' => 'Tigard', 'state' => 'OR'],
            ['name' => 'Lake Oswego', 'state' => 'OR'],
            ['name' => 'Keizer', 'state' => 'OR'],
            ['name' => 'Grants Pass', 'state' => 'OR'],
            ['name' => 'Oregon City', 'state' => 'OR'],
            ['name' => 'McMinnville', 'state' => 'OR'],
            ['name' => 'Redmond', 'state' => 'OR'],
            ['name' => 'Tualatin', 'state' => 'OR'],
            ['name' => 'West Linn', 'state' => 'OR'],
            ['name' => 'Philadelphia', 'state' => 'PA'],
            ['name' => 'Pittsburgh', 'state' => 'PA'],
            ['name' => 'Allentown', 'state' => 'PA'],
            ['name' => 'Reading', 'state' => 'PA'],
            ['name' => 'Scranton', 'state' => 'PA'],
            ['name' => 'Bethlehem', 'state' => 'PA'],
            ['name' => 'Lancaster', 'state' => 'PA'],
            ['name' => 'Harrisburg', 'state' => 'PA'],
            ['name' => 'Altoona', 'state' => 'PA'],
            ['name' => 'Erie', 'state' => 'PA'],
            ['name' => 'York', 'state' => 'PA'],
            ['name' => 'Wilkes-Barre', 'state' => 'PA'],
            ['name' => 'State College', 'state' => 'PA'],
            ['name' => 'Chester', 'state' => 'PA'],
            ['name' => 'Williamsport', 'state' => 'PA'],
            ['name' => 'Easton', 'state' => 'PA'],
            ['name' => 'Lebanon', 'state' => 'PA'],
            ['name' => 'Hazleton', 'state' => 'PA'],
            ['name' => 'New Castle', 'state' => 'PA'],
            ['name' => 'Johnstown', 'state' => 'PA'],
            ['name' => 'Providence', 'state' => 'RI'],
            ['name' => 'Warwick', 'state' => 'RI'],
            ['name' => 'Cranston', 'state' => 'RI'],
            ['name' => 'Pawtucket', 'state' => 'RI'],
            ['name' => 'East Providence', 'state' => 'RI'],
            ['name' => 'Woonsocket', 'state' => 'RI'],
            ['name' => 'Newport', 'state' => 'RI'],
            ['name' => 'Central Falls', 'state' => 'RI'],
            ['name' => 'Westerly', 'state' => 'RI'],
            ['name' => 'North Providence', 'state' => 'RI'],
            ['name' => 'Charleston', 'state' => 'SC'],
            ['name' => 'Columbia', 'state' => 'SC'],
            ['name' => 'North Charleston', 'state' => 'SC'],
            ['name' => 'Mount Pleasant', 'state' => 'SC'],
            ['name' => 'Rock Hill', 'state' => 'SC'],
            ['name' => 'Greenville', 'state' => 'SC'],
            ['name' => 'Summerville', 'state' => 'SC'],
            ['name' => 'Sumter', 'state' => 'SC'],
            ['name' => 'Goose Creek', 'state' => 'SC'],
            ['name' => 'Hilton Head Island', 'state' => 'SC'],
            ['name' => 'Spartanburg', 'state' => 'SC'],
            ['name' => 'Florence', 'state' => 'SC'],
            ['name' => 'Myrtle Beach', 'state' => 'SC'],
            ['name' => 'Anderson', 'state' => 'SC'],
            ['name' => 'Aiken', 'state' => 'SC'],
            ['name' => 'Sioux Falls', 'state' => 'SD'],
            ['name' => 'Rapid City', 'state' => 'SD'],
            ['name' => 'Aberdeen', 'state' => 'SD'],
            ['name' => 'Brookings', 'state' => 'SD'],
            ['name' => 'Watertown', 'state' => 'SD'],
            ['name' => 'Mitchell', 'state' => 'SD'],
            ['name' => 'Yankton', 'state' => 'SD'],
            ['name' => 'Pierre', 'state' => 'SD'],
            ['name' => 'Huron', 'state' => 'SD'],
            ['name' => 'Spearfish', 'state' => 'SD'],
            ['name' => 'Nashville', 'state' => 'TN'],
            ['name' => 'Memphis', 'state' => 'TN'],
            ['name' => 'Knoxville', 'state' => 'TN'],
            ['name' => 'Chattanooga', 'state' => 'TN'],
            ['name' => 'Clarksville', 'state' => 'TN'],
            ['name' => 'Murfreesboro', 'state' => 'TN'],
            ['name' => 'Franklin', 'state' => 'TN'],
            ['name' => 'Jackson', 'state' => 'TN'],
            ['name' => 'Johnson City', 'state' => 'TN'],
            ['name' => 'Bartlett', 'state' => 'TN'],
            ['name' => 'Hendersonville', 'state' => 'TN'],
            ['name' => 'Kingsport', 'state' => 'TN'],
            ['name' => 'Collierville', 'state' => 'TN'],
            ['name' => 'Smyrna', 'state' => 'TN'],
            ['name' => 'Cleveland', 'state' => 'TN'],
            ['name' => 'Brentwood', 'state' => 'TN'],
            ['name' => 'Germantown', 'state' => 'TN'],
            ['name' => 'Columbia', 'state' => 'TN'],
            ['name' => 'Gallatin', 'state' => 'TN'],
            ['name' => 'Spring Hill', 'state' => 'TN'],
            ['name' => 'Houston', 'state' => 'TX'],
            ['name' => 'San Antonio', 'state' => 'TX'],
            ['name' => 'Dallas', 'state' => 'TX'],
            ['name' => 'Austin', 'state' => 'TX'],
            ['name' => 'Fort Worth', 'state' => 'TX'],
            ['name' => 'El Paso', 'state' => 'TX'],
            ['name' => 'Arlington', 'state' => 'TX'],
            ['name' => 'Corpus Christi', 'state' => 'TX'],
            ['name' => 'Plano', 'state' => 'TX'],
            ['name' => 'Laredo', 'state' => 'TX'],
            ['name' => 'Lubbock', 'state' => 'TX'],
            ['name' => 'Garland', 'state' => 'TX'],
            ['name' => 'Irving', 'state' => 'TX'],
            ['name' => 'Amarillo', 'state' => 'TX'],
            ['name' => 'Grand Prairie', 'state' => 'TX'],
            ['name' => 'Brownsville', 'state' => 'TX'],
            ['name' => 'McKinney', 'state' => 'TX'],
            ['name' => 'Frisco', 'state' => 'TX'],
            ['name' => 'Pasadena', 'state' => 'TX'],
            ['name' => 'Killeen', 'state' => 'TX'],
            ['name' => 'Mesquite', 'state' => 'TX'],
            ['name' => 'McAllen', 'state' => 'TX'],
            ['name' => 'Waco', 'state' => 'TX'],
            ['name' => 'Denton', 'state' => 'TX'],
            ['name' => 'Carrollton', 'state' => 'TX'],
            ['name' => 'Midland', 'state' => 'TX'],
            ['name' => 'Abilene', 'state' => 'TX'],
            ['name' => 'Beaumont', 'state' => 'TX'],
            ['name' => 'Round Rock', 'state' => 'TX'],
            ['name' => 'Odessa', 'state' => 'TX'],
            ['name' => 'The Woodlands', 'state' => 'TX'],
            ['name' => 'Richardson', 'state' => 'TX'],
            ['name' => 'Pearland', 'state' => 'TX'],
            ['name' => 'College Station', 'state' => 'TX'],
            ['name' => 'League City', 'state' => 'TX'],
            ['name' => 'Lewisville', 'state' => 'TX'],
            ['name' => 'Tyler', 'state' => 'TX'],
            ['name' => 'San Angelo', 'state' => 'TX'],
            ['name' => 'Wichita Falls', 'state' => 'TX'],
            ['name' => 'Allen', 'state' => 'TX'],
            ['name' => 'Edinburg', 'state' => 'TX'],
            ['name' => 'Sugar Land', 'state' => 'TX'],
            ['name' => 'Mission', 'state' => 'TX'],
            ['name' => 'Conroe', 'state' => 'TX'],
            ['name' => 'Bryan', 'state' => 'TX'],
            ['name' => 'New Braunfels', 'state' => 'TX'],
            ['name' => 'Pharr', 'state' => 'TX'],
            ['name' => 'Longview', 'state' => 'TX'],
            ['name' => 'Baytown', 'state' => 'TX'],
            ['name' => 'Salt Lake City', 'state' => 'UT'],
            ['name' => 'West Valley City', 'state' => 'UT'],
            ['name' => 'Provo', 'state' => 'UT'],
            ['name' => 'West Jordan', 'state' => 'UT'],
            ['name' => 'Orem', 'state' => 'UT'],
            ['name' => 'Sandy', 'state' => 'UT'],
            ['name' => 'Ogden', 'state' => 'UT'],
            ['name' => 'St. George', 'state' => 'UT'],
            ['name' => 'Layton', 'state' => 'UT'],
            ['name' => 'Taylorsville', 'state' => 'UT'],
            ['name' => 'South Jordan', 'state' => 'UT'],
            ['name' => 'Lehi', 'state' => 'UT'],
            ['name' => 'Logan', 'state' => 'UT'],
            ['name' => 'Murray', 'state' => 'UT'],
            ['name' => 'Draper', 'state' => 'UT'],
            ['name' => 'Bountiful', 'state' => 'UT'],
            ['name' => 'Riverton', 'state' => 'UT'],
            ['name' => 'Herriman', 'state' => 'UT'],
            ['name' => 'Spanish Fork', 'state' => 'UT'],
            ['name' => 'Roy', 'state' => 'UT'],
            ['name' => 'Burlington', 'state' => 'VT'],
            ['name' => 'South Burlington', 'state' => 'VT'],
            ['name' => 'Rutland', 'state' => 'VT'],
            ['name' => 'Barre', 'state' => 'VT'],
            ['name' => 'Montpelier', 'state' => 'VT'],
            ['name' => 'Winooski', 'state' => 'VT'],
            ['name' => 'St. Albans', 'state' => 'VT'],
            ['name' => 'Newport', 'state' => 'VT'],
            ['name' => 'Vergennes', 'state' => 'VT'],
            ['name' => 'Essex Junction', 'state' => 'VT'],
            ['name' => 'Virginia Beach', 'state' => 'VA'],
            ['name' => 'Norfolk', 'state' => 'VA'],
            ['name' => 'Chesapeake', 'state' => 'VA'],
            ['name' => 'Richmond', 'state' => 'VA'],
            ['name' => 'Newport News', 'state' => 'VA'],
            ['name' => 'Alexandria', 'state' => 'VA'],
            ['name' => 'Hampton', 'state' => 'VA'],
            ['name' => 'Roanoke', 'state' => 'VA'],
            ['name' => 'Portsmouth', 'state' => 'VA'],
            ['name' => 'Suffolk', 'state' => 'VA'],
            ['name' => 'Lynchburg', 'state' => 'VA'],
            ['name' => 'Harrisonburg', 'state' => 'VA'],
            ['name' => 'Leesburg', 'state' => 'VA'],
            ['name' => 'Charlottesville', 'state' => 'VA'],
            ['name' => 'Danville', 'state' => 'VA'],
            ['name' => 'Blacksburg', 'state' => 'VA'],
            ['name' => 'Manassas', 'state' => 'VA'],
            ['name' => 'Petersburg', 'state' => 'VA'],
            ['name' => 'Fredericksburg', 'state' => 'VA'],
            ['name' => 'Winchester', 'state' => 'VA'],
            ['name' => 'Seattle', 'state' => 'WA'],
            ['name' => 'Spokane', 'state' => 'WA'],
            ['name' => 'Tacoma', 'state' => 'WA'],
            ['name' => 'Vancouver', 'state' => 'WA'],
            ['name' => 'Bellevue', 'state' => 'WA'],
            ['name' => 'Kent', 'state' => 'WA'],
            ['name' => 'Everett', 'state' => 'WA'],
            ['name' => 'Renton', 'state' => 'WA'],
            ['name' => 'Spokane Valley', 'state' => 'WA'],
            ['name' => 'Federal Way', 'state' => 'WA'],
            ['name' => 'Yakima', 'state' => 'WA'],
            ['name' => 'Bellingham', 'state' => 'WA'],
            ['name' => 'Kennewick', 'state' => 'WA'],
            ['name' => 'Auburn', 'state' => 'WA'],
            ['name' => 'Pasco', 'state' => 'WA'],
            ['name' => 'Marysville', 'state' => 'WA'],
            ['name' => 'Lakewood', 'state' => 'WA'],
            ['name' => 'Redmond', 'state' => 'WA'],
            ['name' => 'Shoreline', 'state' => 'WA'],
            ['name' => 'Richland', 'state' => 'WA'],
            ['name' => 'Kirkland', 'state' => 'WA'],
            ['name' => 'Burien', 'state' => 'WA'],
            ['name' => 'Sammamish', 'state' => 'WA'],
            ['name' => 'Olympia', 'state' => 'WA'],
            ['name' => 'Lacey', 'state' => 'WA'],
            ['name' => 'Edmonds', 'state' => 'WA'],
            ['name' => 'Bremerton', 'state' => 'WA'],
            ['name' => 'Puyallup', 'state' => 'WA'],
            ['name' => 'Lynnwood', 'state' => 'WA'],
            ['name' => 'Bothell', 'state' => 'WA'],
            ['name' => 'Charleston', 'state' => 'WV'],
            ['name' => 'Huntington', 'state' => 'WV'],
            ['name' => 'Morgantown', 'state' => 'WV'],
            ['name' => 'Parkersburg', 'state' => 'WV'],
            ['name' => 'Wheeling', 'state' => 'WV'],
            ['name' => 'Weirton', 'state' => 'WV'],
            ['name' => 'Fairmont', 'state' => 'WV'],
            ['name' => 'Martinsburg', 'state' => 'WV'],
            ['name' => 'Beckley', 'state' => 'WV'],
            ['name' => 'Clarksburg', 'state' => 'WV'],
            ['name' => 'Milwaukee', 'state' => 'WI'],
            ['name' => 'Madison', 'state' => 'WI'],
            ['name' => 'Green Bay', 'state' => 'WI'],
            ['name' => 'Kenosha', 'state' => 'WI'],
            ['name' => 'Racine', 'state' => 'WI'],
            ['name' => 'Appleton', 'state' => 'WI'],
            ['name' => 'Waukesha', 'state' => 'WI'],
            ['name' => 'Eau Claire', 'state' => 'WI'],
            ['name' => 'Oshkosh', 'state' => 'WI'],
            ['name' => 'Janesville', 'state' => 'WI'],
            ['name' => 'West Allis', 'state' => 'WI'],
            ['name' => 'La Crosse', 'state' => 'WI'],
            ['name' => 'Sheboygan', 'state' => 'WI'],
            ['name' => 'Wauwatosa', 'state' => 'WI'],
            ['name' => 'Fond du Lac', 'state' => 'WI'],
            ['name' => 'New Berlin', 'state' => 'WI'],
            ['name' => 'Wausau', 'state' => 'WI'],
            ['name' => 'Brookfield', 'state' => 'WI'],
            ['name' => 'Beloit', 'state' => 'WI'],
            ['name' => 'Greenfield', 'state' => 'WI'],
            ['name' => 'Cheyenne', 'state' => 'WY'],
            ['name' => 'Casper', 'state' => 'WY'],
            ['name' => 'Laramie', 'state' => 'WY'],
            ['name' => 'Gillette', 'state' => 'WY'],
            ['name' => 'Rock Springs', 'state' => 'WY'],
            ['name' => 'Sheridan', 'state' => 'WY'],
            ['name' => 'Green River', 'state' => 'WY'],
            ['name' => 'Evanston', 'state' => 'WY'],
            ['name' => 'Riverton', 'state' => 'WY'],
            ['name' => 'Cody', 'state' => 'WY'],
            ['name' => 'Jackson', 'state' => 'WY'],
            ['name' => 'Rawlins', 'state' => 'WY'],
        ];
    }
}
