<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsCountiesSeeder extends Seeder
{
    public function run()
    {
        $stateIds = DB::table('us_states')->pluck('id', 'abbreviation')->toArray();
        
        $counties = $this->getCountiesData();
        
        $now = now();
        $batch = [];
        
        foreach ($counties as $county) {
            if (!isset($stateIds[$county['state']])) {
                continue;
            }
            
            $batch[] = [
                'name' => $county['name'],
                'fips_code' => $county['fips'] ?? null,
                'state_id' => $stateIds[$county['state']],
                'created_at' => $now,
                'updated_at' => $now,
            ];
            
            if (count($batch) >= 500) {
                DB::table('us_counties')->insertOrIgnore($batch);
                $batch = [];
            }
        }
        
        if (!empty($batch)) {
            DB::table('us_counties')->insertOrIgnore($batch);
        }
    }
    
    private function getCountiesData()
    {
        return [
            ['name' => 'Autauga County', 'state' => 'AL', 'fips' => '01001'],
            ['name' => 'Baldwin County', 'state' => 'AL', 'fips' => '01003'],
            ['name' => 'Barbour County', 'state' => 'AL', 'fips' => '01005'],
            ['name' => 'Bibb County', 'state' => 'AL', 'fips' => '01007'],
            ['name' => 'Blount County', 'state' => 'AL', 'fips' => '01009'],
            ['name' => 'Bullock County', 'state' => 'AL', 'fips' => '01011'],
            ['name' => 'Butler County', 'state' => 'AL', 'fips' => '01013'],
            ['name' => 'Calhoun County', 'state' => 'AL', 'fips' => '01015'],
            ['name' => 'Chambers County', 'state' => 'AL', 'fips' => '01017'],
            ['name' => 'Cherokee County', 'state' => 'AL', 'fips' => '01019'],
            ['name' => 'Chilton County', 'state' => 'AL', 'fips' => '01021'],
            ['name' => 'Choctaw County', 'state' => 'AL', 'fips' => '01023'],
            ['name' => 'Clarke County', 'state' => 'AL', 'fips' => '01025'],
            ['name' => 'Clay County', 'state' => 'AL', 'fips' => '01027'],
            ['name' => 'Cleburne County', 'state' => 'AL', 'fips' => '01029'],
            ['name' => 'Coffee County', 'state' => 'AL', 'fips' => '01031'],
            ['name' => 'Colbert County', 'state' => 'AL', 'fips' => '01033'],
            ['name' => 'Conecuh County', 'state' => 'AL', 'fips' => '01035'],
            ['name' => 'Coosa County', 'state' => 'AL', 'fips' => '01037'],
            ['name' => 'Covington County', 'state' => 'AL', 'fips' => '01039'],
            ['name' => 'Crenshaw County', 'state' => 'AL', 'fips' => '01041'],
            ['name' => 'Cullman County', 'state' => 'AL', 'fips' => '01043'],
            ['name' => 'Dale County', 'state' => 'AL', 'fips' => '01045'],
            ['name' => 'Dallas County', 'state' => 'AL', 'fips' => '01047'],
            ['name' => 'DeKalb County', 'state' => 'AL', 'fips' => '01049'],
            ['name' => 'Elmore County', 'state' => 'AL', 'fips' => '01051'],
            ['name' => 'Escambia County', 'state' => 'AL', 'fips' => '01053'],
            ['name' => 'Etowah County', 'state' => 'AL', 'fips' => '01055'],
            ['name' => 'Fayette County', 'state' => 'AL', 'fips' => '01057'],
            ['name' => 'Franklin County', 'state' => 'AL', 'fips' => '01059'],
            ['name' => 'Geneva County', 'state' => 'AL', 'fips' => '01061'],
            ['name' => 'Greene County', 'state' => 'AL', 'fips' => '01063'],
            ['name' => 'Hale County', 'state' => 'AL', 'fips' => '01065'],
            ['name' => 'Henry County', 'state' => 'AL', 'fips' => '01067'],
            ['name' => 'Houston County', 'state' => 'AL', 'fips' => '01069'],
            ['name' => 'Jackson County', 'state' => 'AL', 'fips' => '01071'],
            ['name' => 'Jefferson County', 'state' => 'AL', 'fips' => '01073'],
            ['name' => 'Lamar County', 'state' => 'AL', 'fips' => '01075'],
            ['name' => 'Lauderdale County', 'state' => 'AL', 'fips' => '01077'],
            ['name' => 'Lawrence County', 'state' => 'AL', 'fips' => '01079'],
            ['name' => 'Lee County', 'state' => 'AL', 'fips' => '01081'],
            ['name' => 'Limestone County', 'state' => 'AL', 'fips' => '01083'],
            ['name' => 'Lowndes County', 'state' => 'AL', 'fips' => '01085'],
            ['name' => 'Macon County', 'state' => 'AL', 'fips' => '01087'],
            ['name' => 'Madison County', 'state' => 'AL', 'fips' => '01089'],
            ['name' => 'Marengo County', 'state' => 'AL', 'fips' => '01091'],
            ['name' => 'Marion County', 'state' => 'AL', 'fips' => '01093'],
            ['name' => 'Marshall County', 'state' => 'AL', 'fips' => '01095'],
            ['name' => 'Mobile County', 'state' => 'AL', 'fips' => '01097'],
            ['name' => 'Monroe County', 'state' => 'AL', 'fips' => '01099'],
            ['name' => 'Montgomery County', 'state' => 'AL', 'fips' => '01101'],
            ['name' => 'Morgan County', 'state' => 'AL', 'fips' => '01103'],
            ['name' => 'Perry County', 'state' => 'AL', 'fips' => '01105'],
            ['name' => 'Pickens County', 'state' => 'AL', 'fips' => '01107'],
            ['name' => 'Pike County', 'state' => 'AL', 'fips' => '01109'],
            ['name' => 'Randolph County', 'state' => 'AL', 'fips' => '01111'],
            ['name' => 'Russell County', 'state' => 'AL', 'fips' => '01113'],
            ['name' => 'St. Clair County', 'state' => 'AL', 'fips' => '01115'],
            ['name' => 'Shelby County', 'state' => 'AL', 'fips' => '01117'],
            ['name' => 'Sumter County', 'state' => 'AL', 'fips' => '01119'],
            ['name' => 'Talladega County', 'state' => 'AL', 'fips' => '01121'],
            ['name' => 'Tallapoosa County', 'state' => 'AL', 'fips' => '01123'],
            ['name' => 'Tuscaloosa County', 'state' => 'AL', 'fips' => '01125'],
            ['name' => 'Walker County', 'state' => 'AL', 'fips' => '01127'],
            ['name' => 'Washington County', 'state' => 'AL', 'fips' => '01129'],
            ['name' => 'Wilcox County', 'state' => 'AL', 'fips' => '01131'],
            ['name' => 'Winston County', 'state' => 'AL', 'fips' => '01133'],
            ['name' => 'Aleutians East Borough', 'state' => 'AK', 'fips' => '02013'],
            ['name' => 'Aleutians West Census Area', 'state' => 'AK', 'fips' => '02016'],
            ['name' => 'Anchorage Municipality', 'state' => 'AK', 'fips' => '02020'],
            ['name' => 'Bethel Census Area', 'state' => 'AK', 'fips' => '02050'],
            ['name' => 'Bristol Bay Borough', 'state' => 'AK', 'fips' => '02060'],
            ['name' => 'Denali Borough', 'state' => 'AK', 'fips' => '02068'],
            ['name' => 'Dillingham Census Area', 'state' => 'AK', 'fips' => '02070'],
            ['name' => 'Fairbanks North Star Borough', 'state' => 'AK', 'fips' => '02090'],
            ['name' => 'Haines Borough', 'state' => 'AK', 'fips' => '02100'],
            ['name' => 'Juneau City and Borough', 'state' => 'AK', 'fips' => '02110'],
            ['name' => 'Kenai Peninsula Borough', 'state' => 'AK', 'fips' => '02122'],
            ['name' => 'Ketchikan Gateway Borough', 'state' => 'AK', 'fips' => '02130'],
            ['name' => 'Kodiak Island Borough', 'state' => 'AK', 'fips' => '02150'],
            ['name' => 'Matanuska-Susitna Borough', 'state' => 'AK', 'fips' => '02170'],
            ['name' => 'Nome Census Area', 'state' => 'AK', 'fips' => '02180'],
            ['name' => 'North Slope Borough', 'state' => 'AK', 'fips' => '02185'],
            ['name' => 'Northwest Arctic Borough', 'state' => 'AK', 'fips' => '02188'],
            ['name' => 'Sitka City and Borough', 'state' => 'AK', 'fips' => '02220'],
            ['name' => 'Skagway Municipality', 'state' => 'AK', 'fips' => '02230'],
            ['name' => 'Southeast Fairbanks Census Area', 'state' => 'AK', 'fips' => '02240'],
            ['name' => 'Valdez-Cordova Census Area', 'state' => 'AK', 'fips' => '02261'],
            ['name' => 'Wade Hampton Census Area', 'state' => 'AK', 'fips' => '02270'],
            ['name' => 'Wrangell City and Borough', 'state' => 'AK', 'fips' => '02275'],
            ['name' => 'Yakutat City and Borough', 'state' => 'AK', 'fips' => '02282'],
            ['name' => 'Yukon-Koyukuk Census Area', 'state' => 'AK', 'fips' => '02290'],
            ['name' => 'Apache County', 'state' => 'AZ', 'fips' => '04001'],
            ['name' => 'Cochise County', 'state' => 'AZ', 'fips' => '04003'],
            ['name' => 'Coconino County', 'state' => 'AZ', 'fips' => '04005'],
            ['name' => 'Gila County', 'state' => 'AZ', 'fips' => '04007'],
            ['name' => 'Graham County', 'state' => 'AZ', 'fips' => '04009'],
            ['name' => 'Greenlee County', 'state' => 'AZ', 'fips' => '04011'],
            ['name' => 'La Paz County', 'state' => 'AZ', 'fips' => '04012'],
            ['name' => 'Maricopa County', 'state' => 'AZ', 'fips' => '04013'],
            ['name' => 'Mohave County', 'state' => 'AZ', 'fips' => '04015'],
            ['name' => 'Navajo County', 'state' => 'AZ', 'fips' => '04017'],
            ['name' => 'Pima County', 'state' => 'AZ', 'fips' => '04019'],
            ['name' => 'Pinal County', 'state' => 'AZ', 'fips' => '04021'],
            ['name' => 'Santa Cruz County', 'state' => 'AZ', 'fips' => '04023'],
            ['name' => 'Yavapai County', 'state' => 'AZ', 'fips' => '04025'],
            ['name' => 'Yuma County', 'state' => 'AZ', 'fips' => '04027'],
            ['name' => 'Arkansas County', 'state' => 'AR', 'fips' => '05001'],
            ['name' => 'Ashley County', 'state' => 'AR', 'fips' => '05003'],
            ['name' => 'Baxter County', 'state' => 'AR', 'fips' => '05005'],
            ['name' => 'Benton County', 'state' => 'AR', 'fips' => '05007'],
            ['name' => 'Boone County', 'state' => 'AR', 'fips' => '05009'],
            ['name' => 'Bradley County', 'state' => 'AR', 'fips' => '05011'],
            ['name' => 'Calhoun County', 'state' => 'AR', 'fips' => '05013'],
            ['name' => 'Carroll County', 'state' => 'AR', 'fips' => '05015'],
            ['name' => 'Chicot County', 'state' => 'AR', 'fips' => '05017'],
            ['name' => 'Clark County', 'state' => 'AR', 'fips' => '05019'],
            ['name' => 'Clay County', 'state' => 'AR', 'fips' => '05021'],
            ['name' => 'Cleburne County', 'state' => 'AR', 'fips' => '05023'],
            ['name' => 'Cleveland County', 'state' => 'AR', 'fips' => '05025'],
            ['name' => 'Columbia County', 'state' => 'AR', 'fips' => '05027'],
            ['name' => 'Conway County', 'state' => 'AR', 'fips' => '05029'],
            ['name' => 'Craighead County', 'state' => 'AR', 'fips' => '05031'],
            ['name' => 'Crawford County', 'state' => 'AR', 'fips' => '05033'],
            ['name' => 'Crittenden County', 'state' => 'AR', 'fips' => '05035'],
            ['name' => 'Cross County', 'state' => 'AR', 'fips' => '05037'],
            ['name' => 'Dallas County', 'state' => 'AR', 'fips' => '05039'],
            ['name' => 'Desha County', 'state' => 'AR', 'fips' => '05041'],
            ['name' => 'Drew County', 'state' => 'AR', 'fips' => '05043'],
            ['name' => 'Faulkner County', 'state' => 'AR', 'fips' => '05045'],
            ['name' => 'Franklin County', 'state' => 'AR', 'fips' => '05047'],
            ['name' => 'Fulton County', 'state' => 'AR', 'fips' => '05049'],
            ['name' => 'Garland County', 'state' => 'AR', 'fips' => '05051'],
            ['name' => 'Grant County', 'state' => 'AR', 'fips' => '05053'],
            ['name' => 'Greene County', 'state' => 'AR', 'fips' => '05055'],
            ['name' => 'Hempstead County', 'state' => 'AR', 'fips' => '05057'],
            ['name' => 'Hot Spring County', 'state' => 'AR', 'fips' => '05059'],
            ['name' => 'Howard County', 'state' => 'AR', 'fips' => '05061'],
            ['name' => 'Independence County', 'state' => 'AR', 'fips' => '05063'],
            ['name' => 'Izard County', 'state' => 'AR', 'fips' => '05065'],
            ['name' => 'Jackson County', 'state' => 'AR', 'fips' => '05067'],
            ['name' => 'Jefferson County', 'state' => 'AR', 'fips' => '05069'],
            ['name' => 'Johnson County', 'state' => 'AR', 'fips' => '05071'],
            ['name' => 'Lafayette County', 'state' => 'AR', 'fips' => '05073'],
            ['name' => 'Lawrence County', 'state' => 'AR', 'fips' => '05075'],
            ['name' => 'Lee County', 'state' => 'AR', 'fips' => '05077'],
            ['name' => 'Lincoln County', 'state' => 'AR', 'fips' => '05079'],
            ['name' => 'Little River County', 'state' => 'AR', 'fips' => '05081'],
            ['name' => 'Logan County', 'state' => 'AR', 'fips' => '05083'],
            ['name' => 'Lonoke County', 'state' => 'AR', 'fips' => '05085'],
            ['name' => 'Madison County', 'state' => 'AR', 'fips' => '05087'],
            ['name' => 'Marion County', 'state' => 'AR', 'fips' => '05089'],
            ['name' => 'Miller County', 'state' => 'AR', 'fips' => '05091'],
            ['name' => 'Mississippi County', 'state' => 'AR', 'fips' => '05093'],
            ['name' => 'Monroe County', 'state' => 'AR', 'fips' => '05095'],
            ['name' => 'Montgomery County', 'state' => 'AR', 'fips' => '05097'],
            ['name' => 'Nevada County', 'state' => 'AR', 'fips' => '05099'],
            ['name' => 'Newton County', 'state' => 'AR', 'fips' => '05101'],
            ['name' => 'Ouachita County', 'state' => 'AR', 'fips' => '05103'],
            ['name' => 'Perry County', 'state' => 'AR', 'fips' => '05105'],
            ['name' => 'Phillips County', 'state' => 'AR', 'fips' => '05107'],
            ['name' => 'Pike County', 'state' => 'AR', 'fips' => '05109'],
            ['name' => 'Poinsett County', 'state' => 'AR', 'fips' => '05111'],
            ['name' => 'Polk County', 'state' => 'AR', 'fips' => '05113'],
            ['name' => 'Pope County', 'state' => 'AR', 'fips' => '05115'],
            ['name' => 'Prairie County', 'state' => 'AR', 'fips' => '05117'],
            ['name' => 'Pulaski County', 'state' => 'AR', 'fips' => '05119'],
            ['name' => 'Randolph County', 'state' => 'AR', 'fips' => '05121'],
            ['name' => 'St. Francis County', 'state' => 'AR', 'fips' => '05123'],
            ['name' => 'Saline County', 'state' => 'AR', 'fips' => '05125'],
            ['name' => 'Scott County', 'state' => 'AR', 'fips' => '05127'],
            ['name' => 'Searcy County', 'state' => 'AR', 'fips' => '05129'],
            ['name' => 'Sebastian County', 'state' => 'AR', 'fips' => '05131'],
            ['name' => 'Sevier County', 'state' => 'AR', 'fips' => '05133'],
            ['name' => 'Sharp County', 'state' => 'AR', 'fips' => '05135'],
            ['name' => 'Stone County', 'state' => 'AR', 'fips' => '05137'],
            ['name' => 'Union County', 'state' => 'AR', 'fips' => '05139'],
            ['name' => 'Van Buren County', 'state' => 'AR', 'fips' => '05141'],
            ['name' => 'Washington County', 'state' => 'AR', 'fips' => '05143'],
            ['name' => 'White County', 'state' => 'AR', 'fips' => '05145'],
            ['name' => 'Woodruff County', 'state' => 'AR', 'fips' => '05147'],
            ['name' => 'Yell County', 'state' => 'AR', 'fips' => '05149'],
            ['name' => 'Alameda County', 'state' => 'CA', 'fips' => '06001'],
            ['name' => 'Alpine County', 'state' => 'CA', 'fips' => '06003'],
            ['name' => 'Amador County', 'state' => 'CA', 'fips' => '06005'],
            ['name' => 'Butte County', 'state' => 'CA', 'fips' => '06007'],
            ['name' => 'Calaveras County', 'state' => 'CA', 'fips' => '06009'],
            ['name' => 'Colusa County', 'state' => 'CA', 'fips' => '06011'],
            ['name' => 'Contra Costa County', 'state' => 'CA', 'fips' => '06013'],
            ['name' => 'Del Norte County', 'state' => 'CA', 'fips' => '06015'],
            ['name' => 'El Dorado County', 'state' => 'CA', 'fips' => '06017'],
            ['name' => 'Fresno County', 'state' => 'CA', 'fips' => '06019'],
            ['name' => 'Glenn County', 'state' => 'CA', 'fips' => '06021'],
            ['name' => 'Humboldt County', 'state' => 'CA', 'fips' => '06023'],
            ['name' => 'Imperial County', 'state' => 'CA', 'fips' => '06025'],
            ['name' => 'Inyo County', 'state' => 'CA', 'fips' => '06027'],
            ['name' => 'Kern County', 'state' => 'CA', 'fips' => '06029'],
            ['name' => 'Kings County', 'state' => 'CA', 'fips' => '06031'],
            ['name' => 'Lake County', 'state' => 'CA', 'fips' => '06033'],
            ['name' => 'Lassen County', 'state' => 'CA', 'fips' => '06035'],
            ['name' => 'Los Angeles County', 'state' => 'CA', 'fips' => '06037'],
            ['name' => 'Madera County', 'state' => 'CA', 'fips' => '06039'],
            ['name' => 'Marin County', 'state' => 'CA', 'fips' => '06041'],
            ['name' => 'Mariposa County', 'state' => 'CA', 'fips' => '06043'],
            ['name' => 'Mendocino County', 'state' => 'CA', 'fips' => '06045'],
            ['name' => 'Merced County', 'state' => 'CA', 'fips' => '06047'],
            ['name' => 'Modoc County', 'state' => 'CA', 'fips' => '06049'],
            ['name' => 'Mono County', 'state' => 'CA', 'fips' => '06051'],
            ['name' => 'Monterey County', 'state' => 'CA', 'fips' => '06053'],
            ['name' => 'Napa County', 'state' => 'CA', 'fips' => '06055'],
            ['name' => 'Nevada County', 'state' => 'CA', 'fips' => '06057'],
            ['name' => 'Orange County', 'state' => 'CA', 'fips' => '06059'],
            ['name' => 'Placer County', 'state' => 'CA', 'fips' => '06061'],
            ['name' => 'Plumas County', 'state' => 'CA', 'fips' => '06063'],
            ['name' => 'Riverside County', 'state' => 'CA', 'fips' => '06065'],
            ['name' => 'Sacramento County', 'state' => 'CA', 'fips' => '06067'],
            ['name' => 'San Benito County', 'state' => 'CA', 'fips' => '06069'],
            ['name' => 'San Bernardino County', 'state' => 'CA', 'fips' => '06071'],
            ['name' => 'San Diego County', 'state' => 'CA', 'fips' => '06073'],
            ['name' => 'San Francisco County', 'state' => 'CA', 'fips' => '06075'],
            ['name' => 'San Joaquin County', 'state' => 'CA', 'fips' => '06077'],
            ['name' => 'San Luis Obispo County', 'state' => 'CA', 'fips' => '06079'],
            ['name' => 'San Mateo County', 'state' => 'CA', 'fips' => '06081'],
            ['name' => 'Santa Barbara County', 'state' => 'CA', 'fips' => '06083'],
            ['name' => 'Santa Clara County', 'state' => 'CA', 'fips' => '06085'],
            ['name' => 'Santa Cruz County', 'state' => 'CA', 'fips' => '06087'],
            ['name' => 'Shasta County', 'state' => 'CA', 'fips' => '06089'],
            ['name' => 'Sierra County', 'state' => 'CA', 'fips' => '06091'],
            ['name' => 'Siskiyou County', 'state' => 'CA', 'fips' => '06093'],
            ['name' => 'Solano County', 'state' => 'CA', 'fips' => '06095'],
            ['name' => 'Sonoma County', 'state' => 'CA', 'fips' => '06097'],
            ['name' => 'Stanislaus County', 'state' => 'CA', 'fips' => '06099'],
            ['name' => 'Sutter County', 'state' => 'CA', 'fips' => '06101'],
            ['name' => 'Tehama County', 'state' => 'CA', 'fips' => '06103'],
            ['name' => 'Trinity County', 'state' => 'CA', 'fips' => '06105'],
            ['name' => 'Tulare County', 'state' => 'CA', 'fips' => '06107'],
            ['name' => 'Tuolumne County', 'state' => 'CA', 'fips' => '06109'],
            ['name' => 'Ventura County', 'state' => 'CA', 'fips' => '06111'],
            ['name' => 'Yolo County', 'state' => 'CA', 'fips' => '06113'],
            ['name' => 'Yuba County', 'state' => 'CA', 'fips' => '06115'],
            ['name' => 'Adams County', 'state' => 'CO', 'fips' => '08001'],
            ['name' => 'Alamosa County', 'state' => 'CO', 'fips' => '08003'],
            ['name' => 'Arapahoe County', 'state' => 'CO', 'fips' => '08005'],
            ['name' => 'Archuleta County', 'state' => 'CO', 'fips' => '08007'],
            ['name' => 'Baca County', 'state' => 'CO', 'fips' => '08009'],
            ['name' => 'Bent County', 'state' => 'CO', 'fips' => '08011'],
            ['name' => 'Boulder County', 'state' => 'CO', 'fips' => '08013'],
            ['name' => 'Broomfield County', 'state' => 'CO', 'fips' => '08014'],
            ['name' => 'Chaffee County', 'state' => 'CO', 'fips' => '08015'],
            ['name' => 'Cheyenne County', 'state' => 'CO', 'fips' => '08017'],
            ['name' => 'Clear Creek County', 'state' => 'CO', 'fips' => '08019'],
            ['name' => 'Conejos County', 'state' => 'CO', 'fips' => '08021'],
            ['name' => 'Costilla County', 'state' => 'CO', 'fips' => '08023'],
            ['name' => 'Crowley County', 'state' => 'CO', 'fips' => '08025'],
            ['name' => 'Custer County', 'state' => 'CO', 'fips' => '08027'],
            ['name' => 'Delta County', 'state' => 'CO', 'fips' => '08029'],
            ['name' => 'Denver County', 'state' => 'CO', 'fips' => '08031'],
            ['name' => 'Dolores County', 'state' => 'CO', 'fips' => '08033'],
            ['name' => 'Douglas County', 'state' => 'CO', 'fips' => '08035'],
            ['name' => 'Eagle County', 'state' => 'CO', 'fips' => '08037'],
            ['name' => 'Elbert County', 'state' => 'CO', 'fips' => '08039'],
            ['name' => 'El Paso County', 'state' => 'CO', 'fips' => '08041'],
            ['name' => 'Fremont County', 'state' => 'CO', 'fips' => '08043'],
            ['name' => 'Garfield County', 'state' => 'CO', 'fips' => '08045'],
            ['name' => 'Gilpin County', 'state' => 'CO', 'fips' => '08047'],
            ['name' => 'Grand County', 'state' => 'CO', 'fips' => '08049'],
            ['name' => 'Gunnison County', 'state' => 'CO', 'fips' => '08051'],
            ['name' => 'Hinsdale County', 'state' => 'CO', 'fips' => '08053'],
            ['name' => 'Huerfano County', 'state' => 'CO', 'fips' => '08055'],
            ['name' => 'Jackson County', 'state' => 'CO', 'fips' => '08057'],
            ['name' => 'Jefferson County', 'state' => 'CO', 'fips' => '08059'],
            ['name' => 'Kiowa County', 'state' => 'CO', 'fips' => '08061'],
            ['name' => 'Kit Carson County', 'state' => 'CO', 'fips' => '08063'],
            ['name' => 'Lake County', 'state' => 'CO', 'fips' => '08065'],
            ['name' => 'La Plata County', 'state' => 'CO', 'fips' => '08067'],
            ['name' => 'Larimer County', 'state' => 'CO', 'fips' => '08069'],
            ['name' => 'Las Animas County', 'state' => 'CO', 'fips' => '08071'],
            ['name' => 'Lincoln County', 'state' => 'CO', 'fips' => '08073'],
            ['name' => 'Logan County', 'state' => 'CO', 'fips' => '08075'],
            ['name' => 'Mesa County', 'state' => 'CO', 'fips' => '08077'],
            ['name' => 'Mineral County', 'state' => 'CO', 'fips' => '08079'],
            ['name' => 'Moffat County', 'state' => 'CO', 'fips' => '08081'],
            ['name' => 'Montezuma County', 'state' => 'CO', 'fips' => '08083'],
            ['name' => 'Montrose County', 'state' => 'CO', 'fips' => '08085'],
            ['name' => 'Morgan County', 'state' => 'CO', 'fips' => '08087'],
            ['name' => 'Otero County', 'state' => 'CO', 'fips' => '08089'],
            ['name' => 'Ouray County', 'state' => 'CO', 'fips' => '08091'],
            ['name' => 'Park County', 'state' => 'CO', 'fips' => '08093'],
            ['name' => 'Phillips County', 'state' => 'CO', 'fips' => '08095'],
            ['name' => 'Pitkin County', 'state' => 'CO', 'fips' => '08097'],
            ['name' => 'Prowers County', 'state' => 'CO', 'fips' => '08099'],
            ['name' => 'Pueblo County', 'state' => 'CO', 'fips' => '08101'],
            ['name' => 'Rio Blanco County', 'state' => 'CO', 'fips' => '08103'],
            ['name' => 'Rio Grande County', 'state' => 'CO', 'fips' => '08105'],
            ['name' => 'Routt County', 'state' => 'CO', 'fips' => '08107'],
            ['name' => 'Saguache County', 'state' => 'CO', 'fips' => '08109'],
            ['name' => 'San Juan County', 'state' => 'CO', 'fips' => '08111'],
            ['name' => 'San Miguel County', 'state' => 'CO', 'fips' => '08113'],
            ['name' => 'Sedgwick County', 'state' => 'CO', 'fips' => '08115'],
            ['name' => 'Summit County', 'state' => 'CO', 'fips' => '08117'],
            ['name' => 'Teller County', 'state' => 'CO', 'fips' => '08119'],
            ['name' => 'Washington County', 'state' => 'CO', 'fips' => '08121'],
            ['name' => 'Weld County', 'state' => 'CO', 'fips' => '08123'],
            ['name' => 'Yuma County', 'state' => 'CO', 'fips' => '08125'],
            ['name' => 'Fairfield County', 'state' => 'CT', 'fips' => '09001'],
            ['name' => 'Hartford County', 'state' => 'CT', 'fips' => '09003'],
            ['name' => 'Litchfield County', 'state' => 'CT', 'fips' => '09005'],
            ['name' => 'Middlesex County', 'state' => 'CT', 'fips' => '09007'],
            ['name' => 'New Haven County', 'state' => 'CT', 'fips' => '09009'],
            ['name' => 'New London County', 'state' => 'CT', 'fips' => '09011'],
            ['name' => 'Tolland County', 'state' => 'CT', 'fips' => '09013'],
            ['name' => 'Windham County', 'state' => 'CT', 'fips' => '09015'],
            ['name' => 'Kent County', 'state' => 'DE', 'fips' => '10001'],
            ['name' => 'New Castle County', 'state' => 'DE', 'fips' => '10003'],
            ['name' => 'Sussex County', 'state' => 'DE', 'fips' => '10005'],
            ['name' => 'District of Columbia', 'state' => 'DC', 'fips' => '11001'],
            ['name' => 'Alachua County', 'state' => 'FL', 'fips' => '12001'],
            ['name' => 'Baker County', 'state' => 'FL', 'fips' => '12003'],
            ['name' => 'Bay County', 'state' => 'FL', 'fips' => '12005'],
            ['name' => 'Bradford County', 'state' => 'FL', 'fips' => '12007'],
            ['name' => 'Brevard County', 'state' => 'FL', 'fips' => '12009'],
            ['name' => 'Broward County', 'state' => 'FL', 'fips' => '12011'],
            ['name' => 'Calhoun County', 'state' => 'FL', 'fips' => '12013'],
            ['name' => 'Charlotte County', 'state' => 'FL', 'fips' => '12015'],
            ['name' => 'Citrus County', 'state' => 'FL', 'fips' => '12017'],
            ['name' => 'Clay County', 'state' => 'FL', 'fips' => '12019'],
            ['name' => 'Collier County', 'state' => 'FL', 'fips' => '12021'],
            ['name' => 'Columbia County', 'state' => 'FL', 'fips' => '12023'],
            ['name' => 'DeSoto County', 'state' => 'FL', 'fips' => '12027'],
            ['name' => 'Dixie County', 'state' => 'FL', 'fips' => '12029'],
            ['name' => 'Duval County', 'state' => 'FL', 'fips' => '12031'],
            ['name' => 'Escambia County', 'state' => 'FL', 'fips' => '12033'],
            ['name' => 'Flagler County', 'state' => 'FL', 'fips' => '12035'],
            ['name' => 'Franklin County', 'state' => 'FL', 'fips' => '12037'],
            ['name' => 'Gadsden County', 'state' => 'FL', 'fips' => '12039'],
            ['name' => 'Gilchrist County', 'state' => 'FL', 'fips' => '12041'],
            ['name' => 'Glades County', 'state' => 'FL', 'fips' => '12043'],
            ['name' => 'Gulf County', 'state' => 'FL', 'fips' => '12045'],
            ['name' => 'Hamilton County', 'state' => 'FL', 'fips' => '12047'],
            ['name' => 'Hardee County', 'state' => 'FL', 'fips' => '12049'],
            ['name' => 'Hendry County', 'state' => 'FL', 'fips' => '12051'],
            ['name' => 'Hernando County', 'state' => 'FL', 'fips' => '12053'],
            ['name' => 'Highlands County', 'state' => 'FL', 'fips' => '12055'],
            ['name' => 'Hillsborough County', 'state' => 'FL', 'fips' => '12057'],
            ['name' => 'Holmes County', 'state' => 'FL', 'fips' => '12059'],
            ['name' => 'Indian River County', 'state' => 'FL', 'fips' => '12061'],
            ['name' => 'Jackson County', 'state' => 'FL', 'fips' => '12063'],
            ['name' => 'Jefferson County', 'state' => 'FL', 'fips' => '12065'],
            ['name' => 'Lafayette County', 'state' => 'FL', 'fips' => '12067'],
            ['name' => 'Lake County', 'state' => 'FL', 'fips' => '12069'],
            ['name' => 'Lee County', 'state' => 'FL', 'fips' => '12071'],
            ['name' => 'Leon County', 'state' => 'FL', 'fips' => '12073'],
            ['name' => 'Levy County', 'state' => 'FL', 'fips' => '12075'],
            ['name' => 'Liberty County', 'state' => 'FL', 'fips' => '12077'],
            ['name' => 'Madison County', 'state' => 'FL', 'fips' => '12079'],
            ['name' => 'Manatee County', 'state' => 'FL', 'fips' => '12081'],
            ['name' => 'Marion County', 'state' => 'FL', 'fips' => '12083'],
            ['name' => 'Martin County', 'state' => 'FL', 'fips' => '12085'],
            ['name' => 'Miami-Dade County', 'state' => 'FL', 'fips' => '12086'],
            ['name' => 'Monroe County', 'state' => 'FL', 'fips' => '12087'],
            ['name' => 'Nassau County', 'state' => 'FL', 'fips' => '12089'],
            ['name' => 'Okaloosa County', 'state' => 'FL', 'fips' => '12091'],
            ['name' => 'Okeechobee County', 'state' => 'FL', 'fips' => '12093'],
            ['name' => 'Orange County', 'state' => 'FL', 'fips' => '12095'],
            ['name' => 'Osceola County', 'state' => 'FL', 'fips' => '12097'],
            ['name' => 'Palm Beach County', 'state' => 'FL', 'fips' => '12099'],
            ['name' => 'Pasco County', 'state' => 'FL', 'fips' => '12101'],
            ['name' => 'Pinellas County', 'state' => 'FL', 'fips' => '12103'],
            ['name' => 'Polk County', 'state' => 'FL', 'fips' => '12105'],
            ['name' => 'Putnam County', 'state' => 'FL', 'fips' => '12107'],
            ['name' => 'St. Johns County', 'state' => 'FL', 'fips' => '12109'],
            ['name' => 'St. Lucie County', 'state' => 'FL', 'fips' => '12111'],
            ['name' => 'Santa Rosa County', 'state' => 'FL', 'fips' => '12113'],
            ['name' => 'Sarasota County', 'state' => 'FL', 'fips' => '12115'],
            ['name' => 'Seminole County', 'state' => 'FL', 'fips' => '12117'],
            ['name' => 'Sumter County', 'state' => 'FL', 'fips' => '12119'],
            ['name' => 'Suwannee County', 'state' => 'FL', 'fips' => '12121'],
            ['name' => 'Taylor County', 'state' => 'FL', 'fips' => '12123'],
            ['name' => 'Union County', 'state' => 'FL', 'fips' => '12125'],
            ['name' => 'Volusia County', 'state' => 'FL', 'fips' => '12127'],
            ['name' => 'Wakulla County', 'state' => 'FL', 'fips' => '12129'],
            ['name' => 'Walton County', 'state' => 'FL', 'fips' => '12131'],
            ['name' => 'Washington County', 'state' => 'FL', 'fips' => '12133'],
            ['name' => 'Appling County', 'state' => 'GA', 'fips' => '13001'],
            ['name' => 'Atkinson County', 'state' => 'GA', 'fips' => '13003'],
            ['name' => 'Bacon County', 'state' => 'GA', 'fips' => '13005'],
            ['name' => 'Baker County', 'state' => 'GA', 'fips' => '13007'],
            ['name' => 'Baldwin County', 'state' => 'GA', 'fips' => '13009'],
            ['name' => 'Banks County', 'state' => 'GA', 'fips' => '13011'],
            ['name' => 'Barrow County', 'state' => 'GA', 'fips' => '13013'],
            ['name' => 'Bartow County', 'state' => 'GA', 'fips' => '13015'],
            ['name' => 'Ben Hill County', 'state' => 'GA', 'fips' => '13017'],
            ['name' => 'Berrien County', 'state' => 'GA', 'fips' => '13019'],
            ['name' => 'Bibb County', 'state' => 'GA', 'fips' => '13021'],
            ['name' => 'Bleckley County', 'state' => 'GA', 'fips' => '13023'],
            ['name' => 'Brantley County', 'state' => 'GA', 'fips' => '13025'],
            ['name' => 'Brooks County', 'state' => 'GA', 'fips' => '13027'],
            ['name' => 'Bryan County', 'state' => 'GA', 'fips' => '13029'],
            ['name' => 'Bulloch County', 'state' => 'GA', 'fips' => '13031'],
            ['name' => 'Burke County', 'state' => 'GA', 'fips' => '13033'],
            ['name' => 'Butts County', 'state' => 'GA', 'fips' => '13035'],
            ['name' => 'Calhoun County', 'state' => 'GA', 'fips' => '13037'],
            ['name' => 'Camden County', 'state' => 'GA', 'fips' => '13039'],
            ['name' => 'Candler County', 'state' => 'GA', 'fips' => '13043'],
            ['name' => 'Carroll County', 'state' => 'GA', 'fips' => '13045'],
            ['name' => 'Catoosa County', 'state' => 'GA', 'fips' => '13047'],
            ['name' => 'Charlton County', 'state' => 'GA', 'fips' => '13049'],
            ['name' => 'Chatham County', 'state' => 'GA', 'fips' => '13051'],
            ['name' => 'Chattahoochee County', 'state' => 'GA', 'fips' => '13053'],
            ['name' => 'Chattooga County', 'state' => 'GA', 'fips' => '13055'],
            ['name' => 'Cherokee County', 'state' => 'GA', 'fips' => '13057'],
            ['name' => 'Clarke County', 'state' => 'GA', 'fips' => '13059'],
            ['name' => 'Clay County', 'state' => 'GA', 'fips' => '13061'],
            ['name' => 'Clayton County', 'state' => 'GA', 'fips' => '13063'],
            ['name' => 'Clinch County', 'state' => 'GA', 'fips' => '13065'],
            ['name' => 'Cobb County', 'state' => 'GA', 'fips' => '13067'],
            ['name' => 'Coffee County', 'state' => 'GA', 'fips' => '13069'],
            ['name' => 'Colquitt County', 'state' => 'GA', 'fips' => '13071'],
            ['name' => 'Columbia County', 'state' => 'GA', 'fips' => '13073'],
            ['name' => 'Cook County', 'state' => 'GA', 'fips' => '13075'],
            ['name' => 'Coweta County', 'state' => 'GA', 'fips' => '13077'],
            ['name' => 'Crawford County', 'state' => 'GA', 'fips' => '13079'],
            ['name' => 'Crisp County', 'state' => 'GA', 'fips' => '13081'],
            ['name' => 'Dade County', 'state' => 'GA', 'fips' => '13083'],
            ['name' => 'Dawson County', 'state' => 'GA', 'fips' => '13085'],
            ['name' => 'Decatur County', 'state' => 'GA', 'fips' => '13087'],
            ['name' => 'DeKalb County', 'state' => 'GA', 'fips' => '13089'],
            ['name' => 'Dodge County', 'state' => 'GA', 'fips' => '13091'],
            ['name' => 'Dooly County', 'state' => 'GA', 'fips' => '13093'],
            ['name' => 'Dougherty County', 'state' => 'GA', 'fips' => '13095'],
            ['name' => 'Douglas County', 'state' => 'GA', 'fips' => '13097'],
            ['name' => 'Early County', 'state' => 'GA', 'fips' => '13099'],
            ['name' => 'Echols County', 'state' => 'GA', 'fips' => '13101'],
            ['name' => 'Effingham County', 'state' => 'GA', 'fips' => '13103'],
            ['name' => 'Elbert County', 'state' => 'GA', 'fips' => '13105'],
            ['name' => 'Emanuel County', 'state' => 'GA', 'fips' => '13107'],
            ['name' => 'Evans County', 'state' => 'GA', 'fips' => '13109'],
            ['name' => 'Fannin County', 'state' => 'GA', 'fips' => '13111'],
            ['name' => 'Fayette County', 'state' => 'GA', 'fips' => '13113'],
            ['name' => 'Floyd County', 'state' => 'GA', 'fips' => '13115'],
            ['name' => 'Forsyth County', 'state' => 'GA', 'fips' => '13117'],
            ['name' => 'Franklin County', 'state' => 'GA', 'fips' => '13119'],
            ['name' => 'Fulton County', 'state' => 'GA', 'fips' => '13121'],
            ['name' => 'Gilmer County', 'state' => 'GA', 'fips' => '13123'],
            ['name' => 'Glascock County', 'state' => 'GA', 'fips' => '13125'],
            ['name' => 'Glynn County', 'state' => 'GA', 'fips' => '13127'],
            ['name' => 'Gordon County', 'state' => 'GA', 'fips' => '13129'],
            ['name' => 'Grady County', 'state' => 'GA', 'fips' => '13131'],
            ['name' => 'Greene County', 'state' => 'GA', 'fips' => '13133'],
            ['name' => 'Gwinnett County', 'state' => 'GA', 'fips' => '13135'],
            ['name' => 'Habersham County', 'state' => 'GA', 'fips' => '13137'],
            ['name' => 'Hall County', 'state' => 'GA', 'fips' => '13139'],
            ['name' => 'Hancock County', 'state' => 'GA', 'fips' => '13141'],
            ['name' => 'Haralson County', 'state' => 'GA', 'fips' => '13143'],
            ['name' => 'Harris County', 'state' => 'GA', 'fips' => '13145'],
            ['name' => 'Hart County', 'state' => 'GA', 'fips' => '13147'],
            ['name' => 'Heard County', 'state' => 'GA', 'fips' => '13149'],
            ['name' => 'Henry County', 'state' => 'GA', 'fips' => '13151'],
            ['name' => 'Houston County', 'state' => 'GA', 'fips' => '13153'],
            ['name' => 'Irwin County', 'state' => 'GA', 'fips' => '13155'],
            ['name' => 'Jackson County', 'state' => 'GA', 'fips' => '13157'],
            ['name' => 'Jasper County', 'state' => 'GA', 'fips' => '13159'],
            ['name' => 'Jeff Davis County', 'state' => 'GA', 'fips' => '13161'],
            ['name' => 'Jefferson County', 'state' => 'GA', 'fips' => '13163'],
            ['name' => 'Jenkins County', 'state' => 'GA', 'fips' => '13165'],
            ['name' => 'Johnson County', 'state' => 'GA', 'fips' => '13167'],
            ['name' => 'Jones County', 'state' => 'GA', 'fips' => '13169'],
            ['name' => 'Lamar County', 'state' => 'GA', 'fips' => '13171'],
            ['name' => 'Lanier County', 'state' => 'GA', 'fips' => '13173'],
            ['name' => 'Laurens County', 'state' => 'GA', 'fips' => '13175'],
            ['name' => 'Lee County', 'state' => 'GA', 'fips' => '13177'],
            ['name' => 'Liberty County', 'state' => 'GA', 'fips' => '13179'],
            ['name' => 'Lincoln County', 'state' => 'GA', 'fips' => '13181'],
            ['name' => 'Long County', 'state' => 'GA', 'fips' => '13183'],
            ['name' => 'Lowndes County', 'state' => 'GA', 'fips' => '13185'],
            ['name' => 'Lumpkin County', 'state' => 'GA', 'fips' => '13187'],
            ['name' => 'McDuffie County', 'state' => 'GA', 'fips' => '13189'],
            ['name' => 'McIntosh County', 'state' => 'GA', 'fips' => '13191'],
            ['name' => 'Macon County', 'state' => 'GA', 'fips' => '13193'],
            ['name' => 'Madison County', 'state' => 'GA', 'fips' => '13195'],
            ['name' => 'Marion County', 'state' => 'GA', 'fips' => '13197'],
            ['name' => 'Meriwether County', 'state' => 'GA', 'fips' => '13199'],
            ['name' => 'Miller County', 'state' => 'GA', 'fips' => '13201'],
            ['name' => 'Mitchell County', 'state' => 'GA', 'fips' => '13205'],
            ['name' => 'Monroe County', 'state' => 'GA', 'fips' => '13207'],
            ['name' => 'Montgomery County', 'state' => 'GA', 'fips' => '13209'],
            ['name' => 'Morgan County', 'state' => 'GA', 'fips' => '13211'],
            ['name' => 'Murray County', 'state' => 'GA', 'fips' => '13213'],
            ['name' => 'Muscogee County', 'state' => 'GA', 'fips' => '13215'],
            ['name' => 'Newton County', 'state' => 'GA', 'fips' => '13217'],
            ['name' => 'Oconee County', 'state' => 'GA', 'fips' => '13219'],
            ['name' => 'Oglethorpe County', 'state' => 'GA', 'fips' => '13221'],
            ['name' => 'Paulding County', 'state' => 'GA', 'fips' => '13223'],
            ['name' => 'Peach County', 'state' => 'GA', 'fips' => '13225'],
            ['name' => 'Pickens County', 'state' => 'GA', 'fips' => '13227'],
            ['name' => 'Pierce County', 'state' => 'GA', 'fips' => '13229'],
            ['name' => 'Pike County', 'state' => 'GA', 'fips' => '13231'],
            ['name' => 'Polk County', 'state' => 'GA', 'fips' => '13233'],
            ['name' => 'Pulaski County', 'state' => 'GA', 'fips' => '13235'],
            ['name' => 'Putnam County', 'state' => 'GA', 'fips' => '13237'],
            ['name' => 'Quitman County', 'state' => 'GA', 'fips' => '13239'],
            ['name' => 'Rabun County', 'state' => 'GA', 'fips' => '13241'],
            ['name' => 'Randolph County', 'state' => 'GA', 'fips' => '13243'],
            ['name' => 'Richmond County', 'state' => 'GA', 'fips' => '13245'],
            ['name' => 'Rockdale County', 'state' => 'GA', 'fips' => '13247'],
            ['name' => 'Schley County', 'state' => 'GA', 'fips' => '13249'],
            ['name' => 'Screven County', 'state' => 'GA', 'fips' => '13251'],
            ['name' => 'Seminole County', 'state' => 'GA', 'fips' => '13253'],
            ['name' => 'Spalding County', 'state' => 'GA', 'fips' => '13255'],
            ['name' => 'Stephens County', 'state' => 'GA', 'fips' => '13257'],
            ['name' => 'Stewart County', 'state' => 'GA', 'fips' => '13259'],
            ['name' => 'Sumter County', 'state' => 'GA', 'fips' => '13261'],
            ['name' => 'Talbot County', 'state' => 'GA', 'fips' => '13263'],
            ['name' => 'Taliaferro County', 'state' => 'GA', 'fips' => '13265'],
            ['name' => 'Tattnall County', 'state' => 'GA', 'fips' => '13267'],
            ['name' => 'Taylor County', 'state' => 'GA', 'fips' => '13269'],
            ['name' => 'Telfair County', 'state' => 'GA', 'fips' => '13271'],
            ['name' => 'Terrell County', 'state' => 'GA', 'fips' => '13273'],
            ['name' => 'Thomas County', 'state' => 'GA', 'fips' => '13275'],
            ['name' => 'Tift County', 'state' => 'GA', 'fips' => '13277'],
            ['name' => 'Toombs County', 'state' => 'GA', 'fips' => '13279'],
            ['name' => 'Towns County', 'state' => 'GA', 'fips' => '13281'],
            ['name' => 'Treutlen County', 'state' => 'GA', 'fips' => '13283'],
            ['name' => 'Troup County', 'state' => 'GA', 'fips' => '13285'],
            ['name' => 'Turner County', 'state' => 'GA', 'fips' => '13287'],
            ['name' => 'Twiggs County', 'state' => 'GA', 'fips' => '13289'],
            ['name' => 'Union County', 'state' => 'GA', 'fips' => '13291'],
            ['name' => 'Upson County', 'state' => 'GA', 'fips' => '13293'],
            ['name' => 'Walker County', 'state' => 'GA', 'fips' => '13295'],
            ['name' => 'Walton County', 'state' => 'GA', 'fips' => '13297'],
            ['name' => 'Ware County', 'state' => 'GA', 'fips' => '13299'],
            ['name' => 'Warren County', 'state' => 'GA', 'fips' => '13301'],
            ['name' => 'Washington County', 'state' => 'GA', 'fips' => '13303'],
            ['name' => 'Wayne County', 'state' => 'GA', 'fips' => '13305'],
            ['name' => 'Webster County', 'state' => 'GA', 'fips' => '13307'],
            ['name' => 'Wheeler County', 'state' => 'GA', 'fips' => '13309'],
            ['name' => 'White County', 'state' => 'GA', 'fips' => '13311'],
            ['name' => 'Whitfield County', 'state' => 'GA', 'fips' => '13313'],
            ['name' => 'Wilcox County', 'state' => 'GA', 'fips' => '13315'],
            ['name' => 'Wilkes County', 'state' => 'GA', 'fips' => '13317'],
            ['name' => 'Wilkinson County', 'state' => 'GA', 'fips' => '13319'],
            ['name' => 'Worth County', 'state' => 'GA', 'fips' => '13321'],
            ['name' => 'Hawaii County', 'state' => 'HI', 'fips' => '15001'],
            ['name' => 'Honolulu County', 'state' => 'HI', 'fips' => '15003'],
            ['name' => 'Kalawao County', 'state' => 'HI', 'fips' => '15005'],
            ['name' => 'Kauai County', 'state' => 'HI', 'fips' => '15007'],
            ['name' => 'Maui County', 'state' => 'HI', 'fips' => '15009'],
            ['name' => 'Ada County', 'state' => 'ID', 'fips' => '16001'],
            ['name' => 'Adams County', 'state' => 'ID', 'fips' => '16003'],
            ['name' => 'Bannock County', 'state' => 'ID', 'fips' => '16005'],
            ['name' => 'Bear Lake County', 'state' => 'ID', 'fips' => '16007'],
            ['name' => 'Benewah County', 'state' => 'ID', 'fips' => '16009'],
            ['name' => 'Bingham County', 'state' => 'ID', 'fips' => '16011'],
            ['name' => 'Blaine County', 'state' => 'ID', 'fips' => '16013'],
            ['name' => 'Boise County', 'state' => 'ID', 'fips' => '16015'],
            ['name' => 'Bonner County', 'state' => 'ID', 'fips' => '16017'],
            ['name' => 'Bonneville County', 'state' => 'ID', 'fips' => '16019'],
            ['name' => 'Boundary County', 'state' => 'ID', 'fips' => '16021'],
            ['name' => 'Butte County', 'state' => 'ID', 'fips' => '16023'],
            ['name' => 'Camas County', 'state' => 'ID', 'fips' => '16025'],
            ['name' => 'Canyon County', 'state' => 'ID', 'fips' => '16027'],
            ['name' => 'Caribou County', 'state' => 'ID', 'fips' => '16029'],
            ['name' => 'Cassia County', 'state' => 'ID', 'fips' => '16031'],
            ['name' => 'Clark County', 'state' => 'ID', 'fips' => '16033'],
            ['name' => 'Clearwater County', 'state' => 'ID', 'fips' => '16035'],
            ['name' => 'Custer County', 'state' => 'ID', 'fips' => '16037'],
            ['name' => 'Elmore County', 'state' => 'ID', 'fips' => '16039'],
            ['name' => 'Franklin County', 'state' => 'ID', 'fips' => '16041'],
            ['name' => 'Fremont County', 'state' => 'ID', 'fips' => '16043'],
            ['name' => 'Gem County', 'state' => 'ID', 'fips' => '16045'],
            ['name' => 'Gooding County', 'state' => 'ID', 'fips' => '16047'],
            ['name' => 'Idaho County', 'state' => 'ID', 'fips' => '16049'],
            ['name' => 'Jefferson County', 'state' => 'ID', 'fips' => '16051'],
            ['name' => 'Jerome County', 'state' => 'ID', 'fips' => '16053'],
            ['name' => 'Kootenai County', 'state' => 'ID', 'fips' => '16055'],
            ['name' => 'Latah County', 'state' => 'ID', 'fips' => '16057'],
            ['name' => 'Lemhi County', 'state' => 'ID', 'fips' => '16059'],
            ['name' => 'Lewis County', 'state' => 'ID', 'fips' => '16061'],
            ['name' => 'Lincoln County', 'state' => 'ID', 'fips' => '16063'],
            ['name' => 'Madison County', 'state' => 'ID', 'fips' => '16065'],
            ['name' => 'Minidoka County', 'state' => 'ID', 'fips' => '16067'],
            ['name' => 'Nez Perce County', 'state' => 'ID', 'fips' => '16069'],
            ['name' => 'Oneida County', 'state' => 'ID', 'fips' => '16071'],
            ['name' => 'Owyhee County', 'state' => 'ID', 'fips' => '16073'],
            ['name' => 'Payette County', 'state' => 'ID', 'fips' => '16075'],
            ['name' => 'Power County', 'state' => 'ID', 'fips' => '16077'],
            ['name' => 'Shoshone County', 'state' => 'ID', 'fips' => '16079'],
            ['name' => 'Teton County', 'state' => 'ID', 'fips' => '16081'],
            ['name' => 'Twin Falls County', 'state' => 'ID', 'fips' => '16083'],
            ['name' => 'Valley County', 'state' => 'ID', 'fips' => '16085'],
            ['name' => 'Washington County', 'state' => 'ID', 'fips' => '16087'],
            ['name' => 'Cook County', 'state' => 'IL', 'fips' => '17031'],
            ['name' => 'DuPage County', 'state' => 'IL', 'fips' => '17043'],
            ['name' => 'Lake County', 'state' => 'IL', 'fips' => '17097'],
            ['name' => 'Will County', 'state' => 'IL', 'fips' => '17197'],
            ['name' => 'Kane County', 'state' => 'IL', 'fips' => '17089'],
            ['name' => 'McHenry County', 'state' => 'IL', 'fips' => '17111'],
            ['name' => 'Winnebago County', 'state' => 'IL', 'fips' => '17201'],
            ['name' => 'Madison County', 'state' => 'IL', 'fips' => '17119'],
            ['name' => 'St. Clair County', 'state' => 'IL', 'fips' => '17163'],
            ['name' => 'Champaign County', 'state' => 'IL', 'fips' => '17019'],
            ['name' => 'Sangamon County', 'state' => 'IL', 'fips' => '17167'],
            ['name' => 'Peoria County', 'state' => 'IL', 'fips' => '17143'],
            ['name' => 'Marion County', 'state' => 'IN', 'fips' => '18097'],
            ['name' => 'Lake County', 'state' => 'IN', 'fips' => '18089'],
            ['name' => 'Allen County', 'state' => 'IN', 'fips' => '18003'],
            ['name' => 'Hamilton County', 'state' => 'IN', 'fips' => '18057'],
            ['name' => 'St. Joseph County', 'state' => 'IN', 'fips' => '18141'],
            ['name' => 'Tippecanoe County', 'state' => 'IN', 'fips' => '18157'],
            ['name' => 'Vanderburgh County', 'state' => 'IN', 'fips' => '18163'],
            ['name' => 'Polk County', 'state' => 'IA', 'fips' => '19153'],
            ['name' => 'Linn County', 'state' => 'IA', 'fips' => '19113'],
            ['name' => 'Scott County', 'state' => 'IA', 'fips' => '19163'],
            ['name' => 'Johnson County', 'state' => 'IA', 'fips' => '19103'],
            ['name' => 'Black Hawk County', 'state' => 'IA', 'fips' => '19013'],
            ['name' => 'Woodbury County', 'state' => 'IA', 'fips' => '19193'],
            ['name' => 'Story County', 'state' => 'IA', 'fips' => '19169'],
            ['name' => 'Johnson County', 'state' => 'KS', 'fips' => '20091'],
            ['name' => 'Sedgwick County', 'state' => 'KS', 'fips' => '20173'],
            ['name' => 'Shawnee County', 'state' => 'KS', 'fips' => '20177'],
            ['name' => 'Wyandotte County', 'state' => 'KS', 'fips' => '20209'],
            ['name' => 'Douglas County', 'state' => 'KS', 'fips' => '20045'],
            ['name' => 'Jefferson County', 'state' => 'KY', 'fips' => '21111'],
            ['name' => 'Fayette County', 'state' => 'KY', 'fips' => '21067'],
            ['name' => 'Kenton County', 'state' => 'KY', 'fips' => '21117'],
            ['name' => 'Boone County', 'state' => 'KY', 'fips' => '21015'],
            ['name' => 'Warren County', 'state' => 'KY', 'fips' => '21227'],
            ['name' => 'Orleans Parish', 'state' => 'LA', 'fips' => '22071'],
            ['name' => 'Jefferson Parish', 'state' => 'LA', 'fips' => '22051'],
            ['name' => 'East Baton Rouge Parish', 'state' => 'LA', 'fips' => '22033'],
            ['name' => 'Caddo Parish', 'state' => 'LA', 'fips' => '22017'],
            ['name' => 'St. Tammany Parish', 'state' => 'LA', 'fips' => '22103'],
            ['name' => 'Lafayette Parish', 'state' => 'LA', 'fips' => '22055'],
            ['name' => 'Calcasieu Parish', 'state' => 'LA', 'fips' => '22019'],
            ['name' => 'Cumberland County', 'state' => 'ME', 'fips' => '23005'],
            ['name' => 'York County', 'state' => 'ME', 'fips' => '23031'],
            ['name' => 'Penobscot County', 'state' => 'ME', 'fips' => '23019'],
            ['name' => 'Kennebec County', 'state' => 'ME', 'fips' => '23011'],
            ['name' => 'Androscoggin County', 'state' => 'ME', 'fips' => '23001'],
            ['name' => 'Montgomery County', 'state' => 'MD', 'fips' => '24031'],
            ['name' => 'Prince Georges County', 'state' => 'MD', 'fips' => '24033'],
            ['name' => 'Baltimore County', 'state' => 'MD', 'fips' => '24005'],
            ['name' => 'Anne Arundel County', 'state' => 'MD', 'fips' => '24003'],
            ['name' => 'Howard County', 'state' => 'MD', 'fips' => '24027'],
            ['name' => 'Baltimore City', 'state' => 'MD', 'fips' => '24510'],
            ['name' => 'Frederick County', 'state' => 'MD', 'fips' => '24021'],
            ['name' => 'Harford County', 'state' => 'MD', 'fips' => '24025'],
            ['name' => 'Middlesex County', 'state' => 'MA', 'fips' => '25017'],
            ['name' => 'Worcester County', 'state' => 'MA', 'fips' => '25027'],
            ['name' => 'Suffolk County', 'state' => 'MA', 'fips' => '25025'],
            ['name' => 'Essex County', 'state' => 'MA', 'fips' => '25009'],
            ['name' => 'Norfolk County', 'state' => 'MA', 'fips' => '25021'],
            ['name' => 'Bristol County', 'state' => 'MA', 'fips' => '25005'],
            ['name' => 'Plymouth County', 'state' => 'MA', 'fips' => '25023'],
            ['name' => 'Hampden County', 'state' => 'MA', 'fips' => '25013'],
            ['name' => 'Wayne County', 'state' => 'MI', 'fips' => '26163'],
            ['name' => 'Oakland County', 'state' => 'MI', 'fips' => '26125'],
            ['name' => 'Macomb County', 'state' => 'MI', 'fips' => '26099'],
            ['name' => 'Kent County', 'state' => 'MI', 'fips' => '26081'],
            ['name' => 'Genesee County', 'state' => 'MI', 'fips' => '26049'],
            ['name' => 'Washtenaw County', 'state' => 'MI', 'fips' => '26161'],
            ['name' => 'Ingham County', 'state' => 'MI', 'fips' => '26065'],
            ['name' => 'Ottawa County', 'state' => 'MI', 'fips' => '26139'],
            ['name' => 'Kalamazoo County', 'state' => 'MI', 'fips' => '26077'],
            ['name' => 'Hennepin County', 'state' => 'MN', 'fips' => '27053'],
            ['name' => 'Ramsey County', 'state' => 'MN', 'fips' => '27123'],
            ['name' => 'Dakota County', 'state' => 'MN', 'fips' => '27037'],
            ['name' => 'Anoka County', 'state' => 'MN', 'fips' => '27003'],
            ['name' => 'Washington County', 'state' => 'MN', 'fips' => '27163'],
            ['name' => 'St. Louis County', 'state' => 'MN', 'fips' => '27137'],
            ['name' => 'Olmsted County', 'state' => 'MN', 'fips' => '27109'],
            ['name' => 'Hinds County', 'state' => 'MS', 'fips' => '28049'],
            ['name' => 'Harrison County', 'state' => 'MS', 'fips' => '28047'],
            ['name' => 'DeSoto County', 'state' => 'MS', 'fips' => '28033'],
            ['name' => 'Rankin County', 'state' => 'MS', 'fips' => '28121'],
            ['name' => 'Jackson County', 'state' => 'MS', 'fips' => '28059'],
            ['name' => 'St. Louis County', 'state' => 'MO', 'fips' => '29189'],
            ['name' => 'Jackson County', 'state' => 'MO', 'fips' => '29095'],
            ['name' => 'St. Charles County', 'state' => 'MO', 'fips' => '29183'],
            ['name' => 'St. Louis City', 'state' => 'MO', 'fips' => '29510'],
            ['name' => 'Greene County', 'state' => 'MO', 'fips' => '29077'],
            ['name' => 'Clay County', 'state' => 'MO', 'fips' => '29047'],
            ['name' => 'Boone County', 'state' => 'MO', 'fips' => '29019'],
            ['name' => 'Yellowstone County', 'state' => 'MT', 'fips' => '30111'],
            ['name' => 'Missoula County', 'state' => 'MT', 'fips' => '30063'],
            ['name' => 'Gallatin County', 'state' => 'MT', 'fips' => '30031'],
            ['name' => 'Flathead County', 'state' => 'MT', 'fips' => '30029'],
            ['name' => 'Cascade County', 'state' => 'MT', 'fips' => '30013'],
            ['name' => 'Lewis and Clark County', 'state' => 'MT', 'fips' => '30049'],
            ['name' => 'Douglas County', 'state' => 'NE', 'fips' => '31055'],
            ['name' => 'Lancaster County', 'state' => 'NE', 'fips' => '31109'],
            ['name' => 'Sarpy County', 'state' => 'NE', 'fips' => '31153'],
            ['name' => 'Hall County', 'state' => 'NE', 'fips' => '31079'],
            ['name' => 'Buffalo County', 'state' => 'NE', 'fips' => '31019'],
            ['name' => 'Clark County', 'state' => 'NV', 'fips' => '32003'],
            ['name' => 'Washoe County', 'state' => 'NV', 'fips' => '32031'],
            ['name' => 'Carson City', 'state' => 'NV', 'fips' => '32510'],
            ['name' => 'Lyon County', 'state' => 'NV', 'fips' => '32019'],
            ['name' => 'Elko County', 'state' => 'NV', 'fips' => '32007'],
            ['name' => 'Hillsborough County', 'state' => 'NH', 'fips' => '33011'],
            ['name' => 'Rockingham County', 'state' => 'NH', 'fips' => '33015'],
            ['name' => 'Merrimack County', 'state' => 'NH', 'fips' => '33013'],
            ['name' => 'Strafford County', 'state' => 'NH', 'fips' => '33017'],
            ['name' => 'Grafton County', 'state' => 'NH', 'fips' => '33009'],
            ['name' => 'Bergen County', 'state' => 'NJ', 'fips' => '34003'],
            ['name' => 'Middlesex County', 'state' => 'NJ', 'fips' => '34023'],
            ['name' => 'Essex County', 'state' => 'NJ', 'fips' => '34013'],
            ['name' => 'Hudson County', 'state' => 'NJ', 'fips' => '34017'],
            ['name' => 'Monmouth County', 'state' => 'NJ', 'fips' => '34025'],
            ['name' => 'Ocean County', 'state' => 'NJ', 'fips' => '34029'],
            ['name' => 'Union County', 'state' => 'NJ', 'fips' => '34039'],
            ['name' => 'Camden County', 'state' => 'NJ', 'fips' => '34007'],
            ['name' => 'Passaic County', 'state' => 'NJ', 'fips' => '34031'],
            ['name' => 'Morris County', 'state' => 'NJ', 'fips' => '34027'],
            ['name' => 'Burlington County', 'state' => 'NJ', 'fips' => '34005'],
            ['name' => 'Bernalillo County', 'state' => 'NM', 'fips' => '35001'],
            ['name' => 'Dona Ana County', 'state' => 'NM', 'fips' => '35013'],
            ['name' => 'Santa Fe County', 'state' => 'NM', 'fips' => '35049'],
            ['name' => 'Sandoval County', 'state' => 'NM', 'fips' => '35043'],
            ['name' => 'San Juan County', 'state' => 'NM', 'fips' => '35045'],
            ['name' => 'Kings County', 'state' => 'NY', 'fips' => '36047'],
            ['name' => 'Queens County', 'state' => 'NY', 'fips' => '36081'],
            ['name' => 'New York County', 'state' => 'NY', 'fips' => '36061'],
            ['name' => 'Suffolk County', 'state' => 'NY', 'fips' => '36103'],
            ['name' => 'Bronx County', 'state' => 'NY', 'fips' => '36005'],
            ['name' => 'Nassau County', 'state' => 'NY', 'fips' => '36059'],
            ['name' => 'Westchester County', 'state' => 'NY', 'fips' => '36119'],
            ['name' => 'Erie County', 'state' => 'NY', 'fips' => '36029'],
            ['name' => 'Monroe County', 'state' => 'NY', 'fips' => '36055'],
            ['name' => 'Richmond County', 'state' => 'NY', 'fips' => '36085'],
            ['name' => 'Onondaga County', 'state' => 'NY', 'fips' => '36067'],
            ['name' => 'Albany County', 'state' => 'NY', 'fips' => '36001'],
            ['name' => 'Mecklenburg County', 'state' => 'NC', 'fips' => '37119'],
            ['name' => 'Wake County', 'state' => 'NC', 'fips' => '37183'],
            ['name' => 'Guilford County', 'state' => 'NC', 'fips' => '37081'],
            ['name' => 'Forsyth County', 'state' => 'NC', 'fips' => '37067'],
            ['name' => 'Cumberland County', 'state' => 'NC', 'fips' => '37051'],
            ['name' => 'Durham County', 'state' => 'NC', 'fips' => '37063'],
            ['name' => 'Buncombe County', 'state' => 'NC', 'fips' => '37021'],
            ['name' => 'Gaston County', 'state' => 'NC', 'fips' => '37071'],
            ['name' => 'New Hanover County', 'state' => 'NC', 'fips' => '37129'],
            ['name' => 'Union County', 'state' => 'NC', 'fips' => '37179'],
            ['name' => 'Cabarrus County', 'state' => 'NC', 'fips' => '37025'],
            ['name' => 'Cass County', 'state' => 'ND', 'fips' => '38017'],
            ['name' => 'Burleigh County', 'state' => 'ND', 'fips' => '38015'],
            ['name' => 'Grand Forks County', 'state' => 'ND', 'fips' => '38035'],
            ['name' => 'Ward County', 'state' => 'ND', 'fips' => '38101'],
            ['name' => 'Williams County', 'state' => 'ND', 'fips' => '38105'],
            ['name' => 'Cuyahoga County', 'state' => 'OH', 'fips' => '39035'],
            ['name' => 'Franklin County', 'state' => 'OH', 'fips' => '39049'],
            ['name' => 'Hamilton County', 'state' => 'OH', 'fips' => '39061'],
            ['name' => 'Summit County', 'state' => 'OH', 'fips' => '39153'],
            ['name' => 'Montgomery County', 'state' => 'OH', 'fips' => '39113'],
            ['name' => 'Lucas County', 'state' => 'OH', 'fips' => '39095'],
            ['name' => 'Butler County', 'state' => 'OH', 'fips' => '39017'],
            ['name' => 'Stark County', 'state' => 'OH', 'fips' => '39151'],
            ['name' => 'Lorain County', 'state' => 'OH', 'fips' => '39093'],
            ['name' => 'Mahoning County', 'state' => 'OH', 'fips' => '39099'],
            ['name' => 'Oklahoma County', 'state' => 'OK', 'fips' => '40109'],
            ['name' => 'Tulsa County', 'state' => 'OK', 'fips' => '40143'],
            ['name' => 'Cleveland County', 'state' => 'OK', 'fips' => '40027'],
            ['name' => 'Canadian County', 'state' => 'OK', 'fips' => '40017'],
            ['name' => 'Comanche County', 'state' => 'OK', 'fips' => '40031'],
            ['name' => 'Multnomah County', 'state' => 'OR', 'fips' => '41051'],
            ['name' => 'Washington County', 'state' => 'OR', 'fips' => '41067'],
            ['name' => 'Clackamas County', 'state' => 'OR', 'fips' => '41005'],
            ['name' => 'Lane County', 'state' => 'OR', 'fips' => '41039'],
            ['name' => 'Marion County', 'state' => 'OR', 'fips' => '41047'],
            ['name' => 'Jackson County', 'state' => 'OR', 'fips' => '41029'],
            ['name' => 'Deschutes County', 'state' => 'OR', 'fips' => '41017'],
            ['name' => 'Philadelphia County', 'state' => 'PA', 'fips' => '42101'],
            ['name' => 'Allegheny County', 'state' => 'PA', 'fips' => '42003'],
            ['name' => 'Montgomery County', 'state' => 'PA', 'fips' => '42091'],
            ['name' => 'Bucks County', 'state' => 'PA', 'fips' => '42017'],
            ['name' => 'Delaware County', 'state' => 'PA', 'fips' => '42045'],
            ['name' => 'Lancaster County', 'state' => 'PA', 'fips' => '42071'],
            ['name' => 'Chester County', 'state' => 'PA', 'fips' => '42029'],
            ['name' => 'York County', 'state' => 'PA', 'fips' => '42133'],
            ['name' => 'Berks County', 'state' => 'PA', 'fips' => '42011'],
            ['name' => 'Lehigh County', 'state' => 'PA', 'fips' => '42077'],
            ['name' => 'Luzerne County', 'state' => 'PA', 'fips' => '42079'],
            ['name' => 'Dauphin County', 'state' => 'PA', 'fips' => '42043'],
            ['name' => 'Providence County', 'state' => 'RI', 'fips' => '44007'],
            ['name' => 'Kent County', 'state' => 'RI', 'fips' => '44003'],
            ['name' => 'Washington County', 'state' => 'RI', 'fips' => '44009'],
            ['name' => 'Newport County', 'state' => 'RI', 'fips' => '44005'],
            ['name' => 'Bristol County', 'state' => 'RI', 'fips' => '44001'],
            ['name' => 'Greenville County', 'state' => 'SC', 'fips' => '45045'],
            ['name' => 'Richland County', 'state' => 'SC', 'fips' => '45079'],
            ['name' => 'Charleston County', 'state' => 'SC', 'fips' => '45019'],
            ['name' => 'Horry County', 'state' => 'SC', 'fips' => '45051'],
            ['name' => 'Spartanburg County', 'state' => 'SC', 'fips' => '45083'],
            ['name' => 'Lexington County', 'state' => 'SC', 'fips' => '45063'],
            ['name' => 'York County', 'state' => 'SC', 'fips' => '45091'],
            ['name' => 'Anderson County', 'state' => 'SC', 'fips' => '45007'],
            ['name' => 'Minnehaha County', 'state' => 'SD', 'fips' => '46099'],
            ['name' => 'Pennington County', 'state' => 'SD', 'fips' => '46103'],
            ['name' => 'Lincoln County', 'state' => 'SD', 'fips' => '46083'],
            ['name' => 'Brown County', 'state' => 'SD', 'fips' => '46013'],
            ['name' => 'Brookings County', 'state' => 'SD', 'fips' => '46011'],
            ['name' => 'Shelby County', 'state' => 'TN', 'fips' => '47157'],
            ['name' => 'Davidson County', 'state' => 'TN', 'fips' => '47037'],
            ['name' => 'Knox County', 'state' => 'TN', 'fips' => '47093'],
            ['name' => 'Hamilton County', 'state' => 'TN', 'fips' => '47065'],
            ['name' => 'Rutherford County', 'state' => 'TN', 'fips' => '47149'],
            ['name' => 'Williamson County', 'state' => 'TN', 'fips' => '47187'],
            ['name' => 'Sumner County', 'state' => 'TN', 'fips' => '47165'],
            ['name' => 'Montgomery County', 'state' => 'TN', 'fips' => '47125'],
            ['name' => 'Harris County', 'state' => 'TX', 'fips' => '48201'],
            ['name' => 'Dallas County', 'state' => 'TX', 'fips' => '48113'],
            ['name' => 'Tarrant County', 'state' => 'TX', 'fips' => '48439'],
            ['name' => 'Bexar County', 'state' => 'TX', 'fips' => '48029'],
            ['name' => 'Travis County', 'state' => 'TX', 'fips' => '48453'],
            ['name' => 'Collin County', 'state' => 'TX', 'fips' => '48085'],
            ['name' => 'Hidalgo County', 'state' => 'TX', 'fips' => '48215'],
            ['name' => 'El Paso County', 'state' => 'TX', 'fips' => '48141'],
            ['name' => 'Denton County', 'state' => 'TX', 'fips' => '48121'],
            ['name' => 'Fort Bend County', 'state' => 'TX', 'fips' => '48157'],
            ['name' => 'Montgomery County', 'state' => 'TX', 'fips' => '48339'],
            ['name' => 'Williamson County', 'state' => 'TX', 'fips' => '48491'],
            ['name' => 'Cameron County', 'state' => 'TX', 'fips' => '48061'],
            ['name' => 'Nueces County', 'state' => 'TX', 'fips' => '48355'],
            ['name' => 'Brazoria County', 'state' => 'TX', 'fips' => '48039'],
            ['name' => 'Salt Lake County', 'state' => 'UT', 'fips' => '49035'],
            ['name' => 'Utah County', 'state' => 'UT', 'fips' => '49049'],
            ['name' => 'Davis County', 'state' => 'UT', 'fips' => '49011'],
            ['name' => 'Weber County', 'state' => 'UT', 'fips' => '49057'],
            ['name' => 'Washington County', 'state' => 'UT', 'fips' => '49053'],
            ['name' => 'Cache County', 'state' => 'UT', 'fips' => '49005'],
            ['name' => 'Chittenden County', 'state' => 'VT', 'fips' => '50007'],
            ['name' => 'Rutland County', 'state' => 'VT', 'fips' => '50021'],
            ['name' => 'Washington County', 'state' => 'VT', 'fips' => '50023'],
            ['name' => 'Windsor County', 'state' => 'VT', 'fips' => '50027'],
            ['name' => 'Addison County', 'state' => 'VT', 'fips' => '50001'],
            ['name' => 'Fairfax County', 'state' => 'VA', 'fips' => '51059'],
            ['name' => 'Prince William County', 'state' => 'VA', 'fips' => '51153'],
            ['name' => 'Virginia Beach City', 'state' => 'VA', 'fips' => '51810'],
            ['name' => 'Loudoun County', 'state' => 'VA', 'fips' => '51107'],
            ['name' => 'Chesterfield County', 'state' => 'VA', 'fips' => '51041'],
            ['name' => 'Henrico County', 'state' => 'VA', 'fips' => '51087'],
            ['name' => 'Norfolk City', 'state' => 'VA', 'fips' => '51710'],
            ['name' => 'Arlington County', 'state' => 'VA', 'fips' => '51013'],
            ['name' => 'Richmond City', 'state' => 'VA', 'fips' => '51760'],
            ['name' => 'Newport News City', 'state' => 'VA', 'fips' => '51700'],
            ['name' => 'King County', 'state' => 'WA', 'fips' => '53033'],
            ['name' => 'Pierce County', 'state' => 'WA', 'fips' => '53053'],
            ['name' => 'Snohomish County', 'state' => 'WA', 'fips' => '53061'],
            ['name' => 'Spokane County', 'state' => 'WA', 'fips' => '53063'],
            ['name' => 'Clark County', 'state' => 'WA', 'fips' => '53011'],
            ['name' => 'Thurston County', 'state' => 'WA', 'fips' => '53067'],
            ['name' => 'Kitsap County', 'state' => 'WA', 'fips' => '53035'],
            ['name' => 'Yakima County', 'state' => 'WA', 'fips' => '53077'],
            ['name' => 'Whatcom County', 'state' => 'WA', 'fips' => '53073'],
            ['name' => 'Benton County', 'state' => 'WA', 'fips' => '53005'],
            ['name' => 'Kanawha County', 'state' => 'WV', 'fips' => '54039'],
            ['name' => 'Berkeley County', 'state' => 'WV', 'fips' => '54003'],
            ['name' => 'Cabell County', 'state' => 'WV', 'fips' => '54011'],
            ['name' => 'Monongalia County', 'state' => 'WV', 'fips' => '54061'],
            ['name' => 'Wood County', 'state' => 'WV', 'fips' => '54107'],
            ['name' => 'Milwaukee County', 'state' => 'WI', 'fips' => '55079'],
            ['name' => 'Dane County', 'state' => 'WI', 'fips' => '55025'],
            ['name' => 'Waukesha County', 'state' => 'WI', 'fips' => '55133'],
            ['name' => 'Brown County', 'state' => 'WI', 'fips' => '55009'],
            ['name' => 'Racine County', 'state' => 'WI', 'fips' => '55101'],
            ['name' => 'Outagamie County', 'state' => 'WI', 'fips' => '55087'],
            ['name' => 'Winnebago County', 'state' => 'WI', 'fips' => '55139'],
            ['name' => 'Kenosha County', 'state' => 'WI', 'fips' => '55059'],
            ['name' => 'Laramie County', 'state' => 'WY', 'fips' => '56021'],
            ['name' => 'Natrona County', 'state' => 'WY', 'fips' => '56025'],
            ['name' => 'Campbell County', 'state' => 'WY', 'fips' => '56005'],
            ['name' => 'Sweetwater County', 'state' => 'WY', 'fips' => '56037'],
            ['name' => 'Fremont County', 'state' => 'WY', 'fips' => '56013'],
            ['name' => 'Albany County', 'state' => 'WY', 'fips' => '56001'],
            ['name' => 'Sheridan County', 'state' => 'WY', 'fips' => '56033'],
            ['name' => 'Teton County', 'state' => 'WY', 'fips' => '56039'],
        ];
    }
}
