<?php

namespace App\Services\AskAi;

/**
 * AskAiQuestionClassifierService — Deterministic Question Classifier
 *
 * GOVERNANCE BLOCK:
 * ==================================================================================
 * ROLE: Deterministic keyword-based classifier for Ask AI user questions.
 * Accepts a plain question string and returns a structured classification
 * (question_type, confidence, reason) using keyword matching only.
 *
 * This service MUST NEVER:
 *   - Call any external LLM, language model, or external HTTP service.
 *   - Execute any database write (save, update, create, delete).
 *   - Infer, estimate, or invent values for missing data.
 *   - Generate any AI answer text or call OpenAI.
 *   - Create routes, controllers, Blade views, or database migrations.
 *   - Rank, sort, or recommend any listing, offer, buyer, or agent.
 *   - Reference or infer protected class characteristics.
 * ==================================================================================
 */
class AskAiQuestionClassifierService
{
    /**
     * Keyword rule map for each question type.
     *
     * Each entry is an array of keyword strings. A match is detected when any
     * keyword appears in the lowercased question (case-insensitive substring match).
     *
     * Order matters: types are evaluated top-to-bottom; the first match wins.
     * 'prohibited' is checked before all other types to ensure hard refusals fire first.
     * 'compatibility_signals' is checked before 'buyer_tenant_match' so that
     * score-specific phrases (e.g. "match score") are not swallowed by buyer/tenant terms.
     * 'unsupported' is never listed here — it is the fallback when nothing matches.
     */
    private const KEYWORD_RULES = [
        'prohibited' => [
            'race',
            'racial',
            'race of',
            'religion',
            'religious',
            'nationality',
            'national origin',
            'ethnic',
            'ethnicity',
            'familial status',
            'disability',
            'handicap',
            'sex offender',
            'gender identity',
            'sexual orientation',
            'protected class',
            'fair housing',
            'discrimination',
            'discriminate',
            'neighborhood demographic',
            'neighborhood demographics',
            'diverse neighborhood',
            'neighborhood diversity',
            'demographics',
            'who lives there',
            'type of people',
            'kind of people',
            'school district',
            'school district quality',
            'school quality',
            'best school',
            'good school',
            'best schools',
            'worst schools',
            'schools near',
            'crime statistics',
            'crime rate',
            'crime in',
            'criminal activity',
            'how safe is',
            'is it safe',
            'safe neighborhood',
            'safe area',
            'dangerous',
            'gang',
            'good for kids',
            'good for families',
            'kid friendly',
            'child friendly',
            'families with children',
        ],

        // -----------------------------------------------------------------------
        // listing_facts — Deterministic factual lookup for listing fields and
        // seller/landlord FAQ answers. Routes before buyer_tenant_match so that
        // structural listing questions (bedrooms, price, lease length) are answered
        // from listing data rather than incorrectly trapped as match criteria.
        // -----------------------------------------------------------------------
        'listing_facts' => [
            // Bedrooms / Bathrooms
            'how many bedrooms',
            'how many bathrooms',
            'number of bedrooms',
            'number of bathrooms',
            'bedrooms does',
            'bathrooms does',
            'bedroom count',
            'bathroom count',
            'bedrooms',
            'bathrooms',
            // Asking price / sale price
            'asking price',
            'starting price',
            'list price',
            'listed price',
            'buy now price',
            'sale price',
            'how much does it cost',
            'what is the price',
            'what is the cost',
            'purchase price',
            // Rent amount
            'monthly rent',
            'rent amount',
            'rental price',
            'how much is the rent',
            'how much does it rent',
            'what is the rent',
            'rent per month',
            // Lease length — bare 'lease length' and 'desired lease length' are intentionally
            // excluded here so generic buyer_tenant_match phrases ("is the tenant flexible on
            // lease length", "would the tenant take a longer lease") are not swallowed.
            // The possessive form "tenant's desired lease" is safe to include because none of
            // the buyer_tenant_match keywords use that phrasing — it unambiguously signals
            // a field-lookup ("What is the tenant's desired lease length?").
            'lease term',
            'what is the lease',
            'how long is the lease',
            'length of lease',
            'lease duration',
            "tenant's desired lease",
            // Pets
            'pets allowed',
            'pet policy',
            'allow pets',
            'allows pets',
            'are pets allowed',
            'pet restrictions',
            'pet deposit',
            'is the property pet',
            // HOA
            'hoa fee',
            'monthly hoa',
            'homeowners association fee',
            'homeowners association',
            'association fee',
            'is there an hoa',
            'does it have an hoa',
            'hoa amount',
            'hoa cost',
            'hoa',
            // Property type
            'property type',
            'what type of property',
            'type of property',
            'what kind of property',
            'what property type',
            'what is the property type',
            'kind of property',
            // View / Water view
            'what is the view',
            'water view',
            'does it have a view',
            'lake view',
            'ocean view',
            'river view',
            'waterfront view',
            'what view does it have',
            'what view',
            'scenic view',
            'is there a water view',
            // Credit score range (tenant) — only specific phrases to avoid swallowing
            // "is credit score listed?" which belongs to missing_data.
            'credit score range',
            'tenant credit score',
            'what is the credit score',
            'credit range',
            'what credit score',
            'required credit score',
            // Pool
            'is there a pool',
            'does it have a pool',
            'pool included',
            'has a pool',
            'have a pool',
            // Parking / Garage
            'parking spaces',
            'parking space',
            'how many parking',
            'garage spaces',
            'how many garages',
            'how many garage',
            'parking available',
            'garage',
            'is there a garage',
            'does it have a garage',
            'does the property have a garage',
            'attached garage',
            'detached garage',
            'garage parking',
            // Appliances
            'appliances included',
            'what appliances',
            'which appliances',
            'appliances come with',
            'appliances are included',
            'does it include appliances',
            // Utilities
            'utilities included',
            'what utilities',
            'which utilities',
            'utilities are included',
            'who pays utilities',
            'does it include utilities',
            'what is included in rent',
            // Move-in requirements (security deposit, application fee, etc.)
            'required at move in',
            'what is required at move in',
            'what is required to move in',
            'move in requirements',
            'move-in requirements',
            'what do you need to move in',
            'what do i need to move in',
            'what is needed to move in',
            'required to move in',
            'required to rent this',
            'what do i need to rent',
            'what is needed to rent',
            // Showing instructions
            'showing instructions',
            'how to schedule a showing',
            'schedule a showing',
            'how do i view this',
            'how do i tour',
            // Square footage
            'square feet',
            'square footage',
            'sq ft',
            'sqft',
            'heated sqft',
            'how big is the',
            'how large is the',
            'size of the property',
            'size of the home',
            'size of the unit',
            // Year built / age
            'year built',
            'when was it built',
            'when was the home built',
            'when was this home built',
            'when was the property built',
            'when was this property built',
            'how old is the home',
            'how old is the property',
            'how old is this home',
            'age of the home',
            'age of the property',
            // Roof / HVAC / mechanical
            'roof age',
            'roof condition',
            'age of roof',
            'age of the roof',
            'condition of the roof',
            'condition is the roof',
            'what condition is the roof',
            'what is the age of the roof',
            'when was the roof',
            'how old is the roof',
            "what's the roof situation",
            'what is the roof situation',
            'tell me about the roof',
            'roof type',
            'roof material',
            'roofing material',
            'what type of roof',
            'what kind of roof',
            'hvac',
            'air conditioning',
            'heating system',
            'cooling system',
            'water heater',
            // Property tax
            'property tax',
            'property taxes',
            'annual taxes',
            'annual tax',
            'tax amount',
            'annual property tax',
            'real estate tax',
            'real estate taxes',
            'what are the taxes',
            'what is the taxes',
            'what is the tax',
            "what's the taxes",
            "what's the tax",
            'taxes on this property',
            'tax on this property',
            'how much are the taxes',
            'how much are property taxes',
            'how much are the property taxes',
            // Flood zone
            'flood zone',
            'is it in a flood zone',
            'in a flood zone',
            // Availability / move-in date for the listing
            'available date',
            'when is it available',
            'when does it become available',
            'available for rent',
            // Move-in date / timeframe — factual retrieval phrases only.
            // Bare 'move-in date' / 'move in date' stay in buyer_tenant_match so that
            // compatibility-framed questions ("does the move-in date work for this tenant?")
            // are not swallowed here.
            'what is the move-in date',
            'when is the move-in date',
            'what is the move in date',
            'when is the move in date',
            'move-in timeframe',
            'move in timeframe',
            'move-in schedule',
            'available move-in',
            // Buyer / tenant preferred area / location
            'preferred areas',
            'preferred neighborhoods',
            'preferred cities',
            'preferred locations',
            'where does the buyer want to live',
            'location preferences',
            'location preference',
            'what cities does the buyer prefer',
            'which cities is the buyer looking in',
            'cities the buyer is interested in',
            'preferred counties',
            'what counties is the buyer looking in',
            'which counties does the buyer prefer',
            // Generic city/county phrases — matches "What cities are you interested in?"
            // "Which cities are on the list?", etc. These are short bare phrases; the
            // LISTING_KEY_KEYWORD_MAP has the same phrases for precise routing.
            'what cities',
            'which cities',
            'what counties',
            'which counties',
            'cities are you interested in',
            'cities interested in',
            // Tenant monthly income
            'monthly income',
            'household income',
            'tenant monthly income',
            'what is the tenant income',
            'how much does the tenant earn',
            'income of the tenant',
            'household monthly income',
            'tenant income',
            // Seller credit / contribution
            'seller credit offered',
            'is the seller offering a credit',
            'seller contribution credit',
            'does the seller offer a credit',
            'seller credit',
            'seller contribution',
            // Closing-cost credit synonyms
            'credit toward closing',
            'credits toward closing',
            'closing credit',
            'seller credit at closing',
            'closing cost credit',
            // Pet policy (landlord)
            'pet policy',
            'pet policy details',
            'do you accept pets',
            'accept pets',
            'does this rental accept pets',
            'does the landlord accept pets',
            'is this rental pet-friendly',
            // Move-in timeframe synonyms
            'when do they want to move',
            'when can they move',
            'target move date',
            'desired move date',
            'move-in timeline',
            'move in timeline',
            // Condo / additional fees
            'condo fee',
            // Smoking
            'smoking policy',
            'smoking allowed',
            'is smoking allowed',
            // Subletting
            'subletting allowed',
            'can i sublet',
            'sublease allowed',
            'is subletting permitted',
            // Average utility costs (FAQ answer — distinct from "utilities included")
            'utility costs',
            'average utility',
            'monthly utility bill',
            'how much are utilities',
            'what are the utility costs',
            'average electric bill',
            'average gas bill',
            // Renovations / upgrades (FAQ answer)
            'recent renovations',
            'what renovations',
            'what upgrades have',
            'has it been renovated',
            'renovation history',
            'what has been updated',
            // Known defects / issues (FAQ answer)
            'known defects',
            'known issues',
            'any known problems',
            'deferred repairs',
            'any defects',
            // Pest / termite history (FAQ answer)
            'pest history',
            'termite history',
            'termite damage',
            'any pest issues',
            'have there been termites',
            // Foundation (FAQ answer)
            'foundation type',
            'what type of foundation',
            'foundation condition',
            'foundation problems',
            // Mold history (FAQ answer)
            'mold history',
            'any mold issues',
            'has there been mold',
            'mold remediation',
            // Flood / water damage history (FAQ answer — distinct from flood zone status)
            'ever flooded',
            'flood history',
            'has it flooded',
            'flooding history',
            'water damage history',
            'has the property flooded',
            // Seller concessions (FAQ answer)
            'seller concessions',
            'concessions offered',
            'offering concessions',
            'closing cost credits',
            'closing cost credit',
            'credit toward closing',
            'credits toward closing',
            'closing credit',
            'seller credit at closing',
            'repair credits',
            // Items excluded / what conveys (FAQ answer)
            'items excluded',
            'what does not convey',
            'what conveys',
            'what stays with',
            'excluded from sale',
            // As-is condition (FAQ answer)
            'sold as-is',
            'being sold as is',
            'as-is condition',
            'as is sale',
            // Closing timeline flexibility (FAQ answer)
            'closing timeline flexibility',
            'flexible on closing',
            // HVAC age (FAQ answer — age/service, distinct from system type)
            'hvac age',
            'how old is the hvac',
            'hvac last serviced',
            'when was the ac replaced',
            // Water heater (FAQ answer — age/type details)
            'water heater age',
            'how old is the water heater',
            'water heater type',
            'is there a tankless',
            // Maintenance requests (landlord FAQ answer)
            'maintenance requests',
            'how are repairs handled',
            'maintenance response',
            'how do i report a repair',
            // Emergency maintenance (landlord FAQ answer)
            'emergency maintenance',
            '24 hour maintenance',
            'after hours emergency',
            // Security features (landlord FAQ answer)
            'security system',
            'security cameras',
            'gated community access',
            'building security',
            // Lease renewal process (landlord FAQ answer — process, not just terms)
            'lease renewal process',
            'how does lease renewal work',
            'can i renew the lease',
            'renewing the lease',
            // Closing date
            'closing date',
            'preferred closing',
            // Lot size / acreage
            'lot size',
            'acreage',
            'how many acres',
            // Unit count
            'number of units',
            'how many units',
            // Address / location of the listing
            'address',
            'property address',
            'what is the address',
            "what's the address",
            'where is this property',
            'where is the property',
            'property location',
            'location of this property',
            'location of the property',
            // In-unit laundry
            'laundry',
            'in-unit laundry',
            'in unit laundry',
            'washer dryer',
            'washer and dryer',
            // MLS
            'mls number',
            'mls id',
            // Key features — factual enumeration of listing attributes.
            // 'key features' (plural) routes here so questions like
            // "What are the key features of this property?" resolve from
            // listing data rather than requiring property_intelligence (DNA profile).
            // 'key feature' (singular) stays in property_standout for standout/highlight intent.
            'key features',
            'what are the key features',
            // ---- Seller addon: Commercial Income ----------------------------
            'net operating income',
            'annual noi',
            'what is the noi',
            'property noi',
            'noi for this property',
            'current cap rate',
            'capitalization rate',
            'what is the cap rate',
            'property cap rate',
            'existing tenant lease terms',
            'current tenant lease terms',
            'tenant lease expiration',
            'occupancy rate',
            'what is the occupancy rate',
            'how occupied is the property',
            'annual operating expenses',
            'operating expense breakdown',
            'property operating expenses',
            'value add opportunities',
            'value-add potential',
            'upside potential for the property',
            // ---- Seller addon: Business Opportunity -------------------------
            'annual business revenue',
            'gross revenue of the business',
            'annual gross revenue',
            'annual net profit',
            'owner discretionary earnings',
            'business net profit',
            'why is the business being sold',
            'reason for selling the business',
            'why is the owner selling the business',
            'how many employees does the business have',
            'business employee count',
            'number of employees in this business',
            'seller training after sale',
            'transition support from seller',
            'will the seller provide training',
            'business location lease status',
            'is the business location leased',
            'lease for the business location',
            'inventory included in business sale',
            'equipment included in the sale',
            'what is included in the business sale price',
            // ---- Business listing field phrases (listing.* routing) ----------
            'annual revenue',
            'business revenue',
            'total annual revenue',
            'business name',
            'name of the business',
            'year established',
            'when was this business established',
            'how long has this business been operating',
            'business founding year',
            'how old is this business',
            'nda required',
            'is an nda required',
            'non-disclosure agreement required',
            'confidentiality agreement required',
            'financial statements available',
            'financial records available',
            'financial statements for the business',
            'sale includes',
            'what does the sale include',
            'what assets are included in this business sale',
            'business assets',
            'assets included with business',
            'ffe value',
            'furniture fixtures and equipment value',
            'gross profit',
            'business gross profit',
            'gross profit margin',
            'sde',
            'ebitda',
            'seller discretionary earnings',
            'owner earnings',
            'discretionary earnings',
            'inventory value',
            'value of the inventory',
            'current inventory value',
            'business licenses',
            'licenses required for this business',
            'permits and licenses',
            'business lease monthly rent',
            'monthly rent for the business location',
            'business location rent',
            'business lease assignable',
            'is the business lease assignable',
            'assignable business lease',
            // ---- Landlord approval conditions --------------------------------
            'landlord approval conditions',
            'approval requirements',
            'credit requirements to rent',
            'tenant approval criteria',
            'landlord requirements for tenants',
            'qualifying conditions for this rental',
            // ---- Bare VacantLand phrases not already in list ----------------
            'road frontage',
            'vegetation',
            'easements',
            'water available',
            'telecom available',
            // ---- Multi-unit aliases -----------------------------------------
            'multiple units',
            'multi-unit',
            'how many rental units',
            'separate living units',
            // ---- Smoking, occupants, lease (bare/short forms) ---------------
            'smoking policy',
            'is smoking allowed',
            'number of occupants',
            'occupant limit',
            'minimum lease term',
            'shortest lease available',
            // ---- Investment aliases -----------------------------------------
            'investment yield',
            'rent roll',
            'unit type breakdown',
            'bedroom and bath mix',
            // ---- Misc alias coverage ----------------------------------------
            'flood zone code',
            'maximum budget',
            'rental restrictions',
            'are there any rental restrictions',
            'how much can the tenant afford',
            'how long of a lease does this tenant want',
            // ---- Seller addon: Vacant Land ----------------------------------
            'utilities available on this land',
            'land utilities',
            'utilities on the land parcel',
            'land zoning designation',
            'what is the zoning for this land',
            'what is the zoning',
            'zoning classification',
            'how is this land zoned',
            'permitted uses for the land',
            'permitted uses for this property',
            'road access to the land',
            'land road access',
            'parcel road access',
            'road frontage type',
            'what type of road frontage',
            'does this lot have road frontage',
            'road surface type',
            'what is the road surface',
            'how is the road paved',
            'is the road paved',
            'soil conditions for this land',
            'land topography conditions',
            'soil and topography of the land',
            'land survey available',
            'is a survey available for the land',
            'land survey on file',
            'development restrictions on this land',
            'deed restrictions on the land',
            'easements on the parcel',
            'are there any easements',
            'what easements are on',
            // Waterfront / water access (VL)
            'is this property waterfront',
            'waterfront property',
            'is it on the water',
            'waterfront access',
            'water access type',
            'what type of water access',
            'lake access',
            'river access',
            'creek access',
            // Lot dimensions
            'lot dimensions',
            'what are the lot dimensions',
            'size of the lot',
            'how wide is the lot',
            'depth of the lot',
            // Current use / adjacent use
            'current land use',
            'current use of the land',
            'how is the land currently used',
            'adjacent land use',
            'adjacent use of the land',
            'surrounding land use',
            'what is next to this property',
            'what is the adjacent property used for',
            // Site utilities availability
            'is water available on this land',
            'water availability at site',
            'water to the site',
            'is sewer available on this land',
            'sewer availability at site',
            'sewer to the site',
            'is electric available on this land',
            'electric availability at site',
            'is electricity available to the lot',
            'power to the site',
            'is gas available on this land',
            'natural gas availability',
            'is gas service available to this lot',
            'is internet available on this land',
            'telecom availability on this land',
            'broadband availability at this lot',
            // Front footage / wells / septics
            'front footage',
            'how many feet of frontage',
            'feet of road frontage',
            'how many wells',
            'number of wells on the land',
            'are there any wells on this property',
            'how many septic systems',
            'number of septics',
            'are there any septic systems',
            // Fences / vegetation / buildable
            'are there fences on this land',
            'what type of fencing is there',
            'fencing on the property',
            'is the property fenced',
            'what vegetation is on the land',
            'type of vegetation',
            'is there vegetation on this lot',
            'trees or plants on the land',
            'is this land buildable',
            'can you build on this lot',
            'buildable land status',
            // ---- Landlord addon: Commercial Lease ---------------------------
            'cam charges',
            'common area maintenance charges',
            'what are the cam charges',
            'commercial lease structure',
            'is this a nnn lease',
            'triple net lease',
            'gross lease type',
            'tenant improvement allowance',
            'ti allowance',
            'buildout allowance for this space',
            'buildout flexibility',
            'can the tenant modify the space',
            'tenant buildout modifications',
            'commercial signage rights',
            'exterior signage rights for this lease',
            'signage rights included',
            'loading dock available',
            'freight elevator available',
            'loading dock for this commercial space',
            'electrical capacity of the space',
            'power capacity of the commercial space',
            'electrical service capacity',
            'commercial parking ratio',
            'parking ratio for this space',
            'parking spaces per square foot for this commercial property',
            'commercial exclusivity rights',
            'exclusive use rights for this space',
            'exclusivity clause available',
            'expansion option for this space',
            'right of first refusal on adjacent space',
            'rofr on adjacent space',
            'landlord maintenance responsibilities commercial',
            'what does the landlord maintain in commercial space',
            'commercial landlord responsibilities',
            'building access hours commercial',
            'what are the building access hours',
            'suite access hours',
            // ---- Tenant FAQ (faq_q1–faq_q27) --------------------------------
            'does the tenant work from home',
            'tenant work from home',
            'remote work setup for tenant',
            'what matters most in day to day living for the tenant',
            'tenant daily living priorities',
            'ideal neighborhood for the tenant',
            'tenant neighborhood preference description',
            'tenant noise sensitivity',
            'how sensitive is the tenant to noise',
            'which amenity matters most to the tenant',
            'tenant top amenity priority',
            'how important is outdoor space to the tenant',
            'tenant outdoor space importance',
            'does the tenant have pets',
            'tenant pet breed and size',
            'is the tenant willing to pay pet deposit',
            'tenant pet deposit willingness',
            'is the tenant flexible on lease length',
            'tenant lease length flexibility preference',
            'would the tenant consider a furnished unit',
            'tenant furnished unit preference',
            'how firm is the tenant move-in timeline',
            'tenant move-in timeline firmness',
            'could the tenant need to break the lease early',
            'tenant early lease termination risk',
            'would the tenant take a longer lease for rent reduction',
            'tenant lease term rent reduction preference',
            'what is driving the tenant rental search',
            'tenant rental search motivation',
            'how long was the tenant most recent tenancy',
            'tenant previous tenancy length',
            'is the tenant looking for short term or long term housing',
            'tenant short term or long term housing preference',
            'does the tenant have landlord or employer reference',
            'tenant reference availability',
            'what is the tenant source of income',
            'tenant income source type',
            'how does the tenant prefer to communicate with the landlord',
            'tenant landlord communication preference',
            'what is the tenant biggest concern in rental search',
            'tenant rental search concern',
            'what type of business will the tenant operate from this space',
            'tenant business type for commercial space',
            'does the tenant expect customer foot traffic',
            'tenant expected foot traffic at location',
            'does the tenant have special equipment or power requirements',
            'tenant equipment power needs',
            'does the tenant require exterior signage',
            'tenant exterior signage requirement',
            'will the tenant need to build out or modify the space',
            'tenant space buildout requirement',
            'what are the tenant expected hours of operation',
            'tenant operating hours for business',
            'is the tenant flexible on commercial lease term length',
            'tenant commercial lease term flexibility',
            // ---- Pre-existing pinned keys: missing classifier coverage -------
            // Seller: Condition
            'permits for renovations',
            'permits pulled',
            'work permitted',
            // Seller: Financial
            'internet providers',
            'internet available',
            'what internet providers',
            // Seller: Hidden Selling Points
            'hidden features',
            'non-obvious features',
            'best things about neighborhood',
            'neighborhood description',
            'most unique thing about this property',
            'distinctive features',
            // Seller: Location & Lifestyle
            'neighborhood vibe',
            'traffic near the property',
            'any noise concerns',
            'planned developments nearby',
            'any construction nearby',
            'commute options',
            'how far is the commute',
            'natural light',
            'nearby amenities',
            'what is nearby',
            'deed restrictions',
            'neighborhood covenants',
            // Seller: Flexibility & Negotiation (remaining)
            'leaseback option',
            'rent back after closing',
            'furniture negotiable',
            'any furniture included',
            'environmental concerns',
            'environmental issues',
            "seller's favorite features",
            'what does the seller love about',
            'why is the seller selling',
            'motivation for selling',
            'is it move-in ready',
            'move in ready',
            'storage space',
            'attic storage',
            // Landlord: Maintenance (remaining)
            'storage area included',
            'dedicated storage',
            'internet providers available',
            'planned renovations',
            'upcoming construction at the rental',
            // Landlord: Location & Neighbourhood (remaining)
            'noise levels',
            'how noisy is this rental',
            'what is close by the rental',
            'how close to public transit',
            'near a bus stop',
            'guest parking available',
            'visitor parking',
            // Landlord: Lifestyle (remaining)
            'is it furnished',
            'furnished apartment',
            'notice to vacate',
            'how much notice to leave',
            'what kind of tenant is preferred',
            'preferred tenant profile',
            'airbnb allowed',
            'vrbo allowed',
            'short term rental policy',
            'ev charging available',
            'electric vehicle charging',
            'bike storage',
            'bicycle storage',
            'individually metered',
            'separate utility meters',
            'renters insurance required',
            'do i need renters insurance',
            'lease to own',
            'rent to own option',
            'previous tenant feedback',
            'what do past tenants say',
            // Shared / generic
            'parking arrangements',
            'security features',
            'is there a security system',
            'security cameras',
            'showing tips',
            'best time to show',
            'landlord responsibilities',
            'what is landlord responsible for',
            'tenant rules',
            'rules for tenants',
            'what are the renewal terms',
            'terms for lease renewal',
            'how to set up utilities',
            'utility transfer instructions',
            'parking instructions',
            'assigned parking',
            'where do i park',
            // FAQ fields that route to listing_facts but need explicit classifier coverage
            'cable providers here',
            'fiber available at this rental',
            'bugs or mold',
            'any mold or pest issues',
            'why is this rental special',
            'what sets this rental apart',
            'hoa rules',
            'hoa restrictions',
            'detailed pet policy',
            'full pet policy',
            // Financing type — factual retrieval of requested financing structure
            // (e.g. "What financing type is requested?"). Distinct from buyer_criteria
            // negotiation questions; these look up the listing field directly.
            'financing type',
            'what financing type',
            'financing type requested',
            'requested financing',
            'type of financing',
            // Seller financing terms — factual retrieval of seller-offered financing.
            // Routes to listing_facts so the full listing context (including faq_answers)
            // is searched before OpenAI is called. Not in buyer_tenant_match because
            // these phrases describe the listing terms, not a buyer/tenant criterion.
            'seller financing',
            'seller finance',
            'seller will finance',
            'will the seller finance',
            'seller financing terms',
            'financing offered by seller',
            'owner financing',
            'owner will finance',
            'owner finance',
            'seller carry',
            'seller carryback',
            // Lease option / rent-to-own — factual retrieval of lease-option terms.
            // 'lease to own' is already covered; adding the 'lease option' variant.
            'lease option',
            'lease-option',
            'lease option terms',
            'option to purchase terms',
            // Desired lease length — factual phrasing only.
            // 'desired lease length' / 'preferred lease length' stay in buyer_tenant_match
            // so that compatibility-framed questions are not swallowed here.
            // These more-specific phrases address factual retrieval of the listing field.
            'what lease length is desired',
            'lease length is desired',
            // ---- LISTING_KEY_KEYWORD_MAP gap coverage --------------------------------
            // Phrases present in LISTING_KEY_KEYWORD_MAP but previously absent from this
            // classifier, causing them to fall through to the normalizer path.  Adding
            // them here ensures deterministic listing_facts routing for all 50 approved
            // listing.* fields without requiring an OpenAI round-trip.
            // Buyer maximum price
            'buyer maximum budget',
            'buyer max budget',
            'maximum price buyer',
            'buyer top price',
            // Tenant max rent / budget
            'tenant max rent',
            'maximum rent budget',
            'tenant rent budget',
            "tenant's rental budget",
            'tenant rental budget',
            'budget for rent',
            'maximum rental budget',
            // Property description — factual retrieval only.
            // Bare 'listing description' / 'property description' are ALSO marketing_angles
            // keywords; using them here would route creative-writing prompts to listing_facts.
            // Only specific factual-retrieval phrases are safe here.
            'what does the property description say',
            'what does the listing description say',
            'what is the property description',
            // Property condition (rental)
            'condition of the rental',
            'rental property condition',
            'property overall condition',
            // Carport
            'carport',
            'is there a carport',
            'does it have a carport',
            // Association amenities
            'association amenities',
            'community association offer',
            // Lease renewal option
            'renewal option available',
            'is lease renewal an option',
            'extension option for the lease',
            // Rental restrictions
            'rental restrictions on this property',
            'property rental restriction',
            // Subletting policy (listing field — distinct from FAQ subletting answer)
            'subletting policy',
            'subletting rules',
            // Parking terms
            'parking terms for this rental',
            'parking included in rent',
            // Buyer loan / pre-approval status
            'buyer pre-approved for a loan',
            'has the buyer been pre-approved',
            'loan pre-approval status',
            'is the buyer pre-approved',
            // Inspection / contingency criteria
            'inspection period',
            'buyer inspection contingency days',
            'inspection contingency',
            'home inspection contingency',
            'appraisal contingency',
            'does the buyer need the property to appraise',
            'financing contingency',
            'mortgage contingency',
            // Smoking policy (listing field — distinct from FAQ answer)
            'does this unit allow smoking',
            'is this a smoke-free unit',
            'smoke-free unit',
            // Buy-it-now price variants
            'buy it now price',
            'buy-it-now price',
            'fixed buy-now price',
            // Pet policy / rules
            'pet rules',
            'pet-friendly property',
            'is this pet-friendly',
            // Pet deposit / fee
            'pet fee amount',
            'monthly pet rent',
            // Lease terms (existing / inherited)
            'existing lease terms on this property',
            'current tenant lease on this property',
            // Lease length variants
            'what lease lengths are available',
            'lease length options',
            // Tenant pet details
            'tenant pet details',
            'tenant pet type and size',
            // Tenant preferred lease duration
            'tenant preferred lease duration',
            // Lease terms (existing inherited)
            'is there a tenant currently leasing',
            'inherited lease terms',
            // Inspection / contingency — sentence variants that lack the core keyword phrase
            'how many days for inspection',
            'is there a home inspection contingency',
            'does the buyer have a financing contingency',
            // Rental restrictions — secondary phrase
            'property rental restriction rules',
            // ---- Income / multifamily gap coverage --------------------------------
            // These phrases are present in LISTING_KEY_KEYWORD_MAP but previously
            // absent from the classifier, causing them to fall through to 'unsupported'
            // before detectListingFieldKey() was reached.
            'gross annual income',
            'total annual rent collected',
            'annual net income',
            'net operating income amount',
            'annual operating expenses',
            'total annual expenses',
            'how many units',
            'unit count',
            'unit mix',
            'bedroom mix',
            'rent roll',
            'operating statement',
            'income property',
            'duplex',
            'triplex',
            'quadplex',
            'multifamily type',
            'property type mix',
            'occupancy requirement',
            // ---- Income/Multifamily — buildings and property monthly income ----------------
            'how many buildings',
            'total buildings',
            'number of buildings',
            'property monthly income from rent',
            'monthly income this property generates',
            'investment property monthly income',
            // Use possessive/specific phrases only — bare 'cap rate' would swallow
            // "What is a cap rate in real estate?" which must stay 'educational'.
            'what is the cap rate',
            'cap rate for this',
            'the cap rate',
            'capitalization rate',
            // ---- Telecom / internet availability ---------------------------------
            // 'Is there internet or cable service available?' classifies as 'unsupported'
            // without this entry because no other listing_facts keyword covers it.
            'internet or cable',
            'is there internet',
            'broadband availability',
            // ---- Vacant Land utility availability --------------------------------
            // 'Is there water service to this lot?' and 'Is there sewer service to
            //  this lot?' are in LISTING_KEY_KEYWORD_MAP but classified as 'unsupported'
            //  without these entries because no existing keyword covers them.
            'is there water service',
            'is there sewer service',
            'water service to this lot',
            'sewer service to this lot',
        ],

        'compatibility_signals' => [
            'compatibility',
            'compatible',
            'compatibility score',
            'match score',
            'score breakdown',
            'how strong is the match',
            'financial compatibility',
            'financial match',
            'physical match',
            'terms match',
            'location match',
            'compatibility warning',
            'compatibility signal',
            'compatibility highlight',
            'how compatible',
        ],

        'property_standout' => [
            'stand out',
            'stands out',
            'what makes this',
            'what makes it',
            'what makes the property',
            'makes this property',
            'unique feature',
            'special about',
            'what is special',
            'best feature',
            'best features',
            'highlight',
            'highlights',
            'selling point',
            'selling points',
            'notable',
            'key feature',
            'top feature',
            'most impressive',
            'most appealing feature',
            'distinguish',
            'differentiator',
            'standout',
            'strength',
            'strengths',
            'benefit',
            'benefits',
            'good about this listing',
            'what is good about',
        ],

        'suited_audience' => [
            'suited for',
            'suitable for',
            'ideal for',
            'ideal buyer',
            'ideal tenant',
            'who would',
            'who would want',
            'who is this for',
            'who is this property for',
            'who is this listing for',
            'target audience',
            'target buyer',
            'target renter',
            'who should',
            'best fit for',
            'good fit for',
            'right buyer',
            'right renter',
            'right tenant',
            'who might',
            'appeal to',
            'type of buyer',
            'type of tenant',
            'what kind of buyer',
            'what kind of tenant',
            'lifestyle',
            'who is this good for',
            'good for who',
            'who would like this',
            'best suited for',
            'who would enjoy',
        ],

        'buyer_tenant_match' => [
            'good match for',
            'right match',
            'match for a buyer',
            'match for a tenant',
            'match for buyer',
            'match for tenant',
            'fit for the buyer',
            'fit for the tenant',
            'fit for buyer',
            'fit for tenant',
            'buyer fit',
            'tenant fit',
            'buyer match',
            'tenant match',
            'how well does',
            'how well do',
            'would a buyer',
            'would a tenant',
            'aligned with',
            'align with',
            'meet the buyer',
            'meet the tenant',
            'does this tenant have pets',
            'what does this tenant want',
            'what does this buyer want',
            'rent budget',
            'rental budget',
            'within budget',
            'purchase budget',
            'desired lease length',
            'preferred lease length',
            'move-in date',
            'move in date',
            'amenities required',
            'parking requirement',
        ],

        'missing_data' => [
            'what is missing',
            "what's missing",
            'missing data',
            'missing information',
            'missing from this listing',
            'missing field',
            'missing fields',
            'incomplete',
            'not filled',
            'not filled in',
            'not provided',
            'what data is missing',
            'no information',
            'lacking',
            'absent',
            'gaps in',
            'gap in',
            'what needs to be added',
            'what needs to be filled',
            'how complete is this',
            'what should be added',
            'do we know',
            'is there information about',
            'is income listed',
            'is credit score listed',
            'is pet information listed',
            'is budget listed',
            'is parking listed',
            'is lease length listed',
        ],

        'marketing_angles' => [
            'how to market',
            'marketing angle',
            'marketing strategy',
            'marketing approach',
            'best way to market',
            'how should i market',
            'how would you market',
            'how should this be marketed',
            'advertise this',
            'promote this listing',
            'listing pitch',
            'best pitch',
            'positioning for this',
            'listing description',
            'write a description',
            'draft a description',
            'property description',
            'tagline',
            'ad copy',
            'marketing idea',
            'marketing ideas',
            'listing description ideas',
            'ad ideas',
            'selling points',
        ],

        'educational' => [
            'what is a ',
            'what is an ',
            'what is escrow',
            'what is cap rate',
            'what is earnest',
            'what is closing',
            'what is a mortgage',
            'what is contingency',
            'how does escrow',
            'how does closing',
            'how does the appraisal',
            'how does a mortgage',
            'how does ',
            'how do ',
            'explain ',
            'define ',
            'definition',
            'overview',
            'introduction to',
            'teach me',
            'help me understand',
            'in general',
            'generally speaking',
            'real estate term',
            'real estate process',
            'closing cost',
            'closing costs',
            'escrow',
            'contingency',
            'earnest money',
            'mortgage',
            'appraisal',
            'inspection',
            'title insurance',
            'cap rate',
            'cash flow',
            'auction process',
            'bidding process',
            'platform process',
            'how does this platform',
        ],
    ];

    /**
     * Classify a plain user question into one of the nine approved question types.
     *
     * Output contract — always returns exactly these three keys:
     *   question_type  string  — one of the nine approved types, or 'unsupported'
     *   confidence     float   — value between 0.0 and 1.0 (rule-based, not probabilistic)
     *   reason         string  — human-readable explanation of why this type was selected
     *
     * @param  string $question  The raw user question string.
     * @return array{question_type: string, confidence: float, reason: string}
     */
    public function classify(string $question): array
    {
        $lower = mb_strtolower(trim($question));

        if ($lower === '') {
            return [
                'question_type' => 'unsupported',
                'confidence'    => 0.0,
                'reason'        => 'Empty question string provided; no classification possible.',
            ];
        }

        foreach (self::KEYWORD_RULES as $type => $keywords) {
            $matched = $this->findFirstMatch($lower, $keywords);

            if ($matched !== null) {
                return [
                    'question_type' => $type,
                    'confidence'    => $this->confidenceFor($type),
                    'reason'        => "Matched keyword rule for '{$type}': \"{$matched}\".",
                ];
            }
        }

        return [
            'question_type' => 'unsupported',
            'confidence'    => 0.0,
            'reason'        => 'No keyword rule matched; question does not map to any approved type.',
        ];
    }

    /**
     * Return the first keyword from the list that appears in the haystack, or null.
     */
    private function findFirstMatch(string $haystack, array $keywords): ?string
    {
        foreach ($keywords as $keyword) {
            if (str_contains($haystack, mb_strtolower($keyword))) {
                return $keyword;
            }
        }

        return null;
    }

    /**
     * Return a deterministic confidence value for each question type.
     *
     * Confidence reflects how reliably the keyword rule identifies the type,
     * not a probabilistic model score. 'prohibited' gets 1.0 because it is a
     * hard governance refusal and must never be downgraded. 'unsupported' always
     * returns 0.0 and is handled directly in classify().
     */
    private function confidenceFor(string $type): float
    {
        return match ($type) {
            'prohibited'            => 1.0,
            'listing_facts'         => 0.90,
            'compatibility_signals' => 0.85,
            'property_standout'     => 0.85,
            'suited_audience'       => 0.80,
            'buyer_tenant_match'    => 0.80,
            'missing_data'          => 0.80,
            'marketing_angles'      => 0.75,
            'educational'           => 0.70,
            default                 => 0.0,
        };
    }
}
