<?php

namespace App\Services;

/**
 * AgentPresetCatalog
 *
 * Single source of truth for service lists shown on the Agent Preset
 * management UI (/agent/presets).  Strings are sourced directly from the
 * bid-form service partials so that presets match exactly what appears in
 * the live bid forms.
 */
class AgentPresetCatalog
{
    /**
     * Valid roles and their available property types (DB-format keys).
     */
    public static function getRoles(): array
    {
        return ['buyer', 'seller', 'tenant', 'landlord'];
    }

    public static function getPropertyTypes(string $role): array
    {
        return match ($role) {
            'buyer', 'seller' => ['residential', 'income', 'commercial', 'business', 'vacant_land'],
            'tenant', 'landlord' => ['residential', 'commercial'],
            default => [],
        };
    }

    public static function isValidCombination(string $role, string $propertyType): bool
    {
        return in_array($role, static::getRoles())
            && in_array($propertyType, static::getPropertyTypes($role));
    }

    /**
     * Returns human-readable service strings for the given role + property type.
     * Returns an empty array for unsupported combinations.
     */
    public static function getServices(string $role, string $propertyType): array
    {
        return static::catalog()[$role][$propertyType] ?? [];
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Catalog data (sourced from bid-form service partials)
    // ─────────────────────────────────────────────────────────────────────────

    protected static function catalog(): array
    {
        return [
            'buyer'    => static::buyerCatalog(),
            'seller'   => static::sellerCatalog(),
            'tenant'   => static::tenantCatalog(),
            'landlord' => static::landlordCatalog(),
        ];
    }

    // ── BUYER ────────────────────────────────────────────────────────────────

    protected static function buyerCatalog(): array
    {
        return [
            'residential' => [
                'Create a branded flyer summarizing the Buyer’s purchase criteria',
                'Post the Buyer’s purchase criteria on Craigslist under the “Real Estate Wanted” section',
                'Share the Buyer’s purchase criteria on Nextdoor in Neighborhood or Community Groups',
                'Promote the Buyer’s purchase criteria on Facebook in Real Estate or Housing Groups',
                'Share the Buyer’s purchase criteria on Instagram using posts, stories, or reels',
                'Promote the Buyer’s purchase criteria on LinkedIn in Real Estate or Housing Groups',
                'Upload a TikTok video summarizing the Buyer’s purchase criteria',
                'Upload a YouTube video summarizing the Buyer’s purchase criteria',
                'Launch a mass email campaign promoting the Buyer’s purchase criteria',
                'Distribute branded postcards or flyers in the Buyer’s preferred neighborhoods',
                'Launch hyperlocal digital ads targeting the Buyer’s preferred purchase areas',
                'Send email alerts with new listings from the MLS that match the Buyer’s purchase criteria',
                'Search for off-market, pre-market, distressed, withdrawn, canceled, or expired properties that meet the Buyer’s purchase criteria',
                'Communicate with the Seller’s Agent or Seller to confirm availability, purchase terms, and showing instructions',
                'Evaluate properties with the Buyer and provide insights on pricing, terms, potential, and overall fit',
                'Schedule and attend property showings with the Buyer',
                'Coordinate or conduct virtual showings via live video or pre-recorded walkthroughs',
                'Preview properties on behalf of the Buyer upon request',
                'Provide factual observations on property layout and condition',
                'Draft and submit offers using state-approved purchase forms',
                'Provide the Buyer with the necessary disclosure forms required by state or local law',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Negotiate price, deposits, and contingencies with the Seller’s Agent or Seller (as permitted under the agency agreement)',
                'Manage communications with the Seller’s Agent or Seller',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Assist with inspection-related negotiations and Buyer requests for repairs',
                'Monitor contract milestones, contingency periods, and financing deadlines',
                'Provide referrals to Attorneys, Title Companies, Escrow Professionals, or Lenders (referrals only — no endorsement or warranty is made)',
                'Coordinate inspections, appraisals, and lease audits (if applicable)',
                'Coordinate with the Lender, Title, Escrow, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement for accuracy and coordinate with relevant parties if corrections are needed (no legal or financial advice provided)',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Schedule and confirm the Closing Appointment',
                'Provide a Comparative Market Analysis (CMA) with pricing recommendations based on comparable sales, neighborhood trends, and current market conditions (for informational purposes only — not a formal appraisal)',
                'Answer general questions about financing, loan options, property taxes, insurance, and escrow timelines (non-legal guidance)',
                'Provide factual information about neighborhood characteristics, school zones, crime data, and local amenities using third-party sources (no personal opinions or steering)',
                'Offer general guidance on inspection expectations, common repair requests, and contingency planning during the offer process (non-legal advice)',
            ],
            'income' => [
                'Create a branded flyer summarizing the Buyer’s purchase criteria',
                'Post the Buyer’s purchase criteria on Craigslist under the “Real Estate Wanted” section',
                'Share the Buyer’s purchase criteria on Nextdoor in Neighborhood or Community Groups',
                'Promote the Buyer’s purchase criteria on Facebook in Real Estate Investor or Multifamily Groups',
                'Share the Buyer’s purchase criteria on Instagram using posts, stories, or reels',
                'Promote the Buyer’s purchase criteria on LinkedIn in Investment or Property Management Groups',
                'Upload a TikTok video summarizing the Buyer’s purchase criteria',
                'Upload a YouTube video summarizing the Buyer’s purchase criteria',
                'Launch a mass email campaign promoting the Buyer’s purchase criteria',
                'Distribute branded postcards or flyers in the Buyer’s preferred neighborhoods',
                'Send email alerts with new listings that match the Buyer’s purchase criteria',
                'Search for off-market, pre-market, distressed, withdrawn, canceled, or expired properties that meet the Buyer’s purchase criteria',
                'Communicate with the Seller’s Agent or Sellers to confirm pricing, rental income, expenses, and showing instructions',
                'Schedule and attend property showings with the Buyer',
                'Coordinate or conduct virtual showings via live video or pre-recorded walkthroughs',
                'Preview properties on behalf of the Buyer upon request',
                'Draft and submit offers using state-approved purchase forms',
                'Provide the Buyer with the necessary disclosure forms required by state or local law',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Negotiate price, deposits, and contingencies with the Seller’s Agent or Seller',
                'Manage communication with the Seller’s Agent or Seller',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Assist with inspection-related negotiations and Buyer requests for repairs',
                'Monitor contract milestones, contingency periods, and financing deadlines',
                'Review and provide due diligence documents such as lease agreements, estoppel certificates, rent rolls, utility summaries, and operating expense breakdowns (as available)',
                'Coordinate with the Seller’s Agent, Buyer’s Lender, Title, Escrow, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement for accuracy and coordinate with relevant parties if corrections are needed (no legal or financial advice provided)',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Provide a Comparative Market Analysis (CMA) with pricing recommendations, rental comps, and Cap Rate estimates (for informational purposes only — not a formal appraisal)',
                'Answer general questions about financing options, rent control, property taxes, and Landlord responsibilities',
                'Provide factual information on rental demand, turnover rates, and sub market conditions using third-party sources',
            ],
            'commercial' => [
                'Create a branded flyer summarizing the Buyer’s purchase criteria',
                'Post the Buyer’s criteria on Craigslist under “Real Estate Wanted – Commercial”',
                'Promote the Buyer’s criteria on Facebook in Commercial Real Estate or Investment Groups',
                'Share the Buyer’s criteria on Instagram using posts, stories, or reels',
                'Promote the Buyer’s criteria on LinkedIn in Commercial or Investment Groups',
                'Upload a TikTok video summarizing the Buyer’s purchase criteria',
                'Upload a YouTube video summarizing the Buyer’s purchase criteria',
                'Launch a mass email campaign promoting the Buyer’s purchase criteria',
                'Distribute branded postcards or flyers in the Buyer’s preferred purchase areas',
                'Send property alerts that match the Buyer’s purchase criteria from the MLS or commercial listing platforms',
                'Search for off-market, pre-market, distressed, withdrawn, canceled, or expired listings that meet the Buyer’s criteria',
                'Communicate with the Seller’s Agent or Seller to confirm availability, purchase terms, and showing instructions',
                'Schedule and attend property showings with the Buyer',
                'Coordinate or conduct virtual showings via live video or recorded walkthroughs',
                'Preview properties on behalf of the Buyer upon request',
                'Draft and submit offers using state-approved purchase agreements or Letters of Intent (LOIs)',
                'Provide the Buyer with the necessary disclosure forms required by state or local law',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Negotiate price, deposit structure, timelines, and contingencies with the Seller or Seller’s Agent',
                'Manage communication with the Seller’s Agent or Seller',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Assist with due diligence negotiations, including repair requests or credits',
                'Monitor contract contingencies, including financing, estoppel review, lease audits, and environmental reports',
                'Coordinate inspections, appraisals, environmental assessments, and estoppel certificate collection as needed',
                'Review and request due diligence documentation such as lease agreements, estoppel certificates, rent rolls, utility summaries, and operating expense breakdowns (as available)',
                'Coordinate with the Lender, Title Company, Escrow Officer, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement for accuracy and coordinate with all parties if corrections are needed (no legal or financial advice provided)',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Provide a Comparative Market Analysis (CMA) with recent sales comps, lease comps, and an estimated value range (for informational purposes only — not a formal appraisal)',
                'Answer general questions about zoning regulations, permitted uses, and rental income potential',
                'Provide factual data on traffic counts, commercial market trends, and area demographics using third-party sources (no personal opinions or steering)',
            ],
            'business' => [
                'Create a branded flyer summarizing the Buyer’s purchase criteria',
                'Post the Buyer’s purchase criteria on Craigslist under “Business for Sale” or “Real Estate Wanted – Commercial”',
                'Promote the Buyer’s purchase criteria on Facebook in Business Opportunity or Franchise Groups',
                'Share the Buyer’s purchase criteria on Instagram using posts, stories, or reels',
                'Promote the Buyer’s purchase criteria on LinkedIn in Business, Commercial, or Startup Groups',
                'Upload a TikTok video summarizing the Buyer’s purchase criteria',
                'Upload a YouTube video summarizing the Buyer’s purchase criteria',
                'Launch a mass email campaign promoting the Buyer’s purchase criteria',
                'Distribute branded postcards or flyers in the Buyer’s preferred neighborhoods',
                'Send alerts for businesses that match the Buyer’s acquisition criteria from MLS, BizBuySell, or other listing platforms',
                'Search for off-market, pre-market, distressed, or recently closed businesses that meet the Buyer’s criteria',
                'Communicate with the Seller’s Broker or Seller to confirm pricing, lease terms, licensing status, and showing availability',
                'Schedule and attend property or business showings with the Buyer',
                'Coordinate or conduct virtual showings via live video or pre-recorded walkthroughs',
                'Preview properties or business locations on behalf of the Buyer upon request',
                'Draft and submit offers using appropriate business purchase or asset sale forms',
                'Provide the Buyer with required disclosures, financial summaries, and documentation made available by the Seller',
                'Negotiate terms such as purchase price, deposit structure, inventory inclusions, non-compete agreements, and contingencies',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Manage communication with the Seller’s Broker or Seller',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Assist with due diligence coordination, Buyer-requested repairs, and adjustment negotiations',
                'Monitor contingency periods, financing milestones, and deal approval timelines',
                'Coordinate inspections, licensing verifications, lease assignments, and inventory counts',
                'Coordinate with Lenders, Attorneys, Escrow Officers, Title Companies, CPAs, and other involved parties to prepare for Closing',
                'Review the Settlement Statement or Closing Worksheet for accuracy and coordinate with all parties if corrections are needed (no legal or financial advice provided)',
                'Confirm delivery of final executed documents, wire instructions, and business transition materials',
                'Schedule and confirm the Final Walkthrough',
                'Provide a Comparative Market Review based on similar business sales, financial performance, and industry benchmarks (for informational purposes only — not a formal appraisal or valuation)',
                'Answer general questions about licensing, zoning, SBA financing, registration steps, and transition timing (non-legal guidance)',
            ],
            'vacant_land' => [
                'Create a branded flyer summarizing the Buyer’s purchase criteria',
                'Post the Buyer’s criteria on Craigslist under “Real Estate Wanted – Land”',
                'Share the Buyer’s criteria on Nextdoor in Neighborhood or Rural Groups',
                'Promote the Buyer’s criteria on Facebook in Land Buyers, Developers, or Homesteader Groups',
                'Share the Buyer’s criteria on Instagram using posts, stories, or reels',
                'Promote the Buyer’s criteria on LinkedIn in Land Acquisition or Investment Groups',
                'Upload a TikTok video summarizing the Buyer’s purchase criteria',
                'Upload a YouTube video summarizing the Buyer’s purchase criteria',
                'Launch a mass email campaign promoting the Buyer’s purchase criteria',
                'Distribute branded postcards or flyers in the Buyer’s preferred neighborhoods',
                'Send property alerts for land listings that match the Buyer’s goals from MLS and land-specific platforms',
                'Search for off-market, pre-market, distressed, withdrawn, canceled, or expired properties that meet the Buyer’s purchase criteria',
                'Communicate with the Seller’s Agent or Seller to confirm zoning, access, utilities, and pricing',
                'Schedule and attend land visits with the Buyer',
                'Coordinate or conduct virtual walkthroughs using maps, aerials, and site photos',
                'Preview parcels on behalf of the Buyer upon request',
                'Draft and submit offers using state-approved purchase forms',
                'Provide the Buyer with required state or local disclosure forms',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Negotiate price, deposits, and contingencies (as permitted under the agency agreement)',
                'Manage communication with the Seller’s Agent or Seller',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed documents to all parties',
                'Assist with due diligence coordination, including survey review, soil testing, zoning checks, and permit verification (non-legal guidance only)',
                'Monitor contract milestones, contingency deadlines, and financing timelines',
                'Coordinate surveys, appraisals, inspections, and environmental assessments',
                'Coordinate with the Lender, Title Company, Escrow Officer, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement for accuracy and coordinate with all parties if corrections are needed (no legal or financial advice provided)',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Provide a Comparative Market Analysis (CMA) based on recent land sales, acreage comps, and price-per-acre benchmarks (for informational purposes only — not a formal appraisal)',
                'Answer general questions about zoning, utilities, development potential, and environmental constraints (non-legal guidance only)',
                'Provide factual data on flood zones, wetlands, and land use maps using third-party sources (no legal or engineering advice)',
            ],
        ];
    }

    // ── SELLER ───────────────────────────────────────────────────────────────

    protected static function sellerCatalog(): array
    {
        return [
            'residential' => [
                'List the property on the local Multiple Listing Service (MLS)',
                'Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)',
                'Create a branded flyer featuring the property’s key highlights',
                'Post the property on Facebook Marketplace',
                'Post the property on Craigslist under the “Homes for Sale” category',
                'Share the listing on Nextdoor in Neighborhood or Community Groups',
                'Promote the listing on Facebook in Real Estate or Community Groups',
                'Share the listing on Instagram using posts, stories, or reels',
                'Promote the listing on LinkedIn in Professional or Real Estate Groups',
                'Upload a TikTok video walkthrough of the property',
                'Upload a YouTube video walkthrough of the property',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
                'Conduct a property walkthrough and provide recommendations for listing readiness',
                'Provide a custom listing preparation checklist',
                'Collect property details and prepare MLS remarks and a public listing description',
                'Provide a visual consultation for interior layout, cleanliness, and presentation',
                'Provide a curb appeal consultation focused on exterior presentation',
                'Provide referrals to third-party vendors (e.g., cleaners, handypeople, electricians, landscapers). Vendor fees billed separately. Referrals only — no endorsement or warranty is made',
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide virtual staging (digital enhancements only; no physical staging)',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
                'Ensure proper notice is provided if the property is occupied',
                'Install a real estate sign on the property',
                'Install a lockbox for Agent access',
                'Schedule and attend showings with prospective Buyers',
                'Coordinate showings with Buyer’s Agents',
                'Collect and relay showing feedback to the Seller',
                'Present all offers to the Seller and summarize key terms, pricing, and contingencies',
                'Provide the Seller with the necessary disclosure forms required by state or local law',
                'Negotiate price, terms, and contingencies with the Buyer’s Agent or Buyer',
                'Manage communications with the Buyer’s Agent or Buyer',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Assist with inspection-related negotiations and Buyer requests for repairs',
                'Monitor contract milestones, contingency periods, and financing deadlines',
                'Provide referrals to Attorneys, Title Companies, and Escrow Professionals (referrals only — no endorsement or warranty is made)',
                'Coordinate scheduling for inspections, appraisals, and other requested evaluations',
                'Coordinate with the Buyer’s Agent, Lender, Title, Escrow, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement and coordinate with all parties if corrections are needed',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Schedule and confirm the Closing Appointment',
                'Provide a Comparative Market Analysis (CMA) with pricing recommendations based on comparable sales, neighborhood trends, and current market conditions',
                'Provide general insight on local market trends, seasonal timing, and pricing thresholds',
                'Recommend adjustments to pricing or marketing strategy if the property is not receiving sufficient interest',
            ],
            'income' => [
                'List the property on the local Multiple Listing Service (MLS)',
                'Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)',
                'List the property on Crexi.com',
                'List the property on LoopNet.com',
                'Create a branded flyer with key rental data (e.g., unit mix, gross income, occupancy)',
                'Post the property on Craigslist under the “Multi-Family for Sale” category',
                'Share the listing on Nextdoor in Neighborhood or Community Groups',
                'Promote the listing on Facebook in Real Estate Investor or Multi-Family Buyer Groups',
                'Share the listing on Instagram using posts, stories, or reels',
                'Promote the listing on LinkedIn in Investment or Real Estate Groups',
                'Upload a TikTok video walkthrough of the property',
                'Upload a YouTube video walkthrough of the property',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
                'Conduct a property walkthrough and provide recommendations for listing readiness',
                'Provide a custom listing preparation checklist',
                'Assist with assembling an income property packet, including rent roll, lease copies, and an income/expense summary (as available)',
                'Provide a visual consultation focused on interior layout, cleanliness, and unit presentation',
                'Provide a curb appeal consultation focused on exterior maintenance and first impressions',
                'Provide referrals to third-party vendors (e.g., cleaners, handypeople, electricians, landscapers). Vendor fees billed separately. Referrals only — no endorsement or warranty is made',
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide virtual staging (digital enhancements only; no physical staging)',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
                'Schedule and host Buyer showings (with appropriate Tenant notice)',
                'Host Broker tours',
                'Install a lockbox for Agent access',
                'Track showing activity and collect Buyer or Agent feedback',
                'Assist with Tenant communication and showing logistics (administrative only)',
                'Respond to Buyer inquiries and screen for general qualifications',
                'Provide Non-Disclosure Agreement (NDA) templates for confidential showings or document access',
                'Ensure proper notice is provided if the property is occupied',
                'Install a real estate sign on the property',
                'Schedule and attend showings with prospective Buyers',
                'Coordinate showings with Buyer’s Agents',
                'Collect and relay showing feedback to the Seller',
                'Present all offers to the Seller and summarize key terms, pricing, and contingencies',
                'Provide the Seller with the necessary disclosure forms required by state or local law',
                'Negotiate deal structure, deposits, due diligence timelines, and Buyer contingencies',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Manage communication with the Buyer’s Agent or Buyers',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Assist with inspection-related negotiations and Buyer requests for repairs',
                'Monitor contract contingencies, including financing, lease audits, estoppel review, insurance, inspections, and environmental reports',
                'Provide referrals to Attorneys, Title Companies, Escrow Officers, or 1031 Exchange Professionals. Referrals only — no endorsement or warranty is made',
                'Review and organize due diligence documentation such as lease agreements, estoppel certificates, rent rolls, utility summaries, and operating expense breakdowns (as available)',
                'Coordinate with the Buyer’s Agent, Buyer’s Lender, Title, Escrow, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement for accuracy and coordinate with relevant parties if corrections are needed',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Schedule and confirm the Closing Appointment',
                'Provide a Comparative Market Analysis (CMA) with pricing insights based on recent income property sales, rental income trends, unit mix, and local investor activity',
                'Provide general insight on likely Investor Buyer behavior, common value drivers, and investment strategies',
                'Recommend adjustments to pricing or marketing strategy if the property is not receiving sufficient interest',
                'Provide general guidance on lease transfers, rent proration, security deposits, and possession timelines',
            ],
            'commercial' => [
                'List the property on the local Multiple Listing Service (MLS)',
                'List the property on Crexi.com',
                'List the property on LoopNet.com',
                'Create a branded flyer summarizing the property’s investment highlights and key selling points',
                'Post the property on Craigslist under the “Commercial for Sale” category',
                'Promote the listing on Facebook in Commercial or Investor Real Estate Groups',
                'Share the listing on Instagram using posts, stories, or reels',
                'Promote the listing on LinkedIn in Professional, Real Estate, or Commercial Investment Groups',
                'Upload a TikTok video walkthrough of the property',
                'Upload a YouTube video walkthrough of the property',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
                'Conduct a property walkthrough and provide recommendations for listing readiness',
                'Provide a visual consultation on interior layout, cleanliness, and overall presentation',
                'Provide a curb appeal consultation focused on exterior appearance and first impressions',
                'Provide referrals to third-party vendors such as cleaners, handypeople, electricians, and landscapers (vendor fees billed separately; referrals only — no endorsement or warranty is made)',
                'Compile essential marketing materials such as rent rolls, lease summaries, financial statements, and operating data (as available)',
                'Organize zoning documentation, surveys, and public record reports (as available)',
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide virtual staging (digital enhancements only; no physical staging)',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
                'Respond to Buyer inquiries and screen for general qualifications',
                'Provide Non-Disclosure Agreement (NDA) templates for access to confidential documents or showings',
                'Ensure proper notice is provided if the property is occupied',
                'Install a real estate sign on the property',
                'Install a lockbox for Agent access',
                'Schedule and attend showings with prospective Buyers',
                'Coordinate showings with Buyer’s Agents',
                'Collect and relay showing feedback to the Seller',
                'Present all offers to the Seller and summarize key terms, pricing, and contingencies',
                'Provide the Seller with the necessary disclosure forms required by state or local law',
                'Coordinate Letter of Intent (LOI) submissions, counteroffers, and contract revisions',
                'Negotiate deal terms such as pricing, deposit structure, closing timelines, and due diligence periods',
                'Manage communication with the Buyer’s Agent or Buyer',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Assist with inspection-related negotiations and Buyer requests for repairs or credits',
                'Monitor contract contingencies, including financing, estoppel review, lease audits, and environmental reports',
                'Provide referrals to Attorneys, Title Companies, Escrow Officers, or 1031 Exchange Professionals (referrals only — no endorsement or warranty is made)',
                'Coordinate inspections, appraisals, and estoppel certificate delivery with the Buyer’s Agent or Buyer, as applicable',
                'Provide due diligence documentation such as lease agreements, estoppel certificates, rent rolls, utility summaries, and operating expense breakdowns (as available)',
                'Coordinate with the Buyer’s Agent, Lender, Title, Escrow, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement and coordinate with all parties if corrections are needed',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Schedule and confirm the Closing Appointment',
                'Provide a Comparative Market Analysis (CMA) with recent commercial sales comps, cap rate estimates, and an estimated value range (for informational purposes only — not a formal appraisal)',
                'Provide general insight on local commercial market trends, vacancy rates, and Buyer activity',
                'Recommend adjustments to pricing or marketing strategy if the property is not receiving sufficient interest',
            ],
            'business' => [
                'List the Business Opportunity on the local Multiple Listing Service (MLS)',
                'List the Business Opportunity on Crexi.com',
                'List the Business Opportunity on BizBuySell.com',
                'Promote the listing on LinkedIn in Business Acquisition, Startup, or Investor Groups',
                'Upload a TikTok video summarizing the Business Opportunity',
                'Upload a YouTube video summarizing the Business Opportunity',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
                'Conduct a preliminary Seller consultation to gather details about the Business’s operations, assets, and goals',
                'Provide a business sale checklist to collect financials, licenses, lease terms, and key operational details',
                'Assist with preparing a non-confidential teaser or executive summary for marketing purposes',
                'Organize internal documentation such as profit and loss statements, balance sheets, FF&E summaries, inventory lists, and staffing overviews (as available)',
                'Refer third-party professionals such as valuation experts, accountants, or financial consultants, if requested (referrals only — no endorsement or warranty is made)',
                'Compile essential marketing materials including business overviews, location descriptions, asset lists, and financial summaries',
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
                'Respond to Buyer inquiries and screen for general qualifications',
                'Provide Non-Disclosure Agreement (NDA) templates for confidential showings or document access',
                'Ensure proper notice is provided if the property or business premises is occupied',
                'Install a real estate sign on the property',
                'Install a lockbox for Agent access',
                'Schedule and attend showings with prospective Buyers',
                'Coordinate showings with Buyer’s Agents',
                'Coordinate directly with Tenant(s) or business staff to arrange access for showings',
                'Collect and relay showing feedback to the Seller',
                'Present all Letters of Intent (LOIs) or formal offers to the Seller and summarize key deal terms',
                'Provide the Seller with the necessary disclosure forms required by state or local law',
                'Negotiate deal terms such as purchase price, deposit structure, contingencies, transition period, and asset allocation',
                'Coordinate revisions, counteroffers, and ongoing communication with the Buyer or their representatives',
                'Manage communication with the Buyer’s Broker or Buyer',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Monitor contract contingencies and organize delivery of due diligence materials such as leases, vendor contracts, tax filings, and financial statements',
                'Refer the Seller to legal counsel for formal contract drafting and execution (referrals only — no legal advice provided)',
                'Provide referrals to Business Attorneys, Escrow Officers, or Business Transfer Specialists (referrals only — no endorsement or warranty is made)',
                'Coordinate Buyer inspections, management interviews, and site visits as applicable',
                'Provide a transaction checklist and track key deadlines throughout the escrow period',
                'Coordinate with the Buyer’s Attorney, Escrow Officer, or designated Closing Facilitator',
                'Review the Settlement Statement and coordinate corrections with relevant parties',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Schedule and confirm the Closing Appointment',
                'Provide a Comparative Market Review based on similar business sales, financial performance, and industry benchmarks (for informational purposes only — not a formal appraisal or valuation)',
                'Provide general insight on likely Buyer profiles, business value drivers, and market demand',
                'Recommend adjustments to marketing strategy or asking price if the listing is not generating sufficient interest',
            ],
            'vacant_land' => [
                'List the property in the local Multiple Listing Service (MLS)',
                'Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)',
                'List the property on LandWatch.com',
                'List the property on Land.com',
                'List the property on LandAndFarm.com',
                'Create a branded flyer highlighting lot features, zoning, and potential use',
                'Post the listing on Facebook Marketplace',
                'Post the listing on Craigslist under the “Land for Sale” category',
                'Share the listing on Nextdoor in Neighborhood or Rural Groups',
                'Promote the listing on Facebook in Land Buyers, Developers, or Homesteader Groups',
                'Share the listing on Instagram using posts, stories, or reels',
                'Promote the listing on LinkedIn in Land Acquisition or Investment Groups',
                'Upload a TikTok video summarizing the land opportunity',
                'Upload a YouTube video summarizing the land opportunity (e.g., drone tour, narrated overview)',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
                'Provide a checklist to gather parcel data (e.g., APN, lot size, zoning, utilities, and access)',
                'Assist with collecting public records, flood zone data, and land use information (as available)',
                'Provide referrals to surveyors, soil testers, or land service professionals (referrals only — no endorsement or warranty is made)',
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video overview or narrated walkthrough',
                'Provide a 3D virtual tour (if applicable)',
                'Provide digital enhancements to media assets',
                'Provide a parcel map, topographical image, or plot plan (non-certified; for marketing purposes only)',
                'Install a real estate sign on the property',
                'Schedule and attend showings with prospective Buyers',
                'Coordinate showings with Buyer’s Agents',
                'Collect and relay showing feedback to the Seller',
                'Present all offers to the Seller and summarize key terms, pricing, and contingencies',
                'Provide the Seller with the necessary disclosure forms required by state or local law',
                'Negotiate price, due diligence timelines, and closing terms',
                'Draft and deliver counteroffers and manage revisions to the purchase agreement',
                'Manage communication with the Buyer’s Agent or Buyer',
                'Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties',
                'Monitor contract contingencies, including survey, zoning verification, financing, and environmental reviews',
                'Provide referrals to Attorneys, Title Companies, Escrow Officers, or Land Use Professionals (referrals only — no endorsement or warranty is made)',
                'Coordinate surveys, site visits, or environmental access with the Buyer or Buyer’s Agent, as applicable',
                'Coordinate with Title, Escrow, and/or Attorney to prepare for Closing',
                'Review the Settlement Statement and coordinate with all parties if corrections are needed',
                'Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties',
                'Schedule and confirm the Final Walkthrough',
                'Schedule and confirm the Closing Appointment',
                'Provide a Comparative Market Analysis (CMA) with pricing recommendations based on recent land sales, zoning categories, and location-based trends',
            ],
        ];
    }

    // ── TENANT ───────────────────────────────────────────────────────────────

    protected static function tenantCatalog(): array
    {
        return [
            'residential' => [
                'Create a branded flyer summarizing the Tenant’s rental criteria',
                'Post the Tenant’s rental criteria on Craigslist under the “Real Estate Wanted” section',
                'Share the Tenant’s rental criteria on Nextdoor in Neighborhood or Community Groups',
                'Promote the Tenant’s rental criteria on Facebook in Rental or Housing Groups',
                'Share the Tenant’s rental criteria on Instagram using posts, stories, or reels',
                'Promote the Tenant’s rental criteria on LinkedIn in Real Estate or Housing Groups',
                'Upload a TikTok video summarizing the Tenant’s rental criteria',
                'Upload a YouTube video summarizing the Tenant’s rental criteria',
                'Launch a mass email campaign promoting the Tenant’s rental criteria',
                'Distribute branded postcards or flyers in the Tenant’s preferred neighborhoods',
                'Send email alerts with new listings from the MLS that match the Tenant’s rental criteria',
                'Search for off-market, pre-market, withdrawn, canceled, or expired properties that meet the Tenant’s rental criteria',
                'Communicate with the Landlord’s Agent, Landlord, or Property Manager to confirm availability, lease terms, and showing instructions',
                'Schedule and attend property showings with the Tenant',
                'Coordinate or conduct virtual showings via live video or pre-recorded walkthroughs',
                'Preview properties on behalf of the Tenant upon request',
                'Provide the Tenant with application instructions or links to an online rental application platform',
                'Gather and organize required supporting documents (e.g., identification, income verification, reference letters)',
                'Submit complete and organized application packages to the Landlord’s Agent, Landlord, or Property Manager for review',
                'Review lease offers and assist the Tenant in preparing questions or requested changes',
                'Coordinate lease negotiation with the Landlord’s Agent, Landlord, or Property Manager',
                'Assist with completing required lease disclosures and reviewing key lease terms',
                'Assist with in-person or electronic lease signing, including e-signature setup and secure delivery of executed lease documents, addenda, and disclosures to all parties',
                'Coordinate move-in date and key handoff logistics with the Landlord’s Agent, Landlord or Property Manager',
                'Confirm completion of any agreed-upon pre-move-in cleaning or repairs',
                'Provide a utility setup checklist and local provider resources',
                'Share a move-in checklist for documentation and property condition review',
                'Provide a Rental Market Analysis (RMA) with pricing insights based on comparable rentals, neighborhood trends, and current market conditions',
                'Advise on lease types and structures (e.g., month-to-month, annual, furnished, lease-option)',
                'Provide general guidance on Tenant rights and Landlord responsibilities under state law',
                'Provide general guidance on lease clauses, payment terms, and renewal options',
            ],
            'commercial' => [
                'Create a branded flyer summarizing the Tenant’s leasing criteria',
                'Post the Tenant’s leasing criteria on Craigslist under the “Office/Commercial” or “Retail” section',
                'Promote the Tenant’s leasing criteria on Facebook in Commercial Leasing or Business Groups',
                'Share the Tenant’s leasing criteria on Instagram using posts, stories, or reels',
                'Promote the Tenant’s leasing criteria on LinkedIn in Professional, Real Estate, or Commercial Investment Groups',
                'Upload a TikTok video summarizing the Tenant’s leasing criteria',
                'Upload a YouTube video summarizing the Tenant’s leasing criteria',
                'Launch a mass email campaign promoting the Tenant’s leasing criteria',
                'Distribute branded postcards or flyers in the Tenant’s preferred neighborhoods',
                'Send listing alerts from real estate platforms that match the Tenant’s leasing criteria',
                'Search for off-market, pre-market, withdrawn, canceled, or expired properties that meet the Tenant’s rental criteria',
                'Communicate with the Landlord’s Agent, Landlord, or Property Manager to confirm availability, lease terms, and showing instructions',
                'Schedule and attend property tours with the Tenant',
                'Coordinate or conduct virtual showings via live video or pre-recorded walkthroughs',
                'Preview properties on behalf of the Tenant upon request',
                'Provide the Tenant with application instructions or links to online platforms',
                'Gather and organize required supporting documents (e.g., business licenses, financials, references)',
                'Draft or assist with preparing a Letter of Intent (LOI) summarizing the Tenant’s business needs and proposed terms',
                'Assist with negotiating rent, CAM, lease term, TI allowance, exclusivity clauses, renewal options, and other provisions (as permitted under the agency agreement)',
                'Coordinate with the Landlord’s Agent, Landlord or Property Manager to finalize lease terms',
                'Review lease drafts and coordinate revisions through appropriate channels',
                'Assist with in-person or electronic lease signing, including e-signature setup and secure delivery of executed lease documents, addenda, and disclosures to all parties',
                'Coordinate move-in date and key handoff logistics with the Landlord, Landlord’s Agent, or Property Manager',
                'Confirm completion of any agreed-upon pre-move-in repairs, cleaning, or buildout',
                'Provide a utility setup checklist and local provider resources',
                'Share a move-in checklist for documentation and property condition review',
                'Provide a Comparative Lease Market Analysis (CLMA) with pricing insights, comps, and vacancy trends',
                'Advise on lease types and structures (e.g., NNN, Modified Gross, Full Service) with general explanations of differences',
                'Provide general guidance on Tenant rights and Landlord responsibilities under commercial leasing law',
                'Provide general guidance on lease clauses, escalation terms, and space usage considerations',
            ],
        ];
    }

    // ── LANDLORD ─────────────────────────────────────────────────────────────

    protected static function landlordCatalog(): array
    {
        return [
            'residential' => [
                'List the property on the local Multiple Listing Service (MLS)',
                'Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)',
                'Create a branded flyer featuring the property’s key highlights',
                'Post the property on Facebook Marketplace',
                'Post the property on Craigslist in the appropriate “Homes for Rent” category',
                'Share the listing on Nextdoor in Neighborhood or Community Groups',
                'Promote the listing on Facebook in Housing or Rental Groups',
                'Share the listing on Instagram using posts, stories, or reels',
                'Promote the listing on LinkedIn in Professional or Real Estate Groups',
                'Upload a TikTok video walkthrough of the property',
                'Upload a YouTube video walkthrough of the property',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
                'Conduct a property walkthrough and provide recommendations for listing readiness',
                'Provide a custom listing preparation checklist',
                'Collect property details and prepare MLS remarks and a public listing description',
                'Provide a visual consultation for interior layout, cleanliness, and presentation',
                'Provide a curb appeal consultation focused on exterior presentation',
                'Provide referrals to third-party vendors (e.g., cleaners, handypeople, electricians, landscapers). Vendor fees billed separately. Referrals only — no endorsement or warranty is made',
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide virtual staging (digital enhancements only; no physical staging)',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
                'Ensure proper notice is given if the property is occupied',
                'Install a real estate sign on the property',
                'Install a lockbox for Agent access',
                'Schedule and attend showings with prospective Tenants',
                'Coordinate showings with Tenant’s Agents',
                'Collect and relay feedback to the Landlord after showings',
                'Provide a link to an online application platform with third-party screening tools (e.g., credit, background, and eviction checks)',
                'Ensure compliance with Fair Housing laws and screening regulations throughout the application process',
                'Collect and organize application documents submitted by prospective Tenants',
                'Verify basic information provided in the application (e.g., employment, income, and references)',
                'Present complete and organized application packages to the Landlord for review and final selection',
                'Review lease offers submitted by prospective Tenants and summarize key terms',
                'Coordinate lease negotiation with the Tenant or Tenant’s Agent',
                'Prepare a state-specific lease agreement using approved forms or templates',
                'Assist with completing required lease disclosures and reviewing key lease terms',
                'Assist with in-person or electronic lease signing, including e-signature setup and secure delivery of executed lease documents, addenda, and disclosures to all parties',
                'Confirm receipt of required move-in funds and assist the Landlord in verifying amounts due, payment deadlines, and accepted payment methods',
                'Coordinate move-in date and key handoff logistics with the Tenant or Tenant’s Agent',
                'Confirm completion of any agreed-upon pre-move-in cleaning or repairs',
                'Verify receipt of all required move-in funds prior to occupancy (e.g., deposit, rent, pet fees)',
                'Provide a utility setup checklist and local provider resources for the Tenant',
                'Share a move-in checklist for documentation and property condition review',
                'Provide ongoing property management services throughout the lease term (rent collection, maintenance coordination, Tenant communications, lease enforcement, renewals, etc.)',
                'Provide a Rental Market Analysis (RMA) with pricing insights based on comparable rentals, neighborhood trends, and current market conditions',
                'Advise on lease types and structures (e.g., month-to-month, annual, furnished, corporate, lease-option)',
                'Provide general guidance on Landlord obligations and Tenant rights under state law',
                'Provide general guidance on rental demand, local market conditions, and Tenant expectations',
            ],
            'commercial' => [
                'List the property on the local Multiple Listing Service (MLS)',
                'List the property on Crexi.com',
                'List the property on LoopNet.com',
                'Create a branded flyer featuring the property’s key highlights',
                'Post the property on Craigslist under the “Office/Commercial” category',
                'Promote the listing on Facebook in Commercial Leasing or Business Startup Groups',
                'Share the listing on Instagram using photos, stories, or reels',
                'Promote the listing on LinkedIn in Professional, Real Estate, or Commercial Investment Groups',
                'Upload a TikTok video walkthrough of the property',
                'Upload a YouTube video walkthrough of the property',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
                'Conduct a property walkthrough and provide recommendations for listing readiness',
                'Provide a custom listing preparation checklist',
                'Collect property details such as lease terms, square footage, property features, and allowable uses',
                'Prepare a marketing packet including zoning, cap rate references, and permitted uses',
                'Provide a visual consultation focused on interior layout, cleanliness, and presentation',
                'Provide a curb appeal consultation for exterior appearance and signage opportunities',
                'Provide referrals to third-party vendors (e.g., cleaners, sign installers, minor repair vendors). Vendor fees billed separately. Referrals only — no endorsement or warranty is made',
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide virtual staging (digital enhancements only; no physical staging)',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
                'Ensure proper notice is given if the property is occupied',
                'Install a real estate sign on the property',
                'Install a lockbox for Agent access',
                'Schedule and attend showings with prospective Tenants',
                'Coordinate showings with Tenant’s Agents',
                'Collect and relay showing feedback to the Landlord',
                'Provide a link to an online application platform or share instructions with prospective Tenants or Tenant’s Agents',
                'Ensure compliance with applicable federal, state, and local commercial leasing and anti-discrimination laws',
                'Collect and organize application documents (e.g., business licenses, financials, entity records, references)',
                'Verify basic information provided in the application (e.g., business operations, income sources, references)',
                'Present complete application packages to the Landlord for review and final selection',
                'Coordinate lease negotiation with the Tenant or Tenant’s Agent',
                'Collect and organize Letters of Intent (LOIs) or draft lease proposals',
                'Draft or assist with execution of the final lease agreement using approved forms or templates',
                'Provide and review required lease disclosures and addenda based on state or municipal requirements',
                'Assist with in-person or electronic lease signing, including e-signature setup and secure delivery of executed lease documents, addenda, and disclosures to all parties',
                'Verify receipt of required deposits and track rent commencement and key lease dates to ensure move-in readiness',
                'Coordinate move-in date and key handoff logistics with the Tenant or Tenant’s Agent',
                'Confirm completion of any agreed-upon pre-move-in repairs, cleaning, or improvements',
                'Verify receipt of all required move-in funds and documents prior to occupancy (e.g., rent, security deposit, insurance certificates)',
                'Provide a utility setup checklist and local provider resources for the Tenant',
                'Share a move-in checklist for documentation and property condition review',
                'Assist with coordination of move-in logistics, including Certificate of Insurance (COI) and vendor access (as agreed)',
                'Provide ongoing property management services throughout the lease term (rent collection, maintenance coordination, Tenant communications, lease enforcement, renewals, etc.)',
                'Provide a Comparable Lease Analysis with pricing recommendations based on similar properties, local vacancy trends, and current market conditions',
                'Advise on lease types and structures (e.g., NNN, Modified Gross, Full Service) with general explanations of differences',
                'Provide general guidance on Landlord obligations and Tenant rights under applicable commercial leasing laws',
                'Provide general guidance on zoning, permitted uses, occupancy standards, or rent escalation terms',
            ],
        ];
    }
}
