<?php

namespace App\Exports\ListingFieldMaps;

class LandlordFieldMap
{
    public static function sections(): array
    {
        return [
            'Listing Details' => [
                'Service Type' => 'service_type',
                'Listing Status' => 'listing_status',
                'Listing Type' => 'auction_type',
                'Currently Working with an Agent?' => 'working_with_agent',
                'Listing Date' => 'listing_date',
                'Desired Agent Hire Date' => 'desired_agent_hire_date',
                'Expiration Date' => 'expiration_date',
                'Auction Length' => 'auction_time',
                'Agent Bid Visibility' => 'agent_bid_visibility',
            ],

            'Location' => [
                'Property Address' => 'address',
                'City' => 'property_city',
                'County' => 'property_county',
                'State' => 'property_state',
                'ZIP Code' => 'property_zip',
                'Acceptable Cities' => 'cities',
                'Acceptable Counties' => 'counties',
                'Acceptable ZIP Codes' => 'zipCodes',
            ],

            'Property Details' => [
                'Property Type' => 'property_type',
                'Property Style' => 'property_items',
                'Leasing Space' => 'leasing_space',
                'Property Condition' => 'condition_prop',
                'Bedrooms' => 'bedrooms',
                'Bathrooms' => 'bathrooms',
                'Minimum Heated Sq Ft' => 'minimum_heated_square',
                'Minimum Leaseable Sq Ft' => 'minimum_leaseable',
                'Total Square Feet' => 'total_square_feet',
                'Sq Ft Heated Source' => 'sqft_heated_source',
                'Minimum Acreage' => 'min_acreage',
                'Total Acreage' => 'total_acreage',
                'Appliances' => 'appliances',
                'Property Criteria' => 'property_criteria',
                'Unit Size' => 'unit_size',
                'Preference Details' => 'preferance_details',
            ],

            'Income & Investment Metrics' => [
                'Minimum Annual Net Income' => 'minimum_annual_net_income',
                'Minimum Cap Rate' => 'minimum_cap_rate',
                'Included Assets' => 'assets',
            ],

            'Leasing Terms' => [
                'Occupant Status' => 'occupant_status',
                'Occupant Types' => 'occupant_types',
                'Occupant (Tenant)' => 'occupant_tenant',
                'Leasing Space (Property)' => 'leasing_space_property',
                'Leasing Spaces' => 'leasing_spaces',
                'Desired Rental Amount' => 'desired_rental_amount',
                'Desired Rental Amount (Tenant)' => 'desired_rental_amount_tenant',
                'Lease Amount Frequency' => 'lease_amount_frequency',
                'Desired Lease Length' => 'desired_lease_length',
                'Custom Lease Term' => 'custom_lease_term',
                'Terms of Lease' => 'terms_of_lease',
                'Rent Includes' => 'rent_includes',
                'Tenant Responsible For' => 'tenant_pays',
                'Owner Responsible For' => 'owner_pays',
                'Restrictions' => 'restrictions',
                'Maintenance By' => 'maintenance_by',
                'Maintenance Response Time' => 'maintenance_response_time',
            ],

            'Commercial Property Details' => [
                'Building Hours' => 'building_hours',
                'Access 24/7' => 'access_24_7',
                'Bathroom Facilities' => 'bathroom_facilities',
                'Room Size' => 'room_size',
                'Zoning Allows' => 'zoning_allows',
                'Space Features' => 'space_features',
                'Neighboring Tenants' => 'neighboring_tenants',
                'Shared Amenities' => 'shared_amenities',
                'Common Areas Access' => 'common_areas_access',
                'Common Areas Cleaning' => 'common_areas_cleaning',
                'Utilities' => 'utilities',
            ],

            'Storage' => [
                'Storage Space' => 'storage_space',
                'Included Storage (Residential Both)' => 'included_storage_space_res_both',
                'Storage (Residential Both)' => 'storage_space_res_both',
                'Included Storage (Residential Single)' => 'included_storage_space_res_single',
                'Storage (Residential Single)' => 'storage_space_res_single',
                'Included Storage (Commercial Entire)' => 'included_storage_space_com_entire',
                'Storage (Commercial Entire)' => 'storage_space_com_entire',
                'Included Storage (Commercial Single)' => 'included_storage_space_com_single',
                'Storage (Commercial Single)' => 'storage_space_com_single',
            ],

            'Additional Property Preferences' => [
                'Tenant Requirement' => 'tenant_require',
                'Carport Needed' => 'carport_needed',
                'Garage Needed' => 'garage_needed',
                'Garage/Parking Spaces' => 'garage_parking_spaces',
                'Garage/Parking Spaces Option' => 'garage_parking_spaces_option',
                'Pool Needed' => 'pool_needed',
                'Pool Type' => 'pool_type',
                'View Preference' => 'view_preference',
                'Real Estate Purchase' => 'real_estate_purchase',
                'Number of Units' => 'number_of_unit',
                '55+ Community' => 'leasing_55_plus',
                'Guests Allowed' => 'guests_allowed',
                'Custom Enhancement' => 'custom_enhancement',
            ],

            'Pets' => [
                'Has Breed Restrictions' => 'has_breed_restrictions',
                'Breed Restrictions' => 'breed_restrictions',
                'Support Animal' => 'support_animal',
                'Breed of Pets' => 'breed_of_pets',
                'Type of Pets' => 'type_of_pets',
                'Weight of Pets' => 'weight_of_pets',
            ],

            'Sale Terms' => [
                'Sale Provision' => 'sale_provision',
                'Assignment Allowed' => 'sale_provision_assignment',
                'Assignment Fee Type' => 'assignment_fee_type',
                'Assignment Fee Amount' => 'assignment_fee_amount',
                'Buyer May Sell Contract' => 'buyer_sell_contract',
                'Interested in Selling' => 'interested_in_selling',
                'Interested in Selling Type' => 'interested_in_selling_type',
            ],

            'Budget & Financing' => [
                'Maximum Budget' => 'maximum_budget',
                'Offered Financing' => 'offered_financing',
                'Cash Budget' => 'cash_budget',
                'Pre-Approved' => 'pre_approved',
                'Pre-Approval Amount' => 'pre_approval_amount',
                'Purchase Price' => 'purchase_price',
                'Budget' => 'budget',
                'Credit Score Rating' => 'credit_scroe_rating',
                'Prior Eviction' => 'prior_eviction',
                'Eviction Explanation' => 'eviction_explanation',
            ],

            'Down Payment' => [
                'Down Payment Type' => 'down_payment_type',
                'Down Payment Amount' => 'down_payment_amount',
            ],

            'Seller Financing' => [
                'Seller Financing Type' => 'seller_financing_type',
                'Seller Financing Amount' => 'seller_financing_amount',
                'Interest Rate' => 'interest_rate',
                'Loan Duration' => 'loan_duration',
                'Prepayment Penalty' => 'prepayment_penalty',
                'Prepayment Penalty Amount' => 'prepayment_penalty_amount',
                'Balloon Payment Amount' => 'balloon_payment_amount',
                'Balloon Payment Date' => 'balloon_payment_date',
            ],

            'Assumable Loan' => [
                'Assumable Terms' => 'assumable_terms',
                'Max Assumable Rate' => 'max_assumable_rate',
            ],

            'Gap / Additional Payments' => [
                'Max Monthly Payment' => 'max_monthly_payment',
                'Gap Payment Type' => 'gap_payment_type',
                'Gap Payment Amount' => 'gap_payment_amount',
                'Additional Cash' => 'additional_cash',
            ],

            'Exchange / Trade' => [
                'Exchange Item' => 'exchange_item',
                'Exchange Item Value' => 'exchange_item_value',
                'Exchange Item Condition' => 'exchange_item_condition',
                'Value Determination' => 'value_determination',
            ],

            'Lease Option' => [
                'Interested in Lease Option Agreement' => 'interested_lease_option_agreement',
                'Lease Option Price' => 'lease_option_price',
                'Lease Option Terms' => 'lease_option_terms',
                'Lease Option Duration' => 'lease_option_duration',
                'Lease Option Payment' => 'lease_option_payment',
                'Lease Option Conditions' => 'lease_option_conditions',
                'Has Option Fee' => 'has_option_fee',
                'Option Fee Amount' => 'option_fee_amount',
            ],

            'Lease Purchase' => [
                'Lease Purchase Price' => 'lease_purchase_price',
                'Lease Purchase Terms' => 'lease_purchase_terms',
                'Lease Purchase Duration' => 'lease_purchase_duration',
                'Lease Purchase Payment' => 'lease_purchase_payment',
                'Lease Purchase Conditions' => 'lease_purchase_conditions',
                'Lease Purchase Option Fee' => 'lease_purchase_option_fee',
                'Lease Purchase Option Fee Amount' => 'lease_purchase_option_fee_amount',
            ],

            'Cryptocurrency' => [
                'Cryptocurrency Type' => 'cryptocurrency_type',
                'Crypto Percentage' => 'crypto_percentage',
                'Cash Percentage (Crypto)' => 'cash_percentage_crypto',
            ],

            'NFT' => [
                'NFT Description' => 'nft_description',
                'NFT Percentage' => 'nft_percentage',
                'Cash Percentage (NFT)' => 'cash_percentage_nft',
            ],

            'Lease Details' => [
                'Lease For' => 'lease_for',
                'Lease By' => 'lease_by',
                'Lease Date' => 'lease_date',
            ],

            'Services' => [
                'Services' => 'services',
                'Custom Services' => 'custom_services',
                'Marketing: Include Marketing Fee' => 'include_marketing_fee',
                'Marketing: Email Marketing' => 'email_marketing_fee',
                'Marketing: Email Notifications' => 'email_notifications_fee',
                'Marketing: Launch Ads' => 'launch_ads',
                'Marketing: Launch Ads Fee' => 'launch_ads_fee',
                'Marketing: Market Groups' => 'market_groups',
                'Marketing: Market Groups Fee' => 'market_groups_fee',
                'Marketing: Marketing Materials Fee' => 'marketing_materials_fee',
                'Flat Fee Services' => 'flat_fee_services',
                'Schedule Showings' => 'schedule_showings',
                'Schedule Showings Fee' => 'schedule_showings_fee',
                'Attend Showings' => 'attend_showings',
                'Attend Showings Fee' => 'attend_showings_fee',
                'Provide Virtual Tours' => 'provide_virtual_tours',
                'Virtual Tours Fee' => 'virtual_tours_fee',
                'Assist with Application' => 'assist_application',
                'Assist Application Fee' => 'assist_application_fee',
                'Collect Documents' => 'collect_documents',
                'Collect Documents Fee' => 'collect_documents_fee',
                'Submit Application' => 'submit_application',
                'Submit Application Fee' => 'submit_application_fee',
                'Review Lease' => 'review_lease',
                'Review Lease Fee' => 'review_lease_fee',
                'Provide Lease Form' => 'provide_lease_form',
                'Provide Lease Form Fee' => 'provide_lease_form_fee',
                'Coordinate Signing' => 'coordinate_signing',
                'Coordinate Signing Fee' => 'coordinate_signing_fee',
                'Move-In Inspection Fee' => 'move_in_inspection_fee',
                'Moving Resources Fee' => 'moving_resources_fee',
                'Short-Term Housing Fee' => 'short_term_housing_fee',
                'Rental Rights Fee' => 'rental_rights_fee',
                'Lease Advice Fee' => 'lease_advice_fee',
                'Neighborhood Insights Fee' => 'neighborhood_insights_fee',
                'Neighborhood Marketing Fee' => 'neighborhood_marketing_fee',
                'Neighborhood Materials Fee' => 'neighborhood_materials_fee',
                'Total Marketing Fee' => 'total_marketing_fee',
                'Total Flat Fee' => 'total_flat_fee',
            ],

            'Broker Compensation & Agency Agreement' => [
                'Commission Structure' => 'commission_structure',
                'Lease Fee Type' => 'lease_fee_type',
                'Lease Fee (Flat)' => 'lease_fee_flat',
                'Lease Fee Flat Type' => 'lease_fee_flat_type',
                'Lease Fee (%)' => 'lease_fee_percentage',
                'Lease Fee (Months)' => 'lease_fee_months',
                'Lease Fee (% of Monthly Rent)' => 'lease_fee_percentage_monthly_rent',
                'Lease Fee Flat Combo' => 'lease_fee_flat_combo',
                'Lease Fee % Combo' => 'lease_fee_percentage_combo',
                'Lease Fee Other' => 'lease_fee_other',
                'Purchase Fee Type' => 'purchase_fee_type',
                'Purchase Fee (%)' => 'purchase_fee_percentage',
                'Purchase Fee (Flat)' => 'purchase_fee_flat',
                'Purchase Fee Flat Type' => 'purchase_fee_flat_type',
                'Purchase Fee % Combo' => 'purchase_fee_percentage_combo',
                'Purchase Fee Flat Combo' => 'purchase_fee_flat_combo',
                'Purchase Fee Other' => 'purchase_fee_other',
                'Purchase Fee (Net Aggregate)' => 'purchase_fee_net_aggregate',
                'Purchase Fee Other (Commercial)' => 'purchase_fee_other_commercial',
                'Lease Option Fee Type' => 'lease_option_fee_type',
                'Lease Option Fee (Flat)' => 'lease_option_fee_flat',
                'Lease Option Fee (%)' => 'lease_option_fee_percentage',
                'Lease Option Fee Other' => 'lease_option_fee_other',
                'Landlord Broker (Flat Fee)' => 'landlord_broker_flate_fee',
                'Landlord Broker (% of Price)' => 'landlord_broker_percentage_price',
                'Landlord Broker ($ Price)' => 'landlord_broker_dollar_price',
                'Landlord Broker (Purchase Price)' => 'landlord_broker_purchase_price',
                'Landlord Broker Other' => 'landlord_broker_other',
                'Renewal Fee Type' => 'renewal_fee_type',
                'Renewal Fee (%)' => 'renewal_fee_percentage',
                'Renewal Fee Custom' => 'renewal_fee_custom',
                'Net Aggregate Rent' => 'net_aggregate_rent',
                'Month % Rent' => 'month_percentage_rent',
                'Number of Months' => 'no_of_months',
                'Flat Fee' => 'flat_fee',
                'Gross % Rent' => 'gross_percentage_rent',
                'Split Payment Due' => 'split_payment_due',
                'Broker Fee Timing' => 'broker_fee_timing',
                'Broker Fee Days After Lease' => 'broker_fee_days_after_lease',
                'Broker Fee Days After Rent' => 'broker_fee_days_after_rent',
                'Broker Fee Days From Rent' => 'broker_fee_days_from_rent',
                'Broker Fee Days After Due Event' => 'broker_fee_days_after_due_event',
                'Tenant Broker Commission Structure' => 'tenant_broker_commission_structure',
                'Tenant Broker Commission (%)' => 'tenant_broker_commission_percentage',
                'Tenant Broker Fee Structure' => 'tenant_broker_fee_structure',
                'Tenant Broker (%)' => 'tenant_broker_percentage',
                'Tenant Broker (Flat Fee)' => 'tenant_broker_flat_fee',
                'Tenant Broker (First Month Rent)' => 'tenant_broker_first_month_rent',
                'Tenant Broker (Gross Lease)' => 'tenant_broker_gross_lease',
                'Tenant Broker Other' => 'tenant_broker_other',
                'Expansion Commission Type' => 'expansion_commission_type',
                'Expansion Commission (%)' => 'expansion_commission_percentage',
                'Expansion Gross (%)' => 'expansion_gross_percentage',
                'Expansion First Month (%)' => 'expansion_first_month_percentage',
                'Expansion Flat Fee' => 'expansion_flat_fee',
                'Expansion Custom Commission' => 'expansion_custom_commission',
                'Protection Period' => 'protection_period',
                'Early Termination Fee Option' => 'early_termination_fee_option',
                'Early Termination Fee Amount' => 'early_termination_fee_amount',
                'Lease Type' => 'lease_type',
                'Lease Value' => 'lease_value',
                'Purchase Type' => 'purchase_type',
                'Purchase Value' => 'purchase_value',
                'Retainer Fee Option' => 'retainer_fee_option',
                'Retainer Fee Amount' => 'retainer_fee_amount',
                'Retainer Fee Application' => 'retainer_fee_application',
                'Agency Agreement Timeframe' => 'agency_agreement_timeframe',
                'Agency Agreement Custom' => 'agency_agreement_custom',
                'Brokerage Relationship' => 'brokerage_relationship',
            ],

            'Property Management' => [
                'Interested in Property Management' => 'interested_in_property_management',
                'Property Management Fee' => 'interested_in_property_management_fee',
                'Property Management (Flat Fee)' => 'interested_in_property_management_fee_flate_free',
                'Property Management (Gross Lease)' => 'interested_in_property_management_fee_gross_lease',
                'Property Management (Rental Period)' => 'interested_in_property_management_fee_rental_periord',
                'Property Management Other' => 'interested_in_property_management_fee_other',
            ],

            'Additional Details' => [
                'Additional Details' => 'additional_details',
                'Additional Details (Broker)' => 'additional_details_broker',
                'Video Link' => 'video_link',
            ],

            'Meeting Details' => [
                'Person Meeting' => 'person_meeting',
                'First Name' => 'meeting_details_first_name',
                'Last Name' => 'meeting_details_last_name',
                'Phone' => 'meeting_details_phone',
                'Email' => 'meeting_details_email',
                'Meeting Date' => 'meeting_details_meeting_date',
                'Meeting Time' => 'meeting_details_meeting_time',
                'Time Zone' => 'meeting_details_time_zone',
                'Meeting Instructions' => 'meeting_details_instructions',
                'Additional Meeting Details' => 'meeting_details_additional_details',
            ],

            'Contact Information' => [
                'First Name' => 'first_name',
                'Last Name' => 'last_name',
                'Phone' => 'phone_number',
                'Email' => 'email',
            ],
        ];
    }

    public static function otherPairs(): array
    {
        return [
            'property_items' => 'other_property_items',
            'condition_prop' => 'other_property_condition',
            'assets' => 'assets_other',
            'sale_provision' => 'sale_provision_other',
            'offered_financing' => 'other_financing',
            'exchange_item' => 'other_exchange_item',
            'bathrooms' => 'other_bathrooms',
            'bedrooms' => 'other_bedrooms',
            'unit_size' => 'unit_size_other',
            'carport_needed' => 'other_carport_needed',
            'garage_needed' => 'other_garage_needed',
            'garage_parking_spaces_option' => 'other_parking_space_wrapper',
            'view_preference' => 'other_preferences',
            'number_of_unit' => 'number_of_unit_other',
            'appliances' => 'appliances_other',
            'tenant_pays' => 'tenant_pays_other',
            'owner_pays' => 'owner_pays_other',
            'lease_for' => 'other_lease_for',
            'split_payment_due' => 'split_payment_due_other',
            'broker_fee_timing' => 'broker_fee_timing_other',
            'rent_includes' => 'other_rent_include',
        ];
    }
}
