<?php

namespace App\Exports\ListingFieldMaps;

class TenantFieldMap
{
    public static function sections(): array
    {
        return [
            'Listing Details' => [
                'Service Type' => 'service_type',
                'Listing Status' => 'listing_status',
                'Listing Type' => 'auction_type',
                'Currently Working with an Agent?' => 'working_with_agent',
                'Current Status' => 'current_status',
                'Listing Date' => 'listing_date',
                'Desired Agent Hire Date' => 'desired_agent_hire_date',
                'Expiration Date' => 'expiration_date',
                'Auction Length' => 'auction_time',
                'Agent Bid Visibility' => 'agent_bid_visibility',
                'Meeting Preference' => 'meeting_Preference',
            ],

            'Location' => [
                'Property Address' => 'address',
                'City' => 'property_city',
                'County' => 'property_county',
                'State' => 'property_state',
                'ZIP Code' => 'property_zip',
                'Acceptable Cities' => 'cities',
                'Acceptable Counties' => 'counties',
                'Acceptable ZIP Codes' => 'zipCodes',
            ],

            'Property Details' => [
                'Property Type' => 'property_type',
                'Property Style' => 'property_items',
                'Leasing Space' => 'leasing_space',
                'Leasing Spaces (Tenant)' => 'leasing_spaces_tenant',
                'Property Condition' => 'condition_prop',
                'Acceptable Property Condition' => 'condition_prop_buyer',
                'Business Type' => 'business_type',
                'Business Type Selected' => 'business_type_selected',
                'Bedrooms' => 'bedrooms',
                'Bathrooms' => 'bathrooms',
                'Minimum Heated Sq Ft' => 'minimum_heated_square',
                'Minimum Leaseable Sq Ft' => 'minimum_leaseable',
                'Total Square Feet' => 'total_square_feet',
                'Sq Ft Heated Source' => 'sqft_heated_source',
                'Minimum Acreage' => 'min_acreage',
                'Total Acreage' => 'total_acreage',
                'Appliances' => 'appliances',
                'Property Criteria' => 'property_criteria',
                'Unit Size' => 'unit_size',
                'Number of Units' => 'number_of_unit',
                'Number of Unit Type' => 'number_of_unit_type',
                'Unit Number' => 'unit_number',
                'Number of Buildings' => 'unit_buildings',
                'Unit Type Configurations' => 'unit_type_configurations',
                'Preference Details' => 'preferance_details',
            ],

            'Income & Investment Metrics' => [
                'Minimum Annual Net Income' => 'minimum_annual_net_income',
                'Minimum Cap Rate' => 'minimum_cap_rate',
                'Included Assets' => 'assets',
            ],

            'Leasing Terms' => [
                'Occupant Status' => 'occupant_status',
                'Occupant (Tenant)' => 'occupant_tenant',
                'Leasing Spaces' => 'leasing_spaces',
                'Desired Rental Amount' => 'desired_rental_amount',
                'Lease Amount Frequency' => 'lease_amount_frequency',
                'Desired Lease Length' => 'desired_lease_length',
                'Custom Lease Term' => 'custom_lease_term',
                'Terms of Lease' => 'terms_of_lease',
                'Rent Includes' => 'rent_includes',
                'Tenant Responsible For' => 'tenant_pays',
                'Owner Responsible For' => 'owner_pays',
                'Restrictions' => 'restrictions',
                'Maintenance By' => 'maintenance_by',
                'Maintenance Response Time' => 'maintenance_response_time',
                'Occupied Until' => 'occupied_until',
                'Occupancy Status' => 'occupancy_status',
                'Target Closing Date' => 'target_closing_date',
            ],

            'Commercial Property Details' => [
                'Building Hours' => 'building_hours',
                'Access 24/7' => 'access_24_7',
                'Bathroom Facilities' => 'bathroom_facilities',
                'Room Size' => 'room_size',
                'Zoning Allows' => 'zoning_allows',
                'Space Features' => 'space_features',
                'Neighboring Tenants' => 'neighboring_tenants',
                'Shared Amenities' => 'shared_amenities',
                'Common Areas Access' => 'common_areas_access',
                'Common Areas Cleaning' => 'common_areas_cleaning',
                'Utilities' => 'utilities',
            ],

            'Storage' => [
                'Storage Space' => 'storage_space',
                'Included Storage (Residential Both)' => 'included_storage_space_res_both',
                'Storage (Residential Both)' => 'storage_space_res_both',
                'Included Storage (Residential Single)' => 'included_storage_space_res_single',
                'Storage (Residential Single)' => 'storage_space_res_single',
                'Included Storage (Commercial Entire)' => 'included_storage_space_com_entire',
                'Storage (Commercial Entire)' => 'storage_space_com_entire',
                'Included Storage (Commercial Single)' => 'included_storage_space_com_single',
                'Storage (Commercial Single)' => 'storage_space_com_single',
            ],

            'Additional Property Preferences' => [
                'Furnishings Needed' => 'tenant_require',
                'Carport Needed' => 'carport_needed',
                'Garage Needed' => 'garage_needed',
                'Garage/Parking Spaces' => 'garage_parking_spaces',
                'Garage/Parking Spaces Option' => 'garage_parking_spaces_option',
                'Garage/Parking Spaces Option (Buyer)' => 'garage_parking_spaces_option_buyer',
                'Pool Needed' => 'pool_needed',
                'Pool Type' => 'pool_type',
                'View Preference' => 'view_preference',
                'Real Estate Purchase' => 'real_estate_purchase',
                '55+ Community' => 'leasing_55_plus',
                'Non-Negotiable Amenities' => 'non_negotiable_amenities',
                'Guests Allowed' => 'guests_allowed',
                'Custom Enhancement' => 'custom_enhancement',
            ],

            'Pets & Animals' => [
                'Pets' => 'pets',
                'Number of Pets' => 'number_of_pets',
                'Breed of Pets' => 'breed_of_pets',
                'Pet Types' => 'type_of_pets',
                'Pet Weight Limit (lbs)' => 'weight_of_pets',
                'Service Animal' => 'service_animal',
                'Other Services Enabled' => 'other_services_enabled',
                'Support Animal' => 'support_animal',
                'Emotional Support Animal' => 'emotional_support_animal',
                'Has Breed Restrictions' => 'has_breed_restrictions',
                'Breed Restrictions' => 'breed_restrictions',
            ],

            'Screening' => [
                'Screening Concerns' => 'screening_concerns',
                'Screening Concerns Explanation' => 'screening_concerns_explanation',
                'Credit Score Rating' => 'credit_scroe_rating',
                'Monthly Income' => 'monthly_income',
                'Number of Occupants' => 'number_occupant',
                'Prior Eviction' => 'prior_eviction',
                'Eviction Explanation' => 'eviction_explanation',
                'Prior Felony' => 'prior_felony',
                'Prior Felony Explanation' => 'prior_felony_explanation',
            ],

            'Sale Terms' => [
                'Sale Provision' => 'sale_provision',
                'Assignment Allowed' => 'sale_provision_assignment',
                'Assignment Fee Type' => 'assignment_fee_type',
                'Assignment Fee Amount' => 'assignment_fee_amount',
            ],

            'Budget & Financing' => [
                'Maximum Budget' => 'maximum_budget',
                'Offered Financing' => 'offered_financing',
                'Cash Budget' => 'cash_budget',
                'Pre-Approved' => 'pre_approved',
                'Pre-Approval Amount' => 'pre_approval_amount',
                'Purchase Price' => 'purchase_price',
                'Budget' => 'budget',
            ],

            'Down Payment' => [
                'Down Payment Type' => 'down_payment_type',
                'Down Payment Amount' => 'down_payment_amount',
            ],

            'Seller Financing' => [
                'Seller Financing Type' => 'seller_financing_type',
                'Seller Financing Amount' => 'seller_financing_amount',
                'Seller Down Payment Amount' => 'seller_down_payment_amount',
                'Interest Rate' => 'interest_rate',
                'Loan Duration' => 'loan_duration',
                'Amortization Type' => 'seller_amortization_type',
                'Payment Frequency' => 'seller_payment_frequency',
                'Late Fee Amount' => 'seller_late_fee_amount',
                'Late Fee Type' => 'seller_late_fee_type',
                'Prepayment Penalty' => 'prepayment_penalty',
                'Prepayment Penalty Amount' => 'prepayment_penalty_amount',
                'Balloon Payment' => 'balloon_payment',
                'Balloon Payment Amount' => 'balloon_payment_amount',
                'Balloon Payment Date' => 'balloon_payment_date',
                'Seller Broker Leasing Fee' => 'seller_broker_leasing_fee',
                'Seller Leasing Fee Type' => 'seller_leasing_fee_type',
                'Seller Leasing Gross' => 'seller_leasing_gross',
                'Seller Leasing Each Rental' => 'seller_leasing_each_rental',
                'Seller Leasing Gross Flat Combo' => 'seller_leasing_gross_flat_combo',
                'Seller Leasing Gross Flat Net Combo' => 'seller_leasing_gross_flat_net_combo',
                'Seller Leasing Gross Month Rent' => 'seller_leasing_gross_month_rent',
                'Seller Leasing Gross No. of Months' => 'seller_leasing_gross_no_of_months',
                'Seller Leasing Gross Percentage Combo' => 'seller_leasing_gross_percentage_combo',
                'Seller Leasing Gross Percentage Net Combo' => 'seller_leasing_gross_percentage_net_combo',
                'Seller Leasing Gross Percentage No. of Months' => 'seller_leasing_gross_percentage_no_of_months',
                'Seller Leasing Gross Purchase Fee (Flat)' => 'seller_leasing_gross_purchase_fee_flat_amount',
                'Seller Leasing Gross Purchase Fee Other' => 'seller_leasing_gross_purchase_fee_other',
                'Seller Leasing Gross Rental' => 'seller_leasing_gross_rental',
                'Seller Leasing Gross % Rent' => 'seller_leasing_gross_ross_percentage_rent',
                'Seller Leasing Gross Sales Tax (First Month)' => 'seller_leasing_gross_sales_tax_first_month',
                'Seller Leasing Gross Sales Tax (Flat Fee)' => 'seller_leasing_gross_sales_tax_flat_free_gross',
                'Seller Leasing Gross Sales Tax Option' => 'seller_leasing_gross_sales_tax_option_gross',
                'Seller Leasing Gross Other' => 'seller_leasing_gross_other',
            ],

            'Assumable Loan' => [
                'Assumable Terms' => 'assumable_terms',
                'Assumable Loan Type' => 'assumable_loan_type',
                'Max Assumable Rate' => 'max_assumable_rate',
                'Assumable Fee Type' => 'assumable_fee_type',
                'Assumable Fee Amount' => 'assumable_fee_amount',
                'Assumable Monthly Escrow' => 'assumable_monthly_escrow',
                'Assumable Loan Term Remaining' => 'assumable_loan_term_remaining',
                'Assumable Loan Origination Date' => 'assumable_loan_origination_date',
                'Assumable Loan Servicer' => 'assumable_loan_servicer',
                'Assumable Occupancy Requirement' => 'assumable_occupancy_requirement',
            ],

            'Gap / Additional Payments' => [
                'Max Monthly Payment' => 'max_monthly_payment',
                'Gap Payment Type' => 'gap_payment_type',
                'Gap Payment Amount' => 'gap_payment_amount',
                'Additional Cash' => 'additional_cash',
            ],

            'Exchange / Trade' => [
                'Exchange Item' => 'exchange_item',
                'Exchange Item Value' => 'exchange_item_value',
                'Exchange Item Condition' => 'exchange_item_condition',
                'Value Determination' => 'value_determination',
                'Exchange Transfer Method' => 'exchange_transfer_method',
                'Exchange Liens' => 'exchange_liens',
                'Exchange Liens Details' => 'exchange_liens_details',
                'Exchange Inspection Rights' => 'exchange_inspection_rights',
            ],

            'Lease Option' => [
                'Interested in Lease Option' => 'interested_lease_option',
                'Interested in Lease Option Agreement' => 'interested_lease_option_agreement',
                'Lease Option Price' => 'lease_option_price',
                'Lease Option Terms' => 'lease_option_terms',
                'Lease Option Duration' => 'lease_option_duration',
                'Lease Option Payment' => 'lease_option_payment',
                'Lease Option Conditions' => 'lease_option_conditions',
                'Has Option Fee' => 'has_option_fee',
                'Option Fee Amount' => 'option_fee_amount',
                'Lease Option Fee Credit' => 'lease_option_fee_credit',
                'Lease Option Fee Credit %' => 'lease_option_fee_credit_percentage',
                'Lease Option Maintenance' => 'lease_option_maintenance',
                'Lease Option Extension Terms' => 'lease_option_extension_terms',
                'Lease Option Consideration' => 'lease_option_consideration',
            ],

            'Lease Purchase' => [
                'Lease Purchase Price' => 'lease_purchase_price',
                'Lease Purchase Terms' => 'lease_purchase_terms',
                'Lease Purchase Duration' => 'lease_purchase_duration',
                'Lease Purchase Payment' => 'lease_purchase_payment',
                'Lease Purchase Conditions' => 'lease_purchase_conditions',
                'Lease Purchase Rent Credit' => 'lease_purchase_rent_credit',
                'Lease Purchase Rent Credit Amount' => 'lease_purchase_rent_credit_amount',
                'Lease Purchase Rent Credit Amount Type' => 'lease_purchase_rent_credit_amount_type',
                'Lease Purchase Deposit' => 'lease_purchase_deposit',
                'Lease Purchase Maintenance' => 'lease_purchase_maintenance',
                'Lease Purchase Extension Terms' => 'lease_purchase_extension_terms',
                'Lease Purchase Option Fee' => 'lease_purchase_option_fee',
                'Lease Purchase Option Fee Amount' => 'lease_purchase_option_fee_amount',
            ],

            'Cryptocurrency' => [
                'Cryptocurrency Type' => 'cryptocurrency_type',
                'Crypto Percentage' => 'crypto_percentage',
                'Cash Percentage (Crypto)' => 'cash_percentage_crypto',
                'Crypto Transfer Timing' => 'crypto_transfer_timing',
                'Crypto Exchange Method' => 'crypto_exchange_method',
                'Crypto Custodian/Wallet' => 'crypto_custodian_wallet',
                'Crypto Transaction Fees' => 'crypto_transaction_fees',
            ],

            'NFT' => [
                'NFT Description' => 'nft_description',
                'NFT Percentage' => 'nft_percentage',
                'Cash Percentage (NFT)' => 'cash_percentage_nft',
                'NFT Valuation Method' => 'nft_valuation_method',
                'NFT Transfer Method' => 'nft_transfer_method',
                'NFT Gas Fees' => 'nft_gas_fees',
            ],

            'Lease Details' => [
                'Lease For' => 'lease_for',
                'Lease By' => 'lease_by',
                'Lease Date' => 'lease_date',
            ],

            'Services' => [
                'Services' => 'services',
                'Custom Services' => 'custom_services',
                'Marketing: Include Marketing Fee' => 'include_marketing_fee',
                'Marketing: Email Marketing' => 'email_marketing_fee',
                'Marketing: Email Notifications' => 'email_notifications_fee',
                'Marketing: Launch Ads' => 'launch_ads',
                'Marketing: Launch Ads Fee' => 'launch_ads_fee',
                'Marketing: Market Groups' => 'market_groups',
                'Marketing: Market Groups Fee' => 'market_groups_fee',
                'Marketing: Marketing Materials Fee' => 'marketing_materials_fee',
                'Marketing: MLS Filter Fee' => 'mls_filter_fee',
                'Marketing: Off-Market Search Fee' => 'off_market_search_fee',
                'Marketing: Promote Social' => 'promote_social',
                'Marketing: Promote Social Fee' => 'promote_social_fee',
                'List Criteria' => 'list_criteria',
                'List Criteria Fee' => 'list_criteria_fee',
                'Flat Fee Services' => 'flat_fee_services',
                'Schedule Showings' => 'schedule_showings',
                'Schedule Showings Fee' => 'schedule_showings_fee',
                'Number of Showings to Schedule' => 'number_of_showings_to_schedule',
                'Attend Showings' => 'attend_showings',
                'Number of Showings to Attend' => 'number_of_showings_to_attend',
                'Attend Showings Fee' => 'attend_showings_fee',
                'Provide Virtual Tours' => 'provide_virtual_tours',
                'Number of Virtual Tours' => 'number_of_virtual_tours',
                'Virtual Tours Fee' => 'virtual_tours_fee',
                'Assist with Application' => 'assist_application',
                'Assist Application Fee' => 'assist_application_fee',
                'Collect Documents' => 'collect_documents',
                'Collect Documents Fee' => 'collect_documents_fee',
                'Submit Application' => 'submit_application',
                'Submit Application Fee' => 'submit_application_fee',
                'Review Lease' => 'review_lease',
                'Review Lease Fee' => 'review_lease_fee',
                'Provide Lease Form' => 'provide_lease_form',
                'Provide Lease Form Fee' => 'provide_lease_form_fee',
                'Coordinate Signing' => 'coordinate_signing',
                'Coordinate Signing Fee' => 'coordinate_signing_fee',
                'Prepare Application Fee' => 'prepare_application_fee',
                'Move-In Inspection Fee' => 'move_in_inspection_fee',
                'Moving Resources Fee' => 'moving_resources_fee',
                'Short-Term Housing Fee' => 'short_term_housing_fee',
                'Rental Rights Fee' => 'rental_rights_fee',
                'Lease Advice Fee' => 'lease_advice_fee',
                'Neighborhood Insights Fee' => 'neighborhood_insights_fee',
                'Neighborhood Marketing Fee' => 'neighborhood_marketing_fee',
                'Neighborhood Materials Fee' => 'neighborhood_materials_fee',
                'Total Marketing Fee' => 'total_marketing_fee',
                'Total Flat Fee' => 'total_flat_fee',
                'Staging Duration' => 'staging_duration',
                'Open House Count' => 'open_house_count',
                'Virtual Showings Count' => 'virtual_showings_count',
                'Photo Enhancements' => 'photo_enhancements',
            ],

            'Broker Compensation & Agency Agreement' => [
                'Commission Structure' => 'commission_structure',
                'Commission Structure Type' => 'commission_structure_type',
                'Commission Structure Type Fee (Flat)' => 'commission_structure_type_fee_flat',
                'Commission Structure Type Fee Flat Combo' => 'commission_structure_type_fee_flat_combo',
                'Commission Structure Type Fee (%)' => 'commission_structure_type_fee_percentage',
                'Commission Structure Type Fee % Combo' => 'commission_structure_type_fee_percentage_combo',
                'Commission Structure Type Fee Other' => 'commission_structure_type_fee_other',
                'Lease Fee Type' => 'lease_fee_type',
                'Lease Fee (Flat)' => 'lease_fee_flat',
                'Lease Fee (%)' => 'lease_fee_percentage',
                'Lease Fee (Months)' => 'lease_fee_months',
                'Lease Fee (% of Monthly Rent)' => 'lease_fee_percentage_monthly_rent',
                'Lease Fee (% Monthly Number)' => 'lease_fee_percentage_monthly_number',
                'Lease Fee Flat Combo' => 'lease_fee_flat_combo',
                'Lease Fee % Combo' => 'lease_fee_percentage_combo',
                'Lease Fee Flat Combo (Net)' => 'lease_fee_flat_combo_net',
                'Lease Fee % Combo (Net)' => 'lease_fee_percentage_combo_net',
                'Lease Fee % (Net)' => 'lease_fee_percentage_net',
                'Lease Fee Flat Type' => 'lease_fee_flat_type',
                'Lease Fee Other' => 'lease_fee_other',
                'Purchase Fee Type' => 'purchase_fee_type',
                'Interested in Purchase Fee Type' => 'interested_purchase_fee_type',
                'Purchase Fee (%)' => 'purchase_fee_percentage',
                'Purchase Fee (Flat)' => 'purchase_fee_flat',
                'Purchase Fee Flat Type' => 'purchase_fee_flat_type',
                'Purchase Fee % Combo' => 'purchase_fee_percentage_combo',
                'Purchase Fee Flat Combo' => 'purchase_fee_flat_combo',
                'Purchase Fee Other' => 'purchase_fee_other',
                'Purchase Fee (Flat Commercial)' => 'purchase_fee_flat_commercial',
                'Purchase Fee Other (Commercial)' => 'purchase_fee_other_commercial',
                'Purchase Fee (Net Aggregate)' => 'purchase_fee_net_aggregate',
                'Purchase Fee (Gross Rent)' => 'purchase_fee_gross_rent',
                'Purchase Fee (Monthly %)' => 'purchase_fee_monthly_percentage',
                'Purchase Fee (Months)' => 'purchase_fee_months',
                'Purchase Fee (Purchase Price)' => 'purchase_fee_purchase_price',
                'Purchase Fee (Rental Period)' => 'purchase_fee_rental_period',
                'Lease Option Fee Type' => 'lease_option_fee_type',
                'Lease Option Fee (Flat)' => 'lease_option_fee_flat',
                'Lease Option Fee Flat Combo' => 'lease_option_fee_flat_combo',
                'Lease Option Fee (%)' => 'lease_option_fee_percentage',
                'Lease Option Fee % Combo' => 'lease_option_fee_percentage_combo',
                'Lease Option Fee Other' => 'lease_option_fee_other',
                'Landlord Broker (Flat Fee)' => 'landlord_broker_flate_fee',
                'Landlord Broker Flat Fee Type' => 'landlord_broker_flate_fee_type',
                'Landlord Broker (% of Price)' => 'landlord_broker_percentage_price',
                'Landlord Broker ($ Price)' => 'landlord_broker_dollar_price',
                'Landlord Broker (Purchase Price)' => 'landlord_broker_purchase_price',
                'Landlord Broker Other' => 'landlord_broker_other',
                'Tenant Broker Commission Structure' => 'tenant_broker_commission_structure',
                'Tenant Broker Fee Structure' => 'tenant_broker_fee_structure',
                'Tenant Broker (%)' => 'tenant_broker_percentage',
                'Tenant Broker (Flat Fee)' => 'tenant_broker_flat_fee',
                'Tenant Broker (First Month Rent)' => 'tenant_broker_first_month_rent',
                'Tenant Broker (Gross Lease)' => 'tenant_broker_gross_lease',
                'Tenant Broker Other' => 'tenant_broker_other',
                'Expansion Commission (%)' => 'expansion_commission_percentage',
                'Renewal Fee Type' => 'renewal_fee_type',
                'Renewal Fee (%)' => 'renewal_fee_percentage',
                'Renewal Fee (First Month)' => 'renewal_fee_first_month',
                'Renewal Fee (Flat Fee)' => 'renewal_fee_flat_free',
                'Renewal Fee (Lease Value)' => 'renewal_fee_lease_value',
                'Renewal Fee (Number of Months)' => 'renewal_fee_no_of_months',
                'Renewal Fee Sales Tax (First Month)' => 'renewal_fee_sales_tax_first_month',
                'Renewal Fee Sales Tax (Flat Fee)' => 'renewal_fee_sales_tax_flat_fee',
                'Renewal Fee Sales Tax (Lease Value)' => 'renewal_fee_sales_tax_lease_value',
                'Renewal Fee Custom' => 'renewal_fee_custom',
                'Sales Tax Option (Flat)' => 'sales_tax_option_flat',
                'Sales Tax Option (Gross)' => 'sales_tax_option_gross',
                'Sales Tax Option (Monthly)' => 'sales_tax_option_monthly',
                'Outstanding Balance' => 'outstanding_balance',
                'Retained Deposits' => 'retained_deposits',
                'Split Payment Due' => 'split_payment_due',
                'Broker Fee Timing' => 'broker_fee_timing',
                'Broker Fee Days After Lease' => 'broker_fee_days_after_lease',
                'Broker Fee Days After Rent' => 'broker_fee_days_after_rent',
                'Broker Fee Days From Rent' => 'broker_fee_days_from_rent',
                'Broker Fee Days After Due Event' => 'broker_fee_days_after_due_event',
                'Protection Period' => 'protection_period',
                'Early Termination Fee' => 'early_termination_fee_option',
                'Lease Type' => 'lease_type',
                'Lease Value' => 'lease_value',
                'Purchase Type' => 'purchase_type',
                'Purchase Value' => 'purchase_value',
                'Retainer Fee' => 'retainer_fee_option',
                'Retainer Fee Application' => 'retainer_fee_application',
                'Agency Agreement Timeframe' => 'agency_agreement_timeframe',
                'Agency Agreement Custom' => 'agency_agreement_custom',
                'Brokerage Relationship' => 'brokerage_relationship',
            ],

            'Property Management' => [
                'Interested in Property Management' => 'interested_in_property_management',
                'Property Management Fee' => 'interested_in_property_management_fee',
                'Property Management (Flat Fee)' => 'interested_in_property_management_fee_flate_free',
                'Property Management (Gross Lease)' => 'interested_in_property_management_fee_gross_lease',
                'Property Management (Rental Period)' => 'interested_in_property_management_fee_rental_periord',
                'Property Management Other' => 'interested_in_property_management_fee_other',
                'Interested in Selling' => 'interested_in_selling',
                'Interested in Selling Type' => 'interested_in_selling_type',
            ],

            'Additional Details' => [
                'Additional Details' => 'additional_details',
                'Additional Details (Broker)' => 'additional_details_broker',
                'Video Link' => 'video_link',
            ],

            'Meeting Details' => [
                'Person Meeting' => 'person_meeting',
                'First Name' => 'meeting_details_first_name',
                'Last Name' => 'meeting_details_last_name',
                'Phone' => 'meeting_details_phone',
                'Email' => 'meeting_details_email',
                'Meeting Date' => 'meeting_details_meeting_date',
                'Meeting Time' => 'meeting_details_meeting_time',
                'Time Zone' => 'meeting_details_time_zone',
                'Meeting Instructions' => 'meeting_details_instructions',
                'Additional Meeting Details' => 'meeting_details_additional_details',
                'Service Completion Date' => 'service_completion_date',
                'Service Completion Time' => 'service_completion_time',
                'Service Time Zone' => 'service_time_zone',
            ],

            'Contact Information' => [
                'First Name' => 'first_name',
                'Last Name' => 'last_name',
                'Phone' => 'phone_number',
                'Email' => 'email',
            ],
        ];
    }

    public static function otherPairs(): array
    {
        return [
            'property_items' => 'other_property_items',
            'condition_prop' => 'other_property_condition',
            'condition_prop_buyer' => 'other_property_condition',
            'assets' => 'assets_other',
            'sale_provision' => 'sale_provision_other',
            'offered_financing' => 'other_financing',
            'services' => 'other_services',
            'seller_amortization_type' => 'seller_amortization_other',
            'seller_payment_frequency' => 'seller_payment_frequency_other',
            'owner_pays' => 'owner_pays_other',
            'exchange_item' => 'other_exchange_item',
            'bathrooms' => 'other_bathrooms',
            'bedrooms' => 'other_bedrooms',
            'unit_size' => 'unit_size_other',
            'carport_needed' => 'other_carport_needed',
            'garage_needed' => 'other_garage_needed',
            'garage_parking_spaces_option' => 'other_parking_space_wrapper',
            'view_preference' => 'other_preferences',
            'appliances' => 'other_appliances',
            'non_negotiable_amenities' => 'other_non_negotiable_amenities',
            'lease_for' => 'other_lease_for',
            'tenant_pays' => 'other_tenant_pays',
            'owner_pays' => 'other_owner_pays',
            'rent_includes' => 'other_rent_include',
            'custom_lease_term' => 'other_lease_term',
            'business_type' => 'other_business_type',
            'crypto_transfer_timing' => 'crypto_transfer_timing_other',
            'assumable_occupancy_requirement' => 'assumable_occupancy_other',
            'split_payment_due' => 'split_payment_due_other',
            'broker_fee_timing' => 'broker_fee_timing_other',
        ];
    }
}
