<?php

return [
    'questions' => [
        'Buyer Readiness & Motivation' => [
            'buyer_active_now'         => 'Is the buyer actively looking to purchase now, or is this exploratory?',
            'buyer_timeline'           => "What is the buyer's target timeline to purchase?",
            'buyer_motivation'         => "What is the buyer's primary motivation for purchasing?",
            'buyer_current_situation'  => "What is the buyer's current living or business situation (renting, owning, etc.)?",
            'buyer_area_familiarity'   => 'How familiar is the buyer with the target area?',
            'buyer_flexibility'        => 'How flexible is the buyer on location or timing?',
            'buyer_deal_breakers'      => "What are the buyer's absolute deal-breakers?",
            'buyer_lost_deal'          => 'Has the buyer previously lost a deal? If so, what happened?',
        ],
        'Budget' => [
            'buyer_budget_confirmed'      => "Has the buyer confirmed their total budget?",
            'buyer_down_payment'          => 'How much is the buyer planning to put as a down payment?',
            'buyer_cash_reserves'         => 'Does the buyer have cash reserves remaining after the down payment?',
            'buyer_seller_concessions'    => 'Would the buyer consider seller concessions in lieu of a price reduction?',
            'buyer_monthly_payment_limit' => "What is the buyer's maximum acceptable monthly payment?",
            'buyer_budget_other'          => 'Any other budget-related details?',
        ],
        'Financing' => [
            'buyer_preapproval_status'      => 'Has the buyer been pre-approved or pre-qualified for a loan?',
            'buyer_preapproval_amount'      => 'What is the pre-approval amount?',
            'buyer_lender_name'             => "Who is the buyer's lender or bank?",
            'buyer_loan_type'               => 'What type of loan is the buyer using (e.g., Conventional, FHA, VA, Cash)?',
            'buyer_cash_buyer'              => 'Is the buyer a cash buyer? Do they have proof of funds?',
            'buyer_financing_contingency'   => 'Will the buyer include a financing contingency in the offer?',
            'buyer_bridge_loan'             => 'Is the buyer using a bridge loan or any interim financing?',
            'buyer_co_borrower'             => 'Is there a co-borrower on the loan?',
        ],
        'Desired Property Criteria' => [
            'buyer_property_style'  => 'What property style or architecture is preferred?',
            'buyer_age_preference'  => 'Does the buyer prefer new construction, older homes, or no preference?',
            'buyer_must_have_features' => "What are the buyer's absolute must-have property features?",
            'buyer_nice_to_have'    => 'What property features are nice-to-have but not required?',
            'buyer_school_district' => 'Is a specific school district required?',
            'buyer_hoa_acceptable'  => 'Will the buyer consider HOA communities? What is the maximum monthly HOA fee?',
            'buyer_accessibility'   => 'Does the buyer need any accessibility features?',
            'buyer_home_office'     => 'Does the buyer require a dedicated home office or workspace?',
        ],
        'Offer Terms' => [
            'buyer_earnest_money'          => 'What earnest money amount is the buyer prepared to offer?',
            'buyer_inspection_contingency' => 'Will the buyer include an inspection contingency?',
            'buyer_appraisal_contingency'  => 'Will the buyer include an appraisal contingency?',
            'buyer_escalation_clause'      => 'Is the buyer willing to use an escalation clause?',
            'buyer_as_is'                  => 'Will the buyer consider purchasing as-is?',
            'buyer_repairs_limit'          => 'Is there a maximum repair credit the buyer would accept?',
            'buyer_leaseback'              => 'Would the buyer consider a seller leaseback arrangement?',
            'buyer_multiple_offers'        => 'How does the buyer handle multiple-offer situations?',
            'buyer_offer_expiration'       => 'How long will the buyer keep an offer open?',
        ],
        'Showing & Access' => [
            'buyer_showing_availability' => 'What are the best times for the buyer to schedule showings?',
            'buyer_virtual_tour'         => 'Is the buyer open to virtual tours or remote viewings?',
            'buyer_relocation'           => 'Is the buyer relocating from another city or state?',
            'buyer_relocation_timeline'  => 'If relocating, what is the timeline for the move?',
            'buyer_agent_present'        => "Does the buyer's agent need to be present at all showings?",
            'buyer_travel_distance'      => 'How far is the buyer willing to travel for showings?',
        ],
        'Closing Readiness' => [
            'buyer_close_timeline'        => 'What is the buyer\'s ideal closing timeline?',
            'buyer_flexible_close'        => 'How flexible is the buyer on the closing date?',
            'buyer_simultaneous_close'    => 'Does the buyer need to sell a current property simultaneously?',
            'buyer_post_close_occupancy'  => 'Is the buyer open to post-closing occupancy agreements?',
            'buyer_move_in_ready'         => 'Does the buyer require a move-in-ready property?',
        ],
        'Seller High-Intent' => [
            'buyer_communication_preference' => "What is the buyer's preferred method of communication?",
            'buyer_decision_makers'          => 'Who else is involved in the final buying decision?',
            'buyer_ready_to_offer'           => 'Is the buyer ready to make an offer if the right property is found today?',
            'buyer_agent_loyalty'            => 'Is the buyer working exclusively with one agent or interviewing multiple agents?',
            'buyer_prefers_off_market'       => 'Is the buyer open to off-market or pocket listings?',
            'buyer_additional_criteria'      => 'Any additional criteria or preferences the buyer wants sellers to know?',
            'buyer_neighborhood_preferences' => 'Does the buyer have specific neighborhood or community preferences?',
            'buyer_commute_requirements'     => 'Does the buyer have commute distance or public transit requirements?',
            'buyer_noise_tolerance'          => 'What is the buyer\'s tolerance for noise (e.g., near highways, airports, schools)?',
            'buyer_privacy_requirements'     => 'Does the buyer have specific privacy requirements (e.g., fencing, lot size)?',
            'buyer_outdoor_space'            => 'What outdoor space requirements does the buyer have?',
            'buyer_storage_needs'            => 'What storage needs does the buyer have (garage, basement, attic, etc.)?',
            'buyer_parking_needs'            => "What are the buyer's parking requirements?",
            'buyer_view_preference'          => 'Does the buyer have a preference for a specific view (water, mountain, city, etc.)?',
        ],
        'Commercial / Income Property Add-On' => [
            'com_property_use'           => 'What is the intended use of the commercial property?',
            'com_investment_type'        => 'Is this an investment or owner-occupied purchase?',
            'com_cap_rate_target'        => 'What cap rate is the buyer targeting?',
            'com_noi_required'           => 'What minimum Net Operating Income (NOI) is required?',
            'com_occupancy_rate'         => 'What minimum occupancy rate is required?',
            'com_lease_terms'            => 'What lease structure is preferred (gross, NNN, modified gross)?',
            'com_tenant_type'            => 'What tenant type or mix is desired?',
            'com_zoning'                 => 'What zoning classification is required?',
            'com_buildout_allowance'     => 'Is a tenant improvement/buildout allowance expected?',
            'com_due_diligence_period'   => 'What due diligence period is expected?',
            'com_environmental_concerns' => 'Are environmental assessments required?',
            'com_parking_requirements'   => 'What parking ratio is required?',
            'com_1031_exchange'          => 'Is the buyer doing a 1031 exchange?',
        ],
        'Business Opportunity Add-On' => [
            'biz_type_seeking'       => 'What type of business is the buyer seeking?',
            'biz_revenue_required'   => 'What minimum annual revenue is required?',
            'biz_profit_required'    => 'What minimum net profit is required?',
            'biz_staff_included'     => 'Will existing staff be retained as part of the purchase?',
            'biz_training_expected'  => 'How much seller training or transition support is expected?',
            'biz_lease_status'       => 'What is the status of the business lease (length remaining, assignable, etc.)?',
            'biz_inventory_included' => 'Is inventory included in the purchase price?',
            'biz_non_compete'        => 'Is a non-compete agreement required from the seller?',
            'biz_sba_financing'      => 'Is the buyer considering SBA financing for the business purchase?',
        ],
        'Vacant Land Add-On' => [
            'land_intended_use'      => 'What is the intended use of the vacant land (residential build, agricultural, commercial, etc.)?',
            'land_zoning_required'   => 'What zoning classification is required for the land?',
            'land_utilities_needed'  => 'What utilities need to be available or accessible at the land?',
            'land_soil_testing'      => 'Will the buyer require soil or environmental testing as a contingency?',
            'land_subdivision_plans' => 'Does the buyer plan to subdivide the land?',
            'land_build_timeline'    => "What is the buyer's expected building or development timeline?",
            'land_survey_required'   => 'Is a current survey required as part of the transaction?',
            'land_access_requirements' => 'What road access or easement requirements does the buyer have?',
            'land_topography'        => 'Are there topography, flood zone, or elevation requirements?',
        ],
    ],
];
