<?php

return [
    'landlord_agent' => [
        'residential' => [
            '📢 Rental Marketing & Listing Promotion' => [
                'List the property on the local Multiple Listing Service (MLS)',
                'Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)',
                "Create a branded flyer featuring the property\u2019s key highlights",
                'Post the property on Facebook Marketplace',
                'Post the property on Craigslist in the appropriate "Homes for Rent" category',
                'Share the listing on Nextdoor in Neighborhood or Community Groups',
                'Promote the listing on Facebook in Housing or Rental Groups',
                'Share the listing on Instagram using posts, stories, or reels',
                'Promote the listing on LinkedIn in Professional or Real Estate Groups',
                'Upload a TikTok video walkthrough of the property',
                'Upload a YouTube video walkthrough of the property',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
            ],
            '📋 Listing Presentation & Preparation' => [
                'Conduct a property walkthrough and provide recommendations for listing readiness',
                'Provide a custom listing preparation checklist',
                'Collect property details and prepare MLS remarks and a public listing description',
                'Provide a visual consultation for interior layout, cleanliness, and presentation',
                'Provide a curb appeal consultation focused on exterior presentation',
                "Provide referrals to third-party vendors (e.g., cleaners, handypeople, electricians, landscapers). Vendor fees billed separately. Referrals only \u2014 no endorsement or warranty is made",
            ],
            '📸 Photography, Video & Virtual Media' => [
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide virtual staging (digital enhancements only; no physical staging)',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
            ],
            '🏡 Showings & Access Coordination' => [
                'Ensure proper notice is given if the property is occupied',
                'Install a real estate sign on the property',
                'Install a lockbox for Agent access',
                'Schedule and attend showings with prospective Tenants',
                "Coordinate showings with Tenant\u2019s Agents",
                'Collect and relay feedback to the Landlord after showings',
            ],
            '📝 Tenant Application Support' => [
                'Provide a link to an online application platform with third-party screening tools (e.g., credit, background, and eviction checks)',
                'Ensure compliance with Fair Housing laws and screening regulations throughout the application process',
                'Collect and organize application documents submitted by prospective Tenants',
                'Verify basic information provided in the application (e.g., employment, income, and references)',
                'Present complete and organized application packages to the Landlord for review and final selection',
            ],
            '📃 Lease Preparation & Execution' => [
                'Review lease offers submitted by prospective Tenants and summarize key terms',
                "Coordinate lease negotiation with the Tenant or Tenant\u2019s Agent",
                'Prepare a state-specific lease agreement using approved forms or templates',
                'Assist with completing required lease disclosures and reviewing key lease terms',
                'Assist with in-person or electronic lease signing, including e-signature setup and secure delivery of executed lease documents, addenda, and disclosures to all parties',
                'Confirm receipt of required move-in funds and assist the Landlord in verifying amounts due, payment deadlines, and accepted payment methods',
            ],
            '🚚 Move-In Support & Coordination' => [
                "Coordinate move-in date and key handoff logistics with the Tenant or Tenant\u2019s Agent",
                'Confirm completion of any agreed-upon pre-move-in cleaning or repairs',
                'Verify receipt of all required move-in funds prior to occupancy (e.g., deposit, rent, pet fees)',
                'Provide a utility setup checklist and local provider resources for the Tenant',
                'Share a move-in checklist for documentation and property condition review',
            ],
            '📑 Property Management' => [
                'Provide ongoing property management services throughout the lease term (rent collection, maintenance coordination, Tenant communications, lease enforcement, renewals, etc.)',
            ],
            '💡 Leasing Strategy & Guidance' => [
                'Provide a Rental Market Analysis (RMA) with pricing insights based on comparable rentals, neighborhood trends, and current market conditions ',
                'Advise on lease types and structures (e.g., month-to-month, annual, furnished, corporate, lease-option)',
                'Provide general guidance on Landlord obligations and Tenant rights under state law',
                'Provide general guidance on rental demand, local market conditions, and Tenant expectations',
            ],
        ],
        'commercial' => [
            '📢 Rental Marketing & Listing Promotion' => [
                'List the property on the local Multiple Listing Service (MLS)',
                'List the property on Crexi.com',
                'List the property on LoopNet.com',
                "Create a branded flyer featuring the property\u2019s key highlights",
                'Post the property on Craigslist under the "Office/Commercial" category',
                'Promote the listing on Facebook in Commercial Leasing or Business Startup Groups',
                'Share the listing on Instagram using photos, stories, or reels',
                'Promote the listing on LinkedIn in Professional, Real Estate, or Commercial Investment Groups',
                'Upload a TikTok video walkthrough of the property',
                'Upload a YouTube video walkthrough of the property',
                'Launch a mass email campaign promoting the listing',
                'Distribute printed flyers or postcards in target geographic areas',
                'Launch hyperlocal or interest-based digital ad campaigns promoting the listing',
            ],
            '📋 Listing Presentation & Preparation' => [
                'Conduct a property walkthrough and provide recommendations for listing readiness',
                'Provide a custom listing preparation checklist',
                'Collect property details such as lease terms, square footage, property features, and allowable uses',
                'Prepare a marketing packet including zoning, cap rate references, and permitted uses',
                'Provide a visual consultation focused on interior layout, cleanliness, and presentation',
                'Provide a curb appeal consultation for exterior appearance and signage opportunities',
                "Provide referrals to third-party vendors (e.g., cleaners, sign installers, minor repair vendors). Vendor fees billed separately. Referrals only \u2014 no endorsement or warranty is made",
            ],
            '📸 Photography, Video & Virtual Media' => [
                'Provide professional property photography',
                'Provide aerial (drone) photography (subject to FAA Part 107 compliance)',
                'Provide a video walkthrough tour',
                'Provide a 3D virtual tour',
                'Provide virtual staging (digital enhancements only; no physical staging)',
                'Provide digital photo enhancements',
                'Create a basic schematic floor plan (non-certified; for marketing purposes only)',
            ],
            '🏢 Showings & Access Coordination' => [
                'Ensure proper notice is given if the property is occupied',
                'Install a real estate sign on the property',
                'Install a lockbox for Agent access',
                'Schedule and attend showings with prospective Tenants',
                "Coordinate showings with Tenant\u2019s Agents",
                'Collect and relay showing feedback to the Landlord',
            ],
            '📝 Tenant Application Support' => [
                "Provide a link to an online application platform or share instructions with prospective Tenants or Tenant\u2019s Agents",
                'Ensure compliance with applicable federal, state, and local commercial leasing and anti-discrimination laws',
                'Collect and organize application documents (e.g., business licenses, financials, entity records, references)',
                'Verify basic information provided in the application (e.g., business operations, income sources, references)',
                'Present complete application packages to the Landlord for review and final selection',
            ],
            '📃 Lease Preparation, LOI & Execution' => [
                "Coordinate lease negotiation with the Tenant or Tenant\u2019s Agent",
                'Collect and organize Letters of Intent (LOIs) or draft lease proposals',
                'Draft or assist with execution of the final lease agreement using approved forms or templates',
                'Provide and review required lease disclosures and addenda based on state or municipal requirements',
                'Assist with in-person or electronic lease signing, including e-signature setup and secure delivery of executed lease documents, addenda, and disclosures to all parties',
                'Verify receipt of required deposits and track rent commencement and key lease dates to ensure move-in readiness',
            ],
            '🚚 Move-In Support & Coordination' => [
                "Coordinate move-in date and key handoff logistics with the Tenant or Tenant\u2019s Agent",
                'Confirm completion of any agreed-upon pre-move-in repairs, cleaning, or improvements',
                'Verify receipt of all required move-in funds and documents prior to occupancy (e.g., rent, security deposit, insurance certificates)',
                'Provide a utility setup checklist and local provider resources for the Tenant',
                'Share a move-in checklist for documentation and property condition review',
                'Assist with coordination of move-in logistics, including Certificate of Insurance (COI) and vendor access (as agreed)',
            ],
            '📑 Property Management' => [
                'Provide ongoing property management services throughout the lease term (rent collection, maintenance coordination, Tenant communications, lease enforcement, renewals, etc.)',
            ],
            '💡 Leasing Strategy & Guidance' => [
                'Provide a Comparable Lease Analysis with pricing recommendations based on similar properties, local vacancy trends, and current market conditions',
                'Advise on lease types and structures (e.g., NNN, Modified Gross, Full Service) with general explanations of differences',
                'Provide general guidance on Landlord obligations and Tenant rights under applicable commercial leasing laws',
                'Provide general guidance on zoning, permitted uses, occupancy standards, or rent escalation terms',
            ],
        ],
    ],
];
