<?php

return [
    'seller_agent' => [
        'residential' => [
            '📢 Property Marketing & Listing Promotion' => [
                "List the property on the local Multiple Listing Service (MLS)",
                "Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)",
                "Create a branded flyer featuring the property\u2019s key highlights",
                "Post the property on Facebook Marketplace",
                "Post the property on Craigslist under the \"Homes for Sale\" category",
                "Share the listing on Nextdoor in Neighborhood or Community Groups",
                "Promote the listing on Facebook in Real Estate or Community Groups",
                "Share the listing on Instagram using posts, stories, or reels",
                "Promote the listing on LinkedIn in Professional or Real Estate Groups",
                "Upload a TikTok video walkthrough of the property",
                "Upload a YouTube video walkthrough of the property",
                "Launch a mass email campaign promoting the listing",
                "Distribute printed flyers or postcards in target geographic areas",
                "Launch hyperlocal or interest-based digital ad campaigns promoting the listing",
            ],
            '🛠️ Listing Preparation & Presentation' => [
                "Conduct a property walkthrough and provide recommendations for listing readiness",
                "Provide a custom listing preparation checklist",
                "Collect property details and prepare MLS remarks and a public listing description",
                "Provide a visual consultation for interior layout, cleanliness, and presentation",
                "Provide a curb appeal consultation focused on exterior presentation",
                "Provide referrals to third-party vendors (e.g., cleaners, handypeople, electricians, landscapers). Vendor fees billed separately. Referrals only \u2014 no endorsement or warranty is made",
            ],
            '📸 Photography, Video & Virtual Media' => [
                "Provide professional property photography",
                "Provide aerial (drone) photography (subject to FAA Part 107 compliance)",
                "Provide a video walkthrough tour",
                "Provide a 3D virtual tour",
                "Provide virtual staging (digital enhancements only; no physical staging)",
                "Provide digital photo enhancements",
                "Create a basic schematic floor plan (non-certified; for marketing purposes only)",
            ],
            '🏡 Showings & Access Coordination' => [
                "Ensure proper notice is provided if the property is occupied",
                "Install a real estate sign on the property",
                "Install a lockbox for Agent access",
                "Schedule and attend showings with prospective Buyers",
                "Coordinate showings with Buyer\u2019s Agents",
                "Collect and relay showing feedback to the Seller",
            ],
            '📑 Offer & Contract Management' => [
                "Present all offers to the Seller and summarize key terms, pricing, and contingencies",
                "Provide the Seller with the necessary disclosure forms required by state or local law",
                "Negotiate price, terms, and contingencies with the Buyer\u2019s Agent or Buyer",
                "Manage communications with the Buyer\u2019s Agent or Buyer",
                "Draft and deliver counteroffers and manage revisions to the purchase agreement",
                "Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties",
                "Assist with inspection-related negotiations and Buyer requests for repairs",
                "Monitor contract milestones, contingency periods, and financing deadlines",
                "Provide referrals to Attorneys, Title Companies, and Escrow Professionals (referrals only \u2014 no endorsement or warranty is made)",
            ],
            '🧾 Closing Coordination & Transaction Management' => [
                "Coordinate scheduling for inspections, appraisals, and other requested evaluations",
                "Coordinate with the Buyer\u2019s Agent, Lender, Title, Escrow, and/or Attorney to prepare for Closing",
                "Review the Settlement Statement and coordinate with all parties if corrections are needed",
                "Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties",
                "Schedule and confirm the Final Walkthrough",
                "Schedule and confirm the Closing Appointment",
            ],
            '💡 Selling Strategy & Guidance' => [
                "Provide a Comparative Market Analysis (CMA) with pricing recommendations based on comparable sales, neighborhood trends, and current market conditions",
                "Provide general insight on local market trends, seasonal timing, and pricing thresholds",
                "Recommend adjustments to pricing or marketing strategy if the property is not receiving sufficient interest",
                "Provide general guidance on Seller obligations, required disclosures, and listing preparation",
            ],
        ],
        'income' => [
            '📢 Property Marketing & Listing Promotion' => [
                "List the property on the local Multiple Listing Service (MLS)",
                "Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)",
                "List the property on Crexi.com",
                "List the property on LoopNet.com",
                "Create a branded flyer with key rental data (e.g., unit mix, gross income, occupancy)",
                "Post the property on Craigslist under the \"Multi-Family for Sale\" category",
                "Share the listing on Nextdoor in Neighborhood or Community Groups",
                "Promote the listing on Facebook in Real Estate Investor or Multi-Family Buyer Groups",
                "Share the listing on Instagram using posts, stories, or reels",
                "Promote the listing on LinkedIn in Investment or Real Estate Groups",
                "Upload a TikTok video walkthrough of the property",
                "Upload a YouTube video walkthrough of the property",
                "Launch a mass email campaign promoting the listing",
                "Distribute printed flyers or postcards in target geographic areas",
                "Launch hyperlocal or interest-based digital ad campaigns promoting the listing",
            ],
            '🛠️ Listing Preparation & Investment Packaging' => [
                "Conduct a property walkthrough and provide recommendations for listing readiness",
                "Provide a custom listing preparation checklist",
                "Assist with assembling an income property packet, including rent roll, lease copies, and an income/expense summary (as available)",
                "Provide a visual consultation focused on interior layout, cleanliness, and unit presentation",
                "Provide a curb appeal consultation focused on exterior maintenance and first impressions",
                "Provide referrals to third-party vendors (e.g., cleaners, handypeople, electricians, landscapers). Vendor fees billed separately. Referrals only \u2014 no endorsement or warranty is made",
            ],
            '📸 Photography, Video & Virtual Media' => [
                "Provide professional property photography",
                "Provide aerial (drone) photography (subject to FAA Part 107 compliance)",
                "Provide a video walkthrough tour",
                "Provide a 3D virtual tour",
                "Provide virtual staging (digital enhancements only; no physical staging)",
                "Provide digital photo enhancements",
                "Create a basic schematic floor plan (non-certified; for marketing purposes only)",
            ],
            '🏘️ Showings & Access Coordination' => [
                "Respond to Buyer inquiries and screen for general qualifications",
                "Provide Non-Disclosure Agreement (NDA) templates for confidential showings or document access",
                "Ensure proper notice is provided if the property is occupied",
                "Install a real estate sign on the property",
                "Install a lockbox for Agent access",
                "Schedule and attend showings with prospective Buyers",
                "Coordinate showings with Buyer\u2019s Agents",
                "Collect and relay showing feedback to the Seller",
            ],
            '📉 Offer & Contract Management' => [
                "Present all offers to the Seller and summarize key terms, pricing, and contingencies",
                "Provide the Seller with the necessary disclosure forms required by state or local law",
                "Negotiate deal structure, deposits, due diligence timelines, and Buyer contingencies",
                "Draft and deliver counteroffers and manage revisions to the purchase agreement",
                "Manage communication with the Buyer\u2019s Agent or Buyers",
                "Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties",
                "Assist with inspection-related negotiations and Buyer requests for repairs",
                "Monitor contract contingencies, including financing, lease audits, estoppel review, insurance, inspections, and environmental reports",
                "Provide referrals to Attorneys, Title Companies, Escrow Officers, or 1031 Exchange Professionals. Referrals only \u2014 no endorsement or warranty is made",
            ],
            '🧾 Closing Coordination & Transaction Management' => [
                "Review and organize due diligence documentation such as lease agreements, estoppel certificates, rent rolls, utility summaries, and operating expense breakdowns (as available)",
                "Coordinate with the Buyer\u2019s Agent, Buyer\u2019s Lender, Title, Escrow, and/or Attorney to prepare for Closing",
                "Review the Settlement Statement for accuracy and coordinate with relevant parties if corrections are needed",
                "Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties",
                "Schedule and confirm the Final Walkthrough",
                "Schedule and confirm the Closing Appointment",
            ],
            '💡 Selling Strategy & Guidance' => [
                "Provide a Comparative Market Analysis (CMA) with pricing insights based on recent income property sales, rental income trends, unit mix, and local investor activity",
                "Assist in estimating Gross Rent Multiplier (GRM), Capitalization Rate (Cap Rate), or Price per Unit based on listing details and income property comparables",
                "Provide general insight on likely Investor Buyer behavior, common value drivers, and investment strategies",
                "Recommend adjustments to pricing or marketing strategy if the property is not receiving sufficient interest",
                "Provide general guidance on lease transfers, rent proration, security deposits, and possession timelines",
            ],
        ],
        'commercial' => [
            '📢 Property Marketing & Listing Promotion' => [
                "List the property on the local Multiple Listing Service (MLS)",
                "List the property on Crexi.com",
                "List the property on LoopNet.com",
                "Create a branded flyer summarizing the property\u2019s investment highlights and key selling points",
                "Post the property on Craigslist under the \"Commercial for Sale\" category",
                "Promote the listing on Facebook in Commercial or Investor Real Estate Groups",
                "Share the listing on Instagram using posts, stories, or reels",
                "Promote the listing on LinkedIn in Professional, Real Estate, or Commercial Investment Groups",
                "Upload a TikTok video walkthrough of the property",
                "Upload a YouTube video walkthrough of the property",
                "Launch a mass email campaign promoting the listing",
                "Distribute printed flyers or postcards in target geographic areas",
                "Launch hyperlocal or interest-based digital ad campaigns promoting the listing",
            ],
            '🛠️ Listing Preparation & Asset Presentation' => [
                "Conduct a property walkthrough and provide recommendations for listing readiness",
                "Provide a visual consultation on interior layout, cleanliness, and overall presentation",
                "Provide a curb appeal consultation focused on exterior appearance and first impressions",
                "Provide referrals to third-party vendors such as cleaners, handypeople, electricians, and landscapers (vendor fees billed separately; referrals only \u2014 no endorsement or warranty is made)",
                "Compile essential marketing materials such as rent rolls, lease summaries, financial statements, and operating data (as available)",
                "Organize zoning documentation, surveys, and public record reports (as available)",
            ],
            '📸 Photography, Video & Virtual Media' => [
                "Provide professional property photography",
                "Provide aerial (drone) photography (subject to FAA Part 107 compliance)",
                "Provide a video walkthrough tour",
                "Provide a 3D virtual tour",
                "Provide virtual staging (digital enhancements only; no physical staging)",
                "Provide digital photo enhancements",
                "Create a basic schematic floor plan (non-certified; for marketing purposes only)",
            ],
            '🏢 Showings & Access Coordination' => [
                "Respond to Buyer inquiries and screen for general qualifications",
                "Provide Non-Disclosure Agreement (NDA) templates for access to confidential documents or showings",
                "Ensure proper notice is provided if the property is occupied",
                "Install a real estate sign on the property",
                "Install a lockbox for Agent access",
                "Schedule and attend showings with prospective Buyers",
                "Coordinate showings with Buyer\u2019s Agents",
                "Collect and relay showing feedback to the Seller",
            ],
            '📉 Offer & Contract Management' => [
                "Present all offers to the Seller and summarize key terms, pricing, and contingencies",
                "Provide the Seller with the necessary disclosure forms required by state or local law",
                "Coordinate Letter of Intent (LOI) submissions, counteroffers, and contract revisions",
                "Negotiate deal terms such as pricing, deposit structure, closing timelines, and due diligence periods",
                "Manage communication with the Buyer\u2019s Agent or Buyer",
                "Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties",
                "Assist with inspection-related negotiations and Buyer requests for repairs or credits",
                "Monitor contract contingencies, including financing, estoppel review, lease audits, and environmental reports",
                "Provide referrals to Attorneys, Title Companies, Escrow Officers, or 1031 Exchange Professionals (referrals only \u2014 no endorsement or warranty is made)",
            ],
            '🧾 Closing Coordination & Transaction Management' => [
                "Coordinate inspections, appraisals, and estoppel certificate delivery with the Buyer\u2019s Agent or Buyer, as applicable",
                "Provide due diligence documentation such as lease agreements, estoppel certificates, rent rolls, utility summaries, and operating expense breakdowns (as available)",
                "Coordinate with the Buyer\u2019s Agent, Lender, Title, Escrow, and/or Attorney to prepare for Closing",
                "Review the Settlement Statement and coordinate with all parties if corrections are needed",
                "Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties",
                "Schedule and confirm the Final Walkthrough",
                "Schedule and confirm the Closing Appointment",
            ],
            '💡 Selling Strategy & Guidance' => [
                "Provide a Comparative Market Analysis (CMA) with pricing insights based on recent commercial property sales, rental income trends, market cap rates, and investor activity",
                "Assist in estimating Capitalization Rate (Cap Rate), Price per Square Foot, or Gross Rent Multiplier (GRM) based on listing details and commercial comparables",
                "Provide general insight on likely Buyer types (e.g., Owner-User, Investor, 1031 Exchange Buyer), common value drivers, and investment strategies",
                "Recommend adjustments to pricing or marketing strategy if the property is not receiving sufficient interest",
                "Provide general guidance on lease structures, expense ratios, and Tenant impacts",
            ],
        ],
        'business' => [
            '📢 Business Marketing & Listing Promotion' => [
                "List the Business Opportunity on the local Multiple Listing Service (MLS)",
                "List the Business Opportunity on Crexi.com",
                "List the Business Opportunity on LoopNet.com",
                "List the Business Opportunity on BizBuySell.com",
                "List the Business Opportunity on BizQuest.com",
                "List the Business Opportunity on BusinessesForSale.com",
                "Create a branded flyer summarizing the Business\u2019s key features (e.g., industry, cash flow, assets)",
                "Post the Business Opportunity on Craigslist under the \"Business for Sale\" category",
                "Promote the listing on Facebook in Business Buyer, Franchise, or Investor Groups",
                "Share the listing on Instagram using posts, stories, or reels",
                "Promote the listing on LinkedIn in Business Acquisition, Startup, or Investor Groups",
                "Upload a TikTok video summarizing the Business Opportunity",
                "Upload a YouTube video summarizing the Business Opportunity",
                "Launch a mass email campaign promoting the listing",
                "Distribute printed flyers or postcards in target geographic areas",
                "Launch hyperlocal or interest-based digital ad campaigns promoting the listing",
            ],
            '🛠️ Listing Preparation & Confidential Marketing' => [
                "Conduct a preliminary Seller consultation to gather details about the Business\u2019s operations, assets, and goals",
                "Provide a business sale checklist to collect financials, licenses, lease terms, and key operational details",
                "Assist with preparing a non-confidential teaser or executive summary for marketing purposes",
                "Organize internal documentation such as profit and loss statements, balance sheets, FF&E summaries, inventory lists, and staffing overviews (as available)",
                "Refer third-party professionals such as valuation experts, accountants, or financial consultants, if requested (referrals only \u2014 no endorsement or warranty is made)",
                "Compile essential marketing materials including business overviews, location descriptions, asset lists, and financial summaries",
            ],
            '📸 Photography, Video & Virtual Media' => [
                "Provide professional property photography",
                "Provide aerial (drone) photography (subject to FAA Part 107 compliance)",
                "Provide a video walkthrough tour",
                "Provide a 3D virtual tour",
                "Provide virtual staging (digital enhancements only; no physical staging)",
                "Provide digital photo enhancements",
                "Create a basic schematic floor plan (non-certified; for marketing purposes only)",
            ],
            '🏢 Showings & Access Coordination' => [
                "Respond to Buyer inquiries and screen for general qualifications",
                "Provide Non-Disclosure Agreement (NDA) templates for confidential showings or document access",
                "Ensure proper notice is provided if the property or business premises is occupied",
                "Install a real estate sign on the property",
                "Install a lockbox for Agent access",
                "Schedule and attend showings with prospective Buyers",
                "Coordinate showings with Buyer\u2019s Agents",
                "Coordinate directly with Tenant(s) or business staff to arrange access for showings",
                "Collect and relay showing feedback to the Seller",
            ],
            '📉 Offer & Contract Management' => [
                "Present all Letters of Intent (LOIs) or formal offers to the Seller and summarize key deal terms",
                "Provide the Seller with the necessary disclosure forms required by state or local law",
                "Negotiate deal terms such as purchase price, deposit structure, contingencies, transition period, and asset allocation",
                "Coordinate revisions, counteroffers, and ongoing communication with the Buyer or their representatives",
                "Manage communication with the Buyer\u2019s Broker or Buyer",
                "Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties",
                "Monitor contract contingencies and organize delivery of due diligence materials such as leases, vendor contracts, tax filings, and financial statements",
                "Refer the Seller to legal counsel for formal contract drafting and execution (referrals only \u2014 no legal advice provided)",
                "Provide referrals to Business Attorneys, Escrow Officers, or Business Transfer Specialists (referrals only \u2014 no endorsement or warranty is made)",
            ],
            '📃 Closing Coordination & Transaction Management' => [
                "Coordinate Buyer inspections, management interviews, and site visits as applicable",
                "Provide a transaction checklist and track key deadlines throughout the escrow period",
                "Coordinate with the Buyer\u2019s Attorney, Escrow Officer, or designated Closing Facilitator",
                "Review the Settlement Statement and coordinate corrections with relevant parties",
                "Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties",
                "Schedule and confirm the Final Walkthrough",
                "Schedule and confirm the Closing Appointment",
            ],
            '💡 Selling Strategy & Guidance' => [
                "Provide a business market overview with insights from recent comparable listings",
                "Identify likely Buyer types (e.g., Owner-Operator, Investor, Franchisee) and discuss common deal structures (e.g., asset sale, stock sale)",
                "Provide general insight on common value drivers such as cash flow, recurring revenue, transferable licenses, and key staff retention",
                "Provide general guidance on operational transition timelines, staff notifications, lease assignments, and post-sale training periods",
                "Provide referrals to business valuation, accounting, or legal professionals (referrals only \u2014 no endorsement or warranty is made)",
            ],
        ],
        'vacant_land' => [
            '📢 Property Marketing & Listing Promotion' => [
                "List the property in the local Multiple Listing Service (MLS)",
                "Syndicate the listing to third-party platforms (e.g., Zillow.com, Realtor.com, Trulia.com, Homes.com)",
                "List the property on LandWatch.com",
                "List the property on Land.com",
                "List the property on LandAndFarm.com",
                "Create a branded flyer highlighting lot features, zoning, and potential use",
                "Post the listing on Facebook Marketplace",
                "Post the listing on Craigslist under the \"Land for Sale\" category",
                "Share the listing on Nextdoor in Neighborhood or Rural Groups",
                "Promote the listing on Facebook in Land Buyers, Developers, or Homesteader Groups",
                "Share the listing on Instagram using posts, stories, or reels",
                "Promote the listing on LinkedIn in Land Acquisition or Investment Groups",
                "Upload a TikTok video summarizing the land opportunity",
                "Upload a YouTube video summarizing the land opportunity (e.g., drone tour, narrated overview)",
                "Launch a mass email campaign promoting the listing Distribute printed flyers or postcards in target geographic areas",
                "Launch hyperlocal or interest-based digital ad campaigns promoting the listing",
            ],
            '🛠️ Listing Preparation & Research' => [
                "Provide a checklist to gather parcel data (e.g., APN, lot size, zoning, utilities, and access)",
                "Assist with collecting public records, flood zone data, and land use information (as available)",
                "Provide referrals to surveyors, soil testers, or land service professionals (referrals only \u2014 no endorsement or warranty is made)",
            ],
            '📸 Photography, Video & Virtual Media' => [
                "Provide professional property photography",
                "Provide aerial (drone) photography (subject to FAA Part 107 compliance)",
                "Provide a video overview or narrated walkthrough",
                "Provide a 3D virtual tour (if applicable)",
                "Provide digital enhancements to media assets",
                "Provide a parcel map, topographical image, or plot plan (non-certified; for marketing purposes only)",
            ],
            '🏡 Showings & Access Coordination' => [
                "Install a real estate sign on the property",
                "Schedule and attend showings with prospective Buyers",
                "Coordinate showings with Buyer\u2019s Agents",
                "Collect and relay showing feedback to the Seller",
            ],
            '📉 Offer & Contract Management' => [
                "Present all offers to the Seller and summarize key terms, pricing, and contingencies",
                "Provide the Seller with the necessary disclosure forms required by state or local law",
                "Negotiate price, due diligence timelines, and closing terms",
                "Draft and deliver counteroffers and manage revisions to the purchase agreement",
                "Manage communication with the Buyer\u2019s Agent or Buyer",
                "Assist with in-person or electronic contract signing, including e-signature setup and secure delivery of executed purchase agreements, addenda, and disclosures to all parties",
                "Monitor contract contingencies, including survey, zoning verification, financing, and environmental reviews",
                "Provide referrals to Attorneys, Title Companies, Escrow Officers, or Land Use Professionals (referrals only \u2014 no endorsement or warranty is made)",
            ],
            '📃 Closing Coordination & Transaction Management' => [
                "Coordinate surveys, site visits, or environmental access with the Buyer or Buyer\u2019s Agent, as applicable",
                "Coordinate with Title, Escrow, and/or Attorney to prepare for Closing",
                "Review the Settlement Statement and coordinate with all parties if corrections are needed",
                "Confirm delivery of final executed documents, wire instructions, and Closing paperwork to all relevant parties",
                "Schedule and confirm the Final Walkthrough",
                "Schedule and confirm the Closing Appointment",
            ],
            '💡 Selling Strategy & Guidance' => [
                "Provide a Comparative Market Analysis (CMA) with pricing recommendations based on recent land sales, zoning categories, and location-based trends",
                "Provide general insight on permitted uses, utility access, parcel features, and Buyer demand in the area",
                "Recommend adjustments to pricing or marketing strategy if the land is not receiving sufficient interest",
                "Provide general guidance on Seller obligations, disclosure requirements, and listing preparation",
            ],
        ],
    ],
];
