<?php

return [
    'term_order' => [
        'Assumable',
        'Cryptocurrency',
        'Exchange/Trade',
        'Lease Option',
        'Lease Purchase',
        'Non-Fungible Token (NFT)',
        'Seller Financing',
    ],

    'sections' => [
        'Assumable' => [
            'header' => 'Assumable Terms',
            'icon' => 'fa-solid fa-arrow-right-arrow-left',
            'fields' => [
                ['key' => 'assumable_terms', 'label' => 'Offered Assumable Terms', 'format' => 'text'],
                ['key' => 'assumable_loan_type', 'label' => 'Type of Loan', 'format' => 'text'],
                ['key' => 'max_assumable_rate', 'label' => 'Interest Rate of Assumable Loan', 'format' => 'percent'],
                ['key' => 'max_monthly_payment', 'label' => 'Monthly Payment (Principal & Interest) for Assumable Loan', 'format' => 'money', 'alt_keys' => ['assumable_monthly_payment']],
                ['key' => 'assumable_monthly_escrow', 'label' => 'Monthly Escrow / Impounds (Informational Only)', 'format' => 'money'],
                ['key' => 'outstanding_balance', 'label' => 'Outstanding Balance on Existing Loan', 'format' => 'money', 'alt_keys' => ['assumable_balance']],
                [
                    'key' => 'gap_payment_amount',
                    'label' => 'Down Payment to Cover the Gap Between Price and Loan',
                    'format' => 'money_or_percent',
                    'type_key' => 'gap_payment_type',
                    'type_percent_value' => 'percent',
                    'alt_keys' => ['assumable_down_payment'],
                ],
                ['key' => 'assumable_loan_term_remaining', 'label' => 'Loan Term Remaining', 'format' => 'text'],
                ['key' => 'assumable_loan_origination_date', 'label' => 'Date Loan Originated', 'format' => 'text'],
                ['key' => 'assumable_loan_servicer', 'label' => 'Loan Servicer / Lender', 'format' => 'text'],
                [
                    'key' => 'assumable_fee_amount',
                    'label' => 'Assumption Fee',
                    'format' => 'money_or_percent',
                    'type_key' => 'assumable_fee_type',
                    'type_percent_value' => '%',
                ],
                [
                    'key' => 'assumable_occupancy_requirement',
                    'label' => 'Occupancy Requirement',
                    'format' => 'badge_or_other',
                    'other_value' => 'Other',
                    'other_key' => 'assumable_occupancy_other',
                ],
                ['key' => 'lender_approval', 'label' => 'Lender Approval Required', 'format' => 'badge'],
            ],
        ],

        'Cryptocurrency' => [
            'header' => 'Cryptocurrency Terms',
            'icon' => 'fa-brands fa-bitcoin',
            'fields' => [
                ['key' => 'cryptocurrency_type', 'label' => 'Acceptable Cryptocurrency', 'format' => 'text'],
                ['key' => 'crypto_percentage', 'label' => 'Percentage of Purchase Price Paid with Cryptocurrency', 'format' => 'percent', 'alt_keys' => ['cryptocurrency_percentage']],
                ['key' => 'cash_percentage_crypto', 'label' => 'Percentage of Purchase Price Paid with Cash', 'format' => 'percent'],
                ['key' => 'crypto_exchange_method', 'label' => 'Exchange / Conversion Method', 'format' => 'text'],
                ['key' => 'crypto_custodian_wallet', 'label' => 'Custodian / Wallet for Transfer', 'format' => 'text'],
                ['key' => 'crypto_transaction_fees', 'label' => 'Transaction Fees Responsibility', 'format' => 'badge'],
                [
                    'key' => 'crypto_transfer_timing',
                    'label' => 'Timing of Transfer',
                    'format' => 'badge_or_other',
                    'other_value' => 'Other',
                    'other_key' => 'crypto_transfer_timing_other',
                ],
            ],
        ],

        'Exchange/Trade' => [
            'header' => 'Exchange/Trade Terms',
            'icon' => 'fa-solid fa-exchange-alt',
            'fields' => [
                [
                    'key' => 'exchange_item',
                    'label' => 'Acceptable Exchange Item',
                    'format' => 'badge_or_other',
                    'other_value' => 'Other',
                    'other_key' => 'other_exchange_item',
                ],
                ['key' => 'exchange_item_value', 'label' => 'Estimated Value of Exchange/Trade Item', 'format' => 'money'],
                ['key' => 'exchange_item_condition', 'label' => 'Acceptable Condition of Exchange/Trade Item', 'format' => 'badge'],
                ['key' => 'additional_cash', 'label' => 'Additional Cash Seller Will Require', 'format' => 'money'],
                ['key' => 'value_determination', 'label' => 'Value of Exchange/Trade Item Determined', 'format' => 'text'],
                ['key' => 'exchange_transfer_method', 'label' => 'Transfer Method / Logistics', 'format' => 'text'],
                [
                    'key' => 'exchange_liens',
                    'label' => 'Liens / Encumbrances Disclosure',
                    'format' => 'badge_with_details',
                    'detail_trigger' => 'Yes',
                    'detail_key' => 'exchange_liens_details',
                ],
                ['key' => 'exchange_inspection_rights', 'label' => 'Inspection / Verification Rights', 'format' => 'badge'],
            ],
        ],

        'Lease Option' => [
            'header' => 'Lease Option Terms',
            'icon' => 'fa-solid fa-key',
            'fields' => [
                ['key' => 'lease_option_price', 'label' => "Seller's Desired Offering Price for Lease Option", 'format' => 'money'],
                ['key' => 'lease_option_payment', 'label' => 'Monthly Payment the Seller Will Accept', 'format' => 'money'],
                ['key' => 'lease_option_duration', 'label' => 'Proposed Duration of Lease (Months)', 'format' => 'text_with_suffix', 'suffix' => ' months'],
                ['key' => 'has_option_fee', 'label' => 'Offered Option Fee', 'format' => 'badge'],
                ['key' => 'option_fee_amount', 'label' => 'Option Fee Amount', 'format' => 'money', 'show_when' => ['key' => 'has_option_fee', 'value' => 'Yes']],
                ['key' => 'lease_option_fee', 'label' => 'Option Fee', 'format' => 'money', 'show_when' => ['key' => 'has_option_fee', 'value' => null]],
                ['key' => 'lease_option_fee_credit', 'label' => 'Option Fee Credit Toward Purchase Price', 'format' => 'badge'],
                ['key' => 'lease_option_fee_credit_percentage', 'label' => 'Percentage of Option Fee Credited', 'format' => 'percent', 'show_when' => ['key' => 'lease_option_fee_credit', 'value' => 'Partial']],
                ['key' => 'lease_option_conditions', 'label' => 'Conditions or Requirements for Lease Option', 'format' => 'text'],
                ['key' => 'lease_option_terms', 'label' => 'Specific Terms Proposed for Lease Option', 'format' => 'text'],
                ['key' => 'lease_option_maintenance', 'label' => 'Maintenance / Repair Responsibility', 'format' => 'badge'],
                ['key' => 'lease_option_extension_terms', 'label' => 'Extension Terms', 'format' => 'text'],
            ],
        ],

        'Lease Purchase' => [
            'header' => 'Lease Purchase Terms',
            'icon' => 'fa-solid fa-file-signature',
            'fields' => [
                ['key' => 'lease_purchase_price', 'label' => "Seller's Desired Offering Price for Lease Purchase", 'format' => 'money'],
                ['key' => 'lease_purchase_payment', 'label' => 'Monthly Payment the Seller Will Accept', 'format' => 'money'],
                ['key' => 'lease_purchase_duration', 'label' => 'Proposed Duration of Lease (Months)', 'format' => 'text'],
                [
                    'key' => 'lease_purchase_rent_credit',
                    'label' => 'Rent Credit Toward Purchase Price',
                    'format' => 'badge_with_details',
                    'detail_trigger' => ['Yes', 'Partial'],
                    'detail_key' => 'lease_purchase_rent_credit_amount',
                    'detail_format' => 'money',
                ],
                ['key' => 'lease_purchase_deposit', 'label' => 'Non-Refundable Deposit / Purchase Deposit', 'format' => 'money'],
                ['key' => 'lease_purchase_conditions', 'label' => 'Conditions or Requirements for Lease Purchase', 'format' => 'text'],
                ['key' => 'lease_purchase_terms', 'label' => 'Specific Terms Proposed for Lease Purchase', 'format' => 'text'],
                ['key' => 'lease_purchase_maintenance', 'label' => 'Maintenance / Repair Responsibility', 'format' => 'badge'],
                ['key' => 'lease_purchase_extension_terms', 'label' => 'Extension Terms', 'format' => 'text'],
                ['key' => 'lease_purchase_option_fee', 'label' => 'Option Fee', 'format' => 'badge'],
                ['key' => 'lease_purchase_option_fee_amount', 'label' => 'Option Fee Amount', 'format' => 'money', 'show_when' => ['key' => 'lease_purchase_option_fee', 'value' => 'Yes']],
            ],
        ],

        'Non-Fungible Token (NFT)' => [
            'header' => 'Non-Fungible Token (NFT) Terms',
            'icon' => 'fa-solid fa-image',
            'fields' => [
                ['key' => 'nft_description', 'label' => 'Acceptable Non-Fungible Token (NFT)', 'format' => 'text'],
                ['key' => 'nft_percentage', 'label' => 'Percentage of Purchase Price Acceptable as NFT', 'format' => 'percent'],
                ['key' => 'cash_percentage_nft', 'label' => 'Percentage of Purchase Price Acceptable as Cash', 'format' => 'percent'],
                ['key' => 'nft_valuation_method', 'label' => 'NFT Valuation Method', 'format' => 'text'],
                ['key' => 'nft_transfer_method', 'label' => 'NFT Transfer Method', 'format' => 'text'],
                ['key' => 'nft_gas_fees', 'label' => 'Transaction Fees Responsibility (Gas Fees)', 'format' => 'badge'],
            ],
        ],

        'Seller Financing' => [
            'header' => 'Seller Financing Terms',
            'icon' => 'fa-solid fa-handshake',
            'fields' => [
                ['key' => 'purchase_price', 'label' => 'Purchase Price', 'format' => 'money'],
                [
                    'key' => 'down_payment_amount',
                    'label' => 'Down Payment',
                    'format' => 'money_or_percent',
                    'type_key' => 'down_payment_type',
                    'type_percent_value' => '%',
                ],
                [
                    'key' => 'seller_down_payment_amount',
                    'label' => 'Seller Financing',
                    'format' => 'money_or_percent',
                    'type_key' => 'seller_financing_type',
                    'type_percent_value' => '%',
                    'alt_keys' => ['seller_financing_amount'],
                ],
                ['key' => 'interest_rate', 'label' => 'Interest Rate', 'format' => 'percent', 'alt_keys' => ['seller_financing_interest_rate']],
                ['key' => 'loan_duration', 'label' => 'Loan Duration (Years)', 'format' => 'text', 'alt_keys' => ['seller_financing_term']],
                ['key' => 'prepayment_penalty', 'label' => 'Prepayment Penalty', 'format' => 'badge'],
                ['key' => 'prepayment_penalty_amount', 'label' => 'Prepayment Penalty Amount', 'format' => 'money', 'show_when' => ['key' => 'prepayment_penalty', 'value' => 'Yes']],
                ['key' => 'balloon_payment', 'label' => 'Balloon Payment', 'format' => 'badge'],
                ['key' => 'balloon_payment_amount', 'label' => 'Balloon Payment Amount', 'format' => 'money', 'show_when' => ['key' => 'balloon_payment', 'value' => 'Yes']],
                ['key' => 'balloon_payment_date', 'label' => 'Balloon Payment Due Date', 'format' => 'text', 'show_when' => ['key' => 'balloon_payment', 'value' => 'Yes']],
                [
                    'key' => 'seller_amortization_type',
                    'label' => 'Amortization Type',
                    'format' => 'badge_or_other',
                    'other_value' => 'Other',
                    'other_key' => 'seller_amortization_other',
                ],
                [
                    'key' => 'seller_payment_frequency',
                    'label' => 'Payment Frequency',
                    'format' => 'badge_or_other',
                    'other_value' => 'Other',
                    'other_key' => 'seller_payment_frequency_other',
                ],
                ['key' => 'seller_late_fee_amount', 'label' => 'Late Payment Fee', 'format' => 'text'],
            ],
        ],
    ],
];
