<h3>Financial Details</h3>
<div class="alert alert-info bg-light-info border-info mb-4">
    <div class="d-flex align-items-center">
        <div>
            <strong>💰 Enter the financial details for your property. All fields are optional but help agents and buyers understand the property's financial profile.</strong>
        </div>
    </div>
</div>

{{-- ============================================================ --}}
{{-- INCOME PROPERTY --}}
{{-- ============================================================ --}}
@if ($property_type === 'Income')
    <h5 class="fw-bold text-primary border-bottom pb-2 mb-3">Income Property Financial Details (Optional)</h5>

    {{-- Annual Net Income (moved from Property Details) --}}
    <div class="form-group">
        <label class="fw-bold">Annual Net Income:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the annual net income the property generates after all operating expenses.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="minimum_annual_net_income" class="form-control"
                placeholder="Enter annual net income (e.g., 85000)"
                data-error-id="minimum_annual_net_income_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="minimum_annual_net_income_error"></span>
    </div>

    {{-- Cap Rate (moved from Property Details) --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Cap Rate:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the capitalization rate (Cap Rate), which reflects the property's income potential relative to its price. Formula: Cap Rate = Net Operating Income ÷ Purchase Price">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <input type="text" wire:model.defer="minimum_cap_rate" class="form-control percentage-value-set"
                placeholder="Enter cap rate (e.g., 6.5)"
                data-error-id="minimum_cap_rate_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
            <span class="input-group-text-seller">%</span>
        </div>
        <span class="error mt-2" id="minimum_cap_rate_error"></span>
    </div>

    {{-- Gross Annual Income --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Gross Annual Income:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the total gross annual rental income generated by the property before any expenses.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="gross_annual_income" class="form-control"
                placeholder="Enter gross annual income (e.g., 120000)"
                data-error-id="gross_annual_income_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="gross_annual_income_error"></span>
    </div>

    {{-- Annual Operating Expenses --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Annual Operating Expenses:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the total annual operating expenses for the property (e.g., maintenance, insurance, taxes, management fees).">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="annual_operating_expenses" class="form-control"
                placeholder="Enter annual operating expenses (e.g., 35000)"
                data-error-id="annual_operating_expenses_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="annual_operating_expenses_error"></span>
    </div>

    {{-- Rent Roll Available --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Rent Roll Available:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Indicate whether a current rent roll (list of tenants, lease terms, and rents) is available for review.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <select wire:model.defer="rent_roll_available" class="form-control has-icon"
                data-icon="fa-solid fa-file-invoice">
                <option value="">Select</option>
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
        </div>
    </div>

    {{-- Operating Statement Available --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Operating Statement Available:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Indicate whether a current operating/income statement is available for review.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <i class="input-icon fa-solid fa-file-chart-column"></i>
            <select wire:model.defer="operating_statement_available" class="form-control has-icon"
                data-icon="fa-solid fa-file-chart-column">
                <option value="">Select</option>
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
        </div>
    </div>
@endif

{{-- ============================================================ --}}
{{-- COMMERCIAL PROPERTY --}}
{{-- ============================================================ --}}
@if ($property_type === 'Commercial')
    <h5 class="fw-bold text-primary border-bottom pb-2 mb-3">Commercial Financial &amp; Lease Details (Optional)</h5>

    {{-- Annual Net Income (moved from Property Details) --}}
    <div class="form-group">
        <label class="fw-bold">Annual Net Income:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the annual net income the property generates after all operating expenses.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="minimum_annual_net_income" class="form-control"
                placeholder="Enter annual net income (e.g., 85000)"
                data-error-id="minimum_annual_net_income_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="minimum_annual_net_income_error"></span>
    </div>

    {{-- Cap Rate (moved from Property Details) --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Cap Rate:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the capitalization rate (Cap Rate), which reflects the property's income potential relative to its price. Formula: Cap Rate = Net Operating Income ÷ Purchase Price">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <input type="text" wire:model.defer="minimum_cap_rate" class="form-control percentage-value-set"
                placeholder="Enter cap rate (e.g., 6.5)"
                data-error-id="minimum_cap_rate_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
            <span class="input-group-text-seller">%</span>
        </div>
        <span class="error mt-2" id="minimum_cap_rate_error"></span>
    </div>

    {{-- Price Per Square Foot --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Price Per Square Foot:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the asking price per square foot of leasable/usable space.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="price_per_sqft" class="form-control"
                placeholder="Enter price per sq ft (e.g., 125)"
                data-error-id="price_per_sqft_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="price_per_sqft_error"></span>
    </div>

    {{-- Existing Lease Type --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Existing Lease Type:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Select the type of lease currently in place on the property, if any.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <select wire:model.defer="existing_lease_type" class="form-control has-icon"
                data-icon="fa-solid fa-file-contract">
                <option value="">Select</option>
                <option value="NNN (Triple Net)">NNN (Triple Net)</option>
                <option value="NN (Double Net)">NN (Double Net)</option>
                <option value="Net">Net</option>
                <option value="Gross">Gross</option>
                <option value="Modified Gross">Modified Gross</option>
                <option value="Absolute Net">Absolute Net</option>
                <option value="Ground Lease">Ground Lease</option>
                <option value="No Existing Lease">No Existing Lease</option>
                <option value="Other">Other</option>
            </select>
        </div>
    </div>

    @if ($existing_lease_type === 'Other')
        <div class="form-group mt-2">
            <div class="input-cover">
                <input type="text" wire:model.defer="other_lease_type" class="form-control has-icon"
                    data-icon="fa-solid fa-file-contract"
                    placeholder="Enter Existing Lease Type (e.g., Month-to-Month)">
            </div>
        </div>
    @endif

    {{-- Lease Expiration Date --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Lease Expiration Date:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the date the existing lease expires, if applicable.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <input type="date" wire:model.defer="lease_expiration" class="form-control has-icon"
                data-icon="fa-regular fa-calendar-days">
        </div>
    </div>

    {{-- Lease Assignable --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Lease Assignable to Buyer:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Indicate whether the existing lease can be assigned or transferred to the new buyer.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <select wire:model.defer="lease_assignable" class="form-control has-icon"
                data-icon="fa-solid fa-arrow-right-arrow-left">
                <option value="">Select</option>
                <option value="Yes">Yes</option>
                <option value="No">No</option>
                <option value="Negotiable">Negotiable</option>
            </select>
        </div>
    </div>
@endif

{{-- ============================================================ --}}
{{-- BUSINESS PROPERTY --}}
{{-- ============================================================ --}}
@if ($property_type === 'Business')
    <h5 class="fw-bold text-primary border-bottom pb-2 mb-3">Business Financial Details (Optional)</h5>

    {{-- Annual Net Income (moved from Property Details) --}}
    <div class="form-group">
        <label class="fw-bold">Annual Net Income:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the annual net income the business generates after all operating expenses.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="minimum_annual_net_income" class="form-control"
                placeholder="Enter annual net income (e.g., 85000)"
                data-error-id="minimum_annual_net_income_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="minimum_annual_net_income_error"></span>
    </div>

    {{-- Cap Rate (moved from Property Details) --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Cap Rate:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the capitalization rate (Cap Rate), which reflects the business's income potential relative to its price. Formula: Cap Rate = Net Operating Income ÷ Purchase Price">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <input type="text" wire:model.defer="minimum_cap_rate" class="form-control percentage-value-set"
                placeholder="Enter cap rate (e.g., 6.5)"
                data-error-id="minimum_cap_rate_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
            <span class="input-group-text-seller">%</span>
        </div>
        <span class="error mt-2" id="minimum_cap_rate_error"></span>
    </div>

    {{-- Annual Revenue --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Annual Revenue:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the total annual gross revenue generated by the business.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="annual_revenue" class="form-control"
                placeholder="Enter annual revenue (e.g., 500000)"
                data-error-id="annual_revenue_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="annual_revenue_error"></span>
    </div>

    {{-- Gross Profit --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Gross Profit:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the gross profit (revenue minus cost of goods sold).">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="gross_profit" class="form-control"
                placeholder="Enter gross profit (e.g., 200000)"
                data-error-id="gross_profit_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="gross_profit_error"></span>
    </div>

    {{-- SDE / EBITDA --}}
    <div class="form-group mt-3">
        <label class="fw-bold">SDE / EBITDA:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the Seller's Discretionary Earnings (SDE) or Earnings Before Interest, Taxes, Depreciation, and Amortization (EBITDA). These are key metrics used in business valuations.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="sde_ebitda" class="form-control"
                placeholder="Enter SDE / EBITDA (e.g., 150000)"
                data-error-id="sde_ebitda_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="sde_ebitda_error"></span>
    </div>

    {{-- Inventory Value --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Inventory Value:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the estimated current value of business inventory included in the sale.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="inventory_value" class="form-control"
                placeholder="Enter inventory value (e.g., 50000)"
                data-error-id="inventory_value_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="inventory_value_error"></span>
    </div>

    {{-- FF&E Value --}}
    <div class="form-group mt-3">
        <label class="fw-bold">FF&amp;E Value (Furniture, Fixtures &amp; Equipment):</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the estimated value of furniture, fixtures, and equipment included in the business sale.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <span class="input-group-text-seller">$</span>
            <input type="text" wire:model.defer="ffe_value" class="form-control"
                placeholder="Enter FF&E value (e.g., 75000)"
                data-error-id="ffe_value_error"
                oninput="validateInput(this)" onblur="reformatNumber(this)" onpaste="handlePaste(event)">
        </div>
        <span class="error mt-2" id="ffe_value_error"></span>
    </div>

    {{-- Reason for Sale --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Reason for Sale:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Select the primary reason the business is being sold.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <select id="reason_for_sale_select" wire:model.defer="reason_for_sale" class="form-control has-icon"
                data-icon="fa-solid fa-tag">
                <option value="">Select</option>
                <option value="Retirement">Retirement</option>
                <option value="Relocation">Relocation</option>
                <option value="Health Reasons">Health Reasons</option>
                <option value="Pursuing Other Opportunities">Pursuing Other Opportunities</option>
                <option value="Partnership Dissolution">Partnership Dissolution</option>
                <option value="Financial Reasons">Financial Reasons</option>
                <option value="Other">Other</option>
            </select>
        </div>
    </div>

    @if ($reason_for_sale === 'Other')
        <div class="form-group mt-2">
            <div class="input-cover">
                <input type="text" wire:model.defer="other_reason_for_sale" class="form-control has-icon"
                    data-icon="fa-solid fa-tag"
                    placeholder="Enter Reason for Sale (e.g., Relocation)">
            </div>
        </div>
    @endif

    {{-- Employee Count --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Number of Employees:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Enter the current number of employees (full-time and part-time).">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <input type="number" wire:model.defer="employee_count" class="form-control has-icon"
                data-icon="fa-solid fa-users"
                placeholder="Enter number of employees (e.g., 12)" min="0">
        </div>
    </div>

    {{-- Financial Statements Available --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Financial Statements Available:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Indicate whether financial statements (P&L, balance sheet) are available for qualified buyers.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <select wire:model.defer="financial_statements_available" class="form-control has-icon"
                data-icon="fa-solid fa-file-invoice-dollar">
                <option value="">Select</option>
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
        </div>
    </div>

    {{-- Tax Returns Available --}}
    <div class="form-group mt-3">
        <label class="fw-bold">Tax Returns Available:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Indicate whether business tax returns are available for qualified buyers.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <select wire:model.defer="tax_returns_available" class="form-control has-icon"
                data-icon="fa-solid fa-receipt">
                <option value="">Select</option>
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
        </div>
    </div>

    {{-- NDA Required --}}
    <div class="form-group mt-3">
        <label class="fw-bold">NDA Required to Access Financials:</label>
        <span class="ms-2" data-bs-toggle="tooltip" data-bs-html="true"
            title="Indicate whether a Non-Disclosure Agreement (NDA) must be signed before financial details are shared with prospective buyers.">
            <i class="fa-solid fa-circle-info"></i>
        </span>
        <div class="input-cover">
            <select wire:model.defer="nda_required" class="form-control has-icon"
                data-icon="fa-solid fa-file-shield">
                <option value="">Select</option>
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
        </div>
    </div>
@endif
