<?php

namespace App\Services\Dna;

use App\Models\BuyerTenantDnaProfile;

/**
 * BuyerTenantMarketingContextService — Phase P Deterministic Marketing Context Builder
 *
 * GOVERNANCE BLOCK:
 * ==================================================================================
 * This service is a COMPOSING TRANSLATION LAYER ONLY. It calls
 * BuyerTenantDnaExplanationService to obtain Phase O explanation records and
 * reorganizes those records into named marketing context category buckets.
 *
 * This service MUST NEVER:
 *   - Generate marketing copy, ad copy, listing descriptions, or any narrative text.
 *   - Perform audience targeting, buyer persona inference, or demographic grouping.
 *   - Apply protected-class inference of any kind.
 *   - Rank, sort, order, or weight any tag, flag, or group by any signal.
 *   - Endorse, steer toward, or evaluate any listing, buyer, tenant, seller, or agent.
 *   - Determine fitness, screening, acceptance, or rejection for any party or property.
 *   - Forecast any outcome, likelihood, or probability of any transaction event.
 *   - Perform AI reasoning, language model inference, embedding lookup, or ML logic.
 *   - Call any external service, API, or AI endpoint of any kind.
 *   - Change, recalculate, modify, or influence any DNA profile, score, or metric.
 *   - Introduce new explanation strings — all explanation text originates from Phase O.
 *   - Normalize, reformat, or transform any tag string, flag key, or value string.
 *   - Surface output in any user-facing view, API, PDF, email, or cache layer.
 *
 * All tag strings, flag keys, source field strings, and values are passed through
 * verbatim from Phase O explanation records. No new strings are generated by this
 * service. Output order within each bucket reflects Phase O input order; no
 * reordering is applied within any bucket.
 * ==================================================================================
 */
class BuyerTenantMarketingContextService
{
    /**
     * Maps each lifestyle tag prefix (or bare tag) to a named preference bucket.
     *
     * For bare tags (no colon separator, e.g. `has-pets`), the full tag string is
     * used as the lookup key, matching the same logic used in Phase O.
     *
     * Every prefix and bare tag emitted by BuyerTenantDnaGenerator::buildLifestyleTags()
     * is covered. Unrecognized prefixes are routed to preference_context.unrecognized
     * so no tag is silently dropped.
     */
    private const LIFESTYLE_GROUP_MAP = [
        'prefers-type'      => 'property_type_preference',
        'prefers-condition' => 'property_condition_preference',
        'has-pets'          => 'occupant_signals',
        'seeks'             => 'community_signals',
        'requires'          => 'required_amenities',
        'open-to'           => 'transaction_openness',
        'financial'         => 'financial_signals',
        'preference'        => 'policy_preferences',
    ];

    public function __construct(
        private readonly BuyerTenantDnaExplanationService $explanationService
    ) {}

    /**
     * Build a structured marketing context array from a persisted BuyerTenantDnaProfile.
     *
     * Calls BuyerTenantDnaExplanationService::generate() to obtain Phase O explanation
     * records for lifestyle tags and deal-breaker flags, then groups lifestyle tag
     * records by prefix (or bare tag) into named preference category buckets.
     * Deal-breaker flag records are passed through to requirements_context unchanged.
     *
     * All named bucket arrays are always present in output, even when empty.
     * Unrecognized tag prefixes or bare tags are placed in preference_context.unrecognized
     * so no tag present in the persisted data is silently dropped.
     *
     * Output structure:
     * [
     *     'preference_context' => [
     *         'property_type_preference'      => [ ['tag' => string, 'explanation' => string], ... ],
     *         'property_condition_preference' => [ ... ],
     *         'occupant_signals'              => [ ... ],
     *         'community_signals'             => [ ... ],
     *         'required_amenities'            => [ ... ],
     *         'transaction_openness'          => [ ... ],
     *         'financial_signals'             => [ ... ],
     *         'policy_preferences'            => [ ... ],
     *         'unrecognized'                  => [ ... ],   // populated only if unknown prefix found
     *     ],
     *     'requirements_context' => [
     *         [
     *             'flag'         => string,
     *             'source_field' => string,
     *             'value'        => string|null,
     *             'explanation'  => string,
     *         ],
     *         ...
     *     ],
     *     'summary' => [
     *         'total_lifestyle_tags'        => int,
     *         'total_deal_breaker_flags'    => int,
     *         'non_empty_preference_groups' => int,
     *         'has_hard_requirements'       => bool,
     *     ],
     * ]
     *
     * Output order within each bucket reflects Phase O input order (input order
     * from the persisted array). No reordering is applied within any bucket.
     *
     * @param  BuyerTenantDnaProfile $profile  A persisted, cast profile model instance.
     * @return array
     */
    public function build(BuyerTenantDnaProfile $profile): array
    {
        $explanations = $this->explanationService->generate($profile);

        $lifestyleTagRecords   = (array) ($explanations['lifestyle_tag_explanations'] ?? []);
        $dealBreakerRecords    = (array) ($explanations['deal_breaker_explanations']  ?? []);

        $context = $this->buildEmptyContext();

        foreach ($lifestyleTagRecords as $record) {
            $record = (array) $record;
            $tag    = (string) ($record['tag'] ?? '');

            $colonPos  = strpos($tag, ':');
            $lookupKey = ($colonPos !== false) ? substr($tag, 0, $colonPos) : $tag;

            if (isset(self::LIFESTYLE_GROUP_MAP[$lookupKey])) {
                $bucket = self::LIFESTYLE_GROUP_MAP[$lookupKey];
            } else {
                $bucket = 'unrecognized';
            }

            $context['preference_context'][$bucket][] = $record;
        }

        $context['requirements_context'] = $dealBreakerRecords;

        $context['summary'] = [
            'total_lifestyle_tags'        => count($lifestyleTagRecords),
            'total_deal_breaker_flags'    => count($dealBreakerRecords),
            'non_empty_preference_groups' => $this->countNonEmpty($context['preference_context']),
            'has_hard_requirements'       => count($dealBreakerRecords) > 0,
        ];

        return $context;
    }

    /**
     * Initialise the full output structure with all named bucket arrays present and
     * empty. This ensures no bucket key is absent from the output even when a profile
     * has no tags matching that bucket.
     *
     * unrecognized bucket is included so it is always structurally present, ready to
     * receive any tag whose prefix is not covered by LIFESTYLE_GROUP_MAP.
     */
    private function buildEmptyContext(): array
    {
        return [
            'preference_context' => [
                'property_type_preference'      => [],
                'property_condition_preference' => [],
                'occupant_signals'              => [],
                'community_signals'             => [],
                'required_amenities'            => [],
                'transaction_openness'          => [],
                'financial_signals'             => [],
                'policy_preferences'            => [],
                'unrecognized'                  => [],
            ],
            'requirements_context' => [],
            'summary'              => [],
        ];
    }

    /**
     * Count the number of non-empty (at least one record) arrays within a context group.
     *
     * @param  array $group  An associative array of bucket_name => records[].
     * @return int
     */
    private function countNonEmpty(array $group): int
    {
        $count = 0;
        foreach ($group as $records) {
            if (!empty($records)) {
                $count++;
            }
        }
        return $count;
    }
}
