<?php

namespace App\Services\Dna;

use App\Models\PropertyDnaProfile;

/**
 * PropertyMarketingContextService — Phase P Deterministic Marketing Context Builder
 *
 * GOVERNANCE BLOCK:
 * ==================================================================================
 * This service is a COMPOSING TRANSLATION LAYER ONLY. It calls
 * PropertyDnaExplanationService to obtain Phase O explanation records and
 * reorganizes those records into named marketing context category buckets.
 *
 * This service MUST NEVER:
 *   - Generate marketing copy, ad copy, listing descriptions, or any narrative text.
 *   - Perform audience targeting, buyer persona inference, or demographic grouping.
 *   - Apply protected-class inference of any kind.
 *   - Rank, sort, order, or weight any tag, hook, or group by any signal.
 *   - Endorse, steer toward, or evaluate any listing, buyer, tenant, seller, or agent.
 *   - Determine fitness, screening, acceptance, or rejection for any party or property.
 *   - Forecast any outcome, likelihood, or probability of any transaction event.
 *   - Perform AI reasoning, language model inference, embedding lookup, or ML logic.
 *   - Call any external service, API, or AI endpoint of any kind.
 *   - Change, recalculate, modify, or influence any DNA profile, score, or metric.
 *   - Introduce new explanation strings — all explanation text originates from Phase O.
 *   - Normalize, reformat, or transform any tag string, trait key, or value string.
 *   - Surface output in any user-facing view, API, PDF, email, or cache layer.
 *
 * All tag strings, trait keys, and values are passed through verbatim from Phase O
 * explanation records. No new strings are generated by this service.
 * Output order within each bucket reflects Phase O input order; no reordering is
 * applied within any bucket.
 * ==================================================================================
 */
class PropertyMarketingContextService
{
    /**
     * Maps each of the 14 archetype tag prefixes to a [context_key, bucket_name] pair.
     *
     * attribute_context — physical and policy characteristics of the property.
     * transaction_context — terms and structure of the transaction.
     *
     * Every prefix emitted by PropertyDnaGenerator::buildArchetypeTags() is covered.
     * Unrecognized prefixes are routed to attribute_context.unrecognized so no tag
     * is silently dropped.
     */
    private const TAG_GROUP_MAP = [
        // attribute_context groups
        'type'       => ['attribute_context', 'property_type'],
        'style'      => ['attribute_context', 'property_style'],
        'condition'  => ['attribute_context', 'property_condition'],
        'amenity'    => ['attribute_context', 'amenities'],
        'parking'    => ['attribute_context', 'parking'],
        'feature'    => ['attribute_context', 'features'],
        'policy'     => ['attribute_context', 'policies'],
        'community'  => ['attribute_context', 'community'],
        'use'        => ['attribute_context', 'use_classification'],
        'governance' => ['attribute_context', 'governance'],
        // transaction_context groups
        'timing'     => ['transaction_context', 'timing'],
        'structure'  => ['transaction_context', 'transaction_structure'],
        'financing'  => ['transaction_context', 'financing'],
        'marketing'  => ['transaction_context', 'presentation'],
    ];

    public function __construct(
        private readonly PropertyDnaExplanationService $explanationService
    ) {}

    /**
     * Build a structured marketing context array from a persisted PropertyDnaProfile.
     *
     * Calls PropertyDnaExplanationService::generate() to obtain Phase O explanation
     * records for archetype tags and marketing hooks, then groups archetype tag
     * records by prefix into named category buckets. Marketing hook records are
     * passed through to quantitative_context unchanged.
     *
     * All named bucket arrays are always present in output, even when empty.
     * Unrecognized tag prefixes are placed in attribute_context.unrecognized so no
     * tag present in the persisted data is silently dropped.
     *
     * Output structure:
     * [
     *     'attribute_context' => [
     *         'property_type'      => [ ['tag' => string, 'explanation' => string], ... ],
     *         'property_style'     => [ ... ],
     *         'property_condition' => [ ... ],
     *         'amenities'          => [ ... ],
     *         'parking'            => [ ... ],
     *         'features'           => [ ... ],
     *         'policies'           => [ ... ],
     *         'community'          => [ ... ],
     *         'use_classification' => [ ... ],
     *         'governance'         => [ ... ],
     *         'unrecognized'       => [ ... ],   // populated only if unknown prefix found
     *     ],
     *     'transaction_context' => [
     *         'timing'                => [ ['tag' => string, 'explanation' => string], ... ],
     *         'transaction_structure' => [ ... ],
     *         'financing'             => [ ... ],
     *         'presentation'          => [ ... ],
     *         'unrecognized'          => [ ... ],   // populated only if unknown prefix found
     *     ],
     *     'quantitative_context' => [
     *         ['trait' => string, 'value' => string, 'explanation' => string],
     *         ...
     *     ],
     *     'summary' => [
     *         'total_archetype_tags'        => int,
     *         'total_marketing_hooks'       => int,
     *         'non_empty_attribute_groups'  => int,
     *         'non_empty_transaction_groups'=> int,
     *     ],
     * ]
     *
     * Output order within each bucket reflects Phase O input order (input order
     * from the persisted array). No reordering is applied within any bucket.
     *
     * @param  PropertyDnaProfile $profile  A persisted, cast profile model instance.
     * @return array
     */
    public function build(PropertyDnaProfile $profile): array
    {
        $explanations = $this->explanationService->generate($profile);

        $archetypeTagRecords  = (array) ($explanations['archetype_tag_explanations']  ?? []);
        $marketingHookRecords = (array) ($explanations['marketing_hook_explanations'] ?? []);

        $context = $this->buildEmptyContext();

        foreach ($archetypeTagRecords as $record) {
            $record = (array) $record;
            $tag    = (string) ($record['tag'] ?? '');

            $colonPos = strpos($tag, ':');
            $prefix   = ($colonPos !== false) ? substr($tag, 0, $colonPos) : $tag;

            if (isset(self::TAG_GROUP_MAP[$prefix])) {
                [$contextKey, $bucket] = self::TAG_GROUP_MAP[$prefix];
            } else {
                $contextKey = 'attribute_context';
                $bucket     = 'unrecognized';
            }

            $context[$contextKey][$bucket][] = $record;
        }

        $context['quantitative_context'] = $marketingHookRecords;

        $context['summary'] = [
            'total_archetype_tags'         => count($archetypeTagRecords),
            'total_marketing_hooks'        => count($marketingHookRecords),
            'non_empty_attribute_groups'   => $this->countNonEmpty($context['attribute_context']),
            'non_empty_transaction_groups' => $this->countNonEmpty($context['transaction_context']),
        ];

        return $context;
    }

    /**
     * Initialise the full output structure with all named bucket arrays present and
     * empty. This ensures no bucket key is absent from the output even when a profile
     * has no tags matching that bucket.
     *
     * unrecognized buckets are included so they are always structurally present,
     * ready to receive any tag whose prefix is not covered by TAG_GROUP_MAP.
     */
    private function buildEmptyContext(): array
    {
        return [
            'attribute_context' => [
                'property_type'      => [],
                'property_style'     => [],
                'property_condition' => [],
                'amenities'          => [],
                'parking'            => [],
                'features'           => [],
                'policies'           => [],
                'community'          => [],
                'use_classification' => [],
                'governance'         => [],
                'unrecognized'       => [],
            ],
            'transaction_context' => [
                'timing'                => [],
                'transaction_structure' => [],
                'financing'             => [],
                'presentation'          => [],
                'unrecognized'          => [],
            ],
            'quantitative_context' => [],
            'summary'              => [],
        ];
    }

    /**
     * Count the number of non-empty (at least one record) arrays within a context group.
     *
     * @param  array $group  An associative array of bucket_name => records[].
     * @return int
     */
    private function countNonEmpty(array $group): int
    {
        $count = 0;
        foreach ($group as $records) {
            if (!empty($records)) {
                $count++;
            }
        }
        return $count;
    }
}
