<?php

namespace App\Services\Dna;

use App\Models\PropertyDnaProfile;
use App\Services\LocationDna\LocationDnaIntelligenceContextService;

/**
 * PropertyIntelligenceProfileService — Property Intelligence Profile (V1)
 *
 * GOVERNANCE BLOCK:
 * ==================================================================================
 * ROLE: Downstream intelligence assembly layer. This service reads a persisted
 * PropertyDnaProfile, assembles a unified Property Intelligence Profile using
 * deterministic rules, and integrates Location DNA context.
 *
 * ARCHITECTURAL DECISION — location_intelligence_context persistence:
 * This service performs exactly one bounded database write: it persists
 * location_intelligence_context back onto the PropertyDnaProfile record.
 * This write is intentional and scoped to a single nullable JSON column that
 * PropertyDnaGenerator cannot populate (it has no access to LocationDna).
 * The column exists specifically as the storage home for this data; caching it
 * on the profile avoids re-querying property_location_dna on every downstream
 * read. No other column, table, or record is written. If future architecture
 * moves location context persistence to a dedicated job, remove the save() call
 * here and update this comment.
 *
 * This service MUST NEVER:
 *   - Call PropertyDnaGenerator or trigger DNA generation of any kind.
 *   - Write to any column other than location_intelligence_context on PropertyDnaProfile.
 *   - Call any AI, OpenAI, language model, embedding, ML, or external HTTP service.
 *   - Rank, sort, or order output by any score, metric, or signal.
 *   - Recommend any listing, buyer, seller, landlord, tenant, or agent.
 *   - Determine, infer, or output suitability, qualification, approval, or rejection.
 *   - Predict any outcome, likelihood, or probability of any transaction event.
 *   - Generate narrative persuasion copy, endorsements, or matchmaking language.
 *   - Recalculate, modify, or reinterpret any stored DNA score or completeness value.
 *   - Surface output in any user-facing view, API, PDF, email, or cache layer.
 *
 * All intelligence outputs are deterministic and reproducible from persisted
 * PropertyDnaProfile data and LocationDnaIntelligenceContextService output.
 * ==================================================================================
 */
class PropertyIntelligenceProfileService
{
    /**
     * Version marker included in every output. Increment this constant when the
     * intelligence profile schema changes in a backward-incompatible way, enabling
     * callers to detect and migrate stale cached outputs.
     */
    public const PROPERTY_INTELLIGENCE_VERSION = 'PROPERTY_INTELLIGENCE_V1';

    /**
     * Consolidated strength tag map covering both seller and landlord listing signals.
     * Only archetype tags listed here produce a strength label.
     *
     * Key   = full archetype tag string (as generated by PropertyDnaGenerator)
     * Value = human-readable strength label
     */
    private const STRENGTH_MAP = [
        'amenity:pool'                       => 'Pool',
        'amenity:waterfront'                 => 'Waterfront',
        'feature:waterfront'                 => 'Waterfront',
        'parking:garage'                     => 'Garage',
        'parking:carport'                    => 'Carport Parking',
        'feature:storage'                    => 'Storage',
        'policy:pets-allowed'                => 'Pet-Friendly',
        'amenity:furnished'                  => 'Furnished',
        'feature:furnished'                  => 'Furnished',
        'feature:furnishing-terms-specified' => 'Furnished Terms Specified',
        'structure:lease-option'             => 'Lease Option',
        'structure:lease-purchase'           => 'Lease Purchase',
        'financing:seller-financed'          => 'Seller Financing',
        'financing:assumable'                => 'Assumable Loan',
        'marketing:video-tour'               => 'Video Tour Available',
        'timing:move-in-specified'           => 'Move-In Timing Specified',
    ];

    /**
     * Highlight tag map: a flat consumable list of headline property attributes
     * for downstream use by Marketing Intelligence, Ask AI, listing widgets, and
     * shareable reports. Overlap with STRENGTH_MAP labels is acceptable — the two
     * arrays serve different consumers.
     *
     * Key   = full archetype tag string
     * Value = canonical headline label
     */
    private const HIGHLIGHT_MAP = [
        'amenity:pool'               => 'Pool',
        'amenity:waterfront'         => 'Waterfront',
        'feature:waterfront'         => 'Waterfront',
        'parking:garage'             => 'Garage',
        'parking:carport'            => 'Carport',
        'feature:storage'            => 'Storage',
        'policy:pets-allowed'        => 'Pets Allowed',
        'amenity:furnished'          => 'Furnished',
        'feature:furnished'          => 'Furnished',
        'structure:lease-option'     => 'Lease Option',
        'structure:lease-purchase'   => 'Lease Purchase',
        'financing:seller-financed'  => 'Seller Financing',
        'financing:assumable'        => 'Assumable Loan',
        'marketing:video-tour'       => 'Video Tour',
        'community:55-plus'          => '55+ Community',
        'use:commercial'             => 'Commercial Use Eligible',
        'governance:hoa'             => 'HOA Community',
    ];

    /**
     * Positioning label constants (deterministic, one per property).
     */
    private const POSITIONING_COMMERCIAL   = 'Commercial Property';
    private const POSITIONING_RETIREMENT   = 'Retirement Home';
    private const POSITIONING_INVESTMENT   = 'Investment Property';
    private const POSITIONING_VACATION     = 'Vacation Home';
    private const POSITIONING_LUXURY       = 'Luxury Home';
    private const POSITIONING_STARTER      = 'Starter Home';
    private const POSITIONING_MOVE_UP      = 'Move-Up Home';

    /**
     * Financial score threshold used for investment and starter home classification.
     * Profiles with financial_score above this threshold show investment signal strength.
     */
    private const INVESTMENT_FINANCIAL_THRESHOLD = 60.0;

    /**
     * Physical score threshold used for luxury classification.
     */
    private const LUXURY_PHYSICAL_THRESHOLD = 75.0;

    private LocationDnaIntelligenceContextService $locationContextService;

    public function __construct(LocationDnaIntelligenceContextService $locationContextService)
    {
        $this->locationContextService = $locationContextService;
    }

    /**
     * Generate a unified Property Intelligence Profile from a persisted PropertyDnaProfile.
     *
     * Calls LocationDnaIntelligenceContextService to retrieve location context, persists
     * location_intelligence_context back to the profile record, and returns the full
     * intelligence profile array.
     *
     * Output contract — always returns exactly these keys:
     *   success                       bool
     *   status                        'generated' | 'insufficient_data' | 'failed'
     *   listing_type                  string   ('seller' | 'landlord')
     *   listing_id                    int
     *   property_strengths            string[]
     *   property_highlights           string[]
     *   property_positioning          string
     *   property_target_audiences     string[]
     *   property_personality_tags     string[]
     *   property_story                string
     *   location_intelligence_context array|null
     *   property_intelligence_version string   (always PROPERTY_INTELLIGENCE_V1)
     *   error                         string|null
     *
     * @param  PropertyDnaProfile $profile  A cast, in-memory profile instance.
     * @return array
     */
    public function generate(PropertyDnaProfile $profile): array
    {
        $stub = [
            'success'                       => false,
            'status'                        => 'insufficient_data',
            'listing_type'                  => (string) ($profile->listing_type ?? ''),
            'listing_id'                    => (int) ($profile->listing_id ?? 0),
            'property_strengths'            => [],
            'property_highlights'           => [],
            'property_positioning'          => self::POSITIONING_MOVE_UP,
            'property_target_audiences'     => [],
            'property_personality_tags'     => [],
            'property_story'                => '',
            'location_intelligence_context' => null,
            'property_intelligence_version' => self::PROPERTY_INTELLIGENCE_VERSION,
            'error'                         => null,
        ];

        if ($this->isInsufficientData($profile)) {
            $stub['error'] = 'Insufficient profile data: overall_dna_completeness is empty and no score fields are populated.';
            return $stub;
        }

        try {
            $tags = (array) ($profile->ai_buyer_archetype_tags ?? []);

            $locationResult = $this->locationContextService->getForListing(
                (string) $profile->listing_type,
                (int) $profile->listing_id
            );

            $locationContext = $locationResult['success']
                ? ($locationResult['location_intelligence_context'] ?? null)
                : null;

            $profile->location_intelligence_context = $locationContext;
            $profile->save();

            $strengths     = $this->deriveStrengths($tags);
            $highlights    = $this->deriveHighlights($tags);
            $positioning   = $this->derivePositioning($tags, $profile);
            $audiences     = $this->deriveTargetAudiences($tags, $profile);
            $personality   = $this->derivePersonalityTags($tags, $profile, $locationContext);
            $story         = $this->assembleStory($positioning, $strengths, $profile, $locationContext);

            return [
                'success'                       => true,
                'status'                        => 'generated',
                'listing_type'                  => (string) $profile->listing_type,
                'listing_id'                    => (int) $profile->listing_id,
                'property_strengths'            => $strengths,
                'property_highlights'           => $highlights,
                'property_positioning'          => $positioning,
                'property_target_audiences'     => $audiences,
                'property_personality_tags'     => $personality,
                'property_story'                => $story,
                'location_intelligence_context' => $locationContext,
                'property_intelligence_version' => self::PROPERTY_INTELLIGENCE_VERSION,
                'error'                         => null,
            ];
        } catch (\Throwable $e) {
            return array_merge($stub, [
                'status' => 'failed',
                'error'  => $e->getMessage(),
            ]);
        }
    }

    // =========================================================================
    // Guard
    // =========================================================================

    /**
     * Returns true when overall_dna_completeness is null or zero AND
     * all numeric score fields are null — profile is considered empty.
     */
    private function isInsufficientData(PropertyDnaProfile $profile): bool
    {
        $completeness = $profile->overall_dna_completeness;
        if ($completeness !== null && (float) $completeness > 0.0) {
            return false;
        }

        $scoreFields = [
            'physical_score', 'financial_score', 'flexibility_score',
            'occupant_qualification_score', 'marketing_score', 'commercial_score',
            'location_score', 'condition_score', 'legal_score', 'compatibility_score',
        ];

        foreach ($scoreFields as $field) {
            if ($profile->{$field} !== null) {
                return false;
            }
        }

        return true;
    }

    // =========================================================================
    // Derivation: property_strengths
    // =========================================================================

    /**
     * Derive property_strengths from ai_buyer_archetype_tags using STRENGTH_MAP.
     *
     * Returns a flat string[] of matched strength labels. Deduplication is applied
     * so that multiple tags mapping to the same label only appear once.
     *
     * @param  string[] $tags
     * @return string[]
     */
    private function deriveStrengths(array $tags): array
    {
        $seen      = [];
        $strengths = [];

        foreach ($tags as $tag) {
            $tag = (string) $tag;
            if (isset(self::STRENGTH_MAP[$tag])) {
                $label = self::STRENGTH_MAP[$tag];
                if (!in_array($label, $seen, true)) {
                    $seen[]      = $label;
                    $strengths[] = $label;
                }
            }
        }

        return $strengths;
    }

    // =========================================================================
    // Derivation: property_highlights
    // =========================================================================

    /**
     * Derive property_highlights from ai_buyer_archetype_tags using HIGHLIGHT_MAP.
     *
     * Returns a flat string[] of canonical headline labels, deduplicated.
     * This is the shared feed for Marketing Intelligence, Ask AI, listing widgets,
     * and shareable reports.
     *
     * @param  string[] $tags
     * @return string[]
     */
    private function deriveHighlights(array $tags): array
    {
        $seen       = [];
        $highlights = [];

        foreach ($tags as $tag) {
            $tag = (string) $tag;
            if (isset(self::HIGHLIGHT_MAP[$tag])) {
                $label = self::HIGHLIGHT_MAP[$tag];
                if (!in_array($label, $seen, true)) {
                    $seen[]       = $label;
                    $highlights[] = $label;
                }
            }
        }

        return $highlights;
    }

    // =========================================================================
    // Derivation: property_positioning
    // =========================================================================

    /**
     * Deterministically classify the property into exactly one positioning label.
     *
     * Priority order (first match wins):
     *   1. Commercial Property  — use:commercial tag present
     *   2. Retirement Home      — community:55-plus tag present
     *                             (PropertyDnaGenerator emits this tag when is_55_plus dimension = 'yes',
     *                             sourced from the leasing_55_plus meta key)
     *   3. Investment Property  — two or more investment-signal tags, OR financial_score > threshold
     *   4. Vacation Home        — waterfront tag present AND furnished/furnishing signal present
     *                             (waterfront alone is insufficient; a primary residence may be waterfront)
     *   5. Luxury Home          — physical_score above luxury threshold
     *   6. Starter Home         — financial_score below investment threshold AND completeness < 35
     *   7. Move-Up Home         — default when no other signal is present
     *
     * @param  string[]           $tags
     * @param  PropertyDnaProfile $profile
     * @return string
     */
    private function derivePositioning(array $tags, PropertyDnaProfile $profile): string
    {
        $tagSet = array_flip($tags);

        if (isset($tagSet['use:commercial'])) {
            return self::POSITIONING_COMMERCIAL;
        }

        if (isset($tagSet['community:55-plus'])) {
            return self::POSITIONING_RETIREMENT;
        }

        $investmentSignals = 0;
        if (isset($tagSet['structure:lease-option']))    { $investmentSignals++; }
        if (isset($tagSet['structure:lease-purchase']))  { $investmentSignals++; }
        if (isset($tagSet['financing:seller-financed'])) { $investmentSignals++; }
        if (isset($tagSet['financing:assumable']))       { $investmentSignals++; }

        $financialScore = $profile->financial_score !== null ? (float) $profile->financial_score : null;

        if ($investmentSignals >= 2 || ($financialScore !== null && $financialScore > self::INVESTMENT_FINANCIAL_THRESHOLD)) {
            return self::POSITIONING_INVESTMENT;
        }

        $hasWaterfront  = isset($tagSet['amenity:waterfront']) || isset($tagSet['feature:waterfront']);
        $hasFurnished   = isset($tagSet['amenity:furnished'])
            || isset($tagSet['feature:furnished'])
            || isset($tagSet['feature:furnishing-terms-specified']);
        // Vacation Home requires waterfront + furnished signal.
        // A waterfront primary residence without furnished indicators is classified
        // as Move-Up Home or Luxury Home depending on physical_score.
        if ($hasWaterfront && $hasFurnished) {
            return self::POSITIONING_VACATION;
        }

        $physicalScore = $profile->physical_score !== null ? (float) $profile->physical_score : null;
        if ($physicalScore !== null && $physicalScore > self::LUXURY_PHYSICAL_THRESHOLD) {
            return self::POSITIONING_LUXURY;
        }

        $completeness = $profile->overall_dna_completeness !== null ? (float) $profile->overall_dna_completeness : null;
        if ($financialScore !== null && $financialScore <= self::INVESTMENT_FINANCIAL_THRESHOLD
            && $completeness !== null && $completeness < 35.0) {
            return self::POSITIONING_STARTER;
        }

        return self::POSITIONING_MOVE_UP;
    }

    // =========================================================================
    // Derivation: property_target_audiences
    // =========================================================================

    /**
     * Deterministically derive property_target_audiences from archetype tags and scores.
     *
     * Answers "who is this property for?" Returns a string[] of audience labels.
     * Multiple audiences may be returned. Order is deterministic (fixed evaluation order).
     *
     * @param  string[]           $tags
     * @param  PropertyDnaProfile $profile
     * @return string[]
     */
    private function deriveTargetAudiences(array $tags, PropertyDnaProfile $profile): array
    {
        $tagSet    = array_flip($tags);
        $audiences = [];

        if (isset($tagSet['community:55-plus'])) {
            $audiences[] = 'Retirees';
        }

        if (isset($tagSet['use:commercial'])) {
            $audiences[] = 'Investors';
        }

        $hasLeaseOption    = isset($tagSet['structure:lease-option']);
        $hasLeaseP         = isset($tagSet['structure:lease-purchase']);
        $hasSellerFinance  = isset($tagSet['financing:seller-financed']);
        $hasAssumable      = isset($tagSet['financing:assumable']);

        if ($hasSellerFinance || $hasAssumable) {
            $audiences[] = 'First-Time Buyers';
        }

        if ($hasLeaseOption || $hasLeaseP || $hasSellerFinance || $hasAssumable) {
            if (!in_array('Investors', $audiences, true)) {
                $audiences[] = 'Investors';
            }
        }

        $hasWaterfront  = isset($tagSet['amenity:waterfront']) || isset($tagSet['feature:waterfront']);
        $physicalScore  = $profile->physical_score !== null ? (float) $profile->physical_score : null;
        $hasPool        = isset($tagSet['amenity:pool']);
        $hasGarage      = isset($tagSet['parking:garage']);

        if ($hasWaterfront) {
            $audiences[] = 'Vacation Buyers';
        }

        if ($hasPool && $hasGarage && $physicalScore !== null && $physicalScore > 50.0) {
            $audiences[] = 'Move-Up Families';
        }

        $hasFurnished = isset($tagSet['amenity:furnished']) || isset($tagSet['feature:furnished'])
            || isset($tagSet['feature:furnishing-terms-specified']);

        if ($hasFurnished) {
            $audiences[] = 'Remote Workers';
        }

        if (empty($audiences)) {
            $audiences[] = 'Move-Up Families';
        }

        return array_values(array_unique($audiences));
    }

    // =========================================================================
    // Derivation: property_personality_tags
    // =========================================================================

    /**
     * Deterministically derive property_personality_tags from archetype tags, scores,
     * and — where available — the location intelligence context.
     *
     * Returns a string[] of lifestyle/character labels. Designed as a future bridge
     * across Property DNA → Buyer/Tenant Avatars → Compatibility → Marketing Intelligence.
     *
     * @param  string[]     $tags
     * @param  PropertyDnaProfile $profile
     * @param  array|null   $locationContext
     * @return string[]
     */
    private function derivePersonalityTags(array $tags, PropertyDnaProfile $profile, ?array $locationContext): array
    {
        $tagSet      = array_flip($tags);
        $personality = [];

        $hasWaterfront = isset($tagSet['amenity:waterfront']) || isset($tagSet['feature:waterfront']);
        $coastalAvailable = $locationContext !== null
            && isset($locationContext['available_categories'])
            && in_array('coastal_features', (array) $locationContext['available_categories'], true);

        if ($hasWaterfront || $coastalAvailable) {
            $personality[] = 'Coastal Lifestyle';
        }

        if (isset($tagSet['amenity:pool']) || isset($tagSet['feature:storage'])) {
            $personality[] = 'Outdoor Living';
        }

        if (isset($tagSet['policy:pets-allowed']) || isset($tagSet['parking:garage'])) {
            $personality[] = 'Family-Friendly';
        }

        if (isset($tagSet['governance:hoa'])) {
            $personality[] = 'Low Maintenance';
        }

        $hasLeaseOption   = isset($tagSet['structure:lease-option']);
        $hasLeaseP        = isset($tagSet['structure:lease-purchase']);
        $hasSellerFinance = isset($tagSet['financing:seller-financed']);
        $hasAssumable     = isset($tagSet['financing:assumable']);

        if ($hasSellerFinance || $hasAssumable || $hasLeaseOption || $hasLeaseP) {
            $personality[] = 'Investment Potential';
        }

        if ($hasSellerFinance || $hasAssumable) {
            $personality[] = 'Flexible Financing';
        }

        if (isset($tagSet['policy:pets-allowed'])) {
            $personality[] = 'Pet-Friendly';
        }

        $hasFurnished = isset($tagSet['amenity:furnished']) || isset($tagSet['feature:furnished'])
            || isset($tagSet['feature:furnishing-terms-specified']);

        if ($hasFurnished) {
            $personality[] = 'Move-In Ready';
        }

        return array_values(array_unique($personality));
    }

    // =========================================================================
    // Assembly: property_story
    // =========================================================================

    /**
     * Assemble a single-paragraph property story from deterministic template fragments.
     *
     * No AI, no OpenAI calls. Template structure:
     *   1. Opening: positioning label sentence.
     *   2. Strengths sentence (if strengths exist).
     *   3. Marketing hook phrase (first hook from ai_marketing_hooks, if present).
     *   4. Location highlight sentence (if Location DNA context is available).
     *
     * @param  string             $positioning
     * @param  string[]           $strengths
     * @param  PropertyDnaProfile $profile
     * @param  array|null         $locationContext
     * @return string
     */
    private function assembleStory(
        string $positioning,
        array $strengths,
        PropertyDnaProfile $profile,
        ?array $locationContext
    ): string {
        $parts = [];

        $article = in_array(strtolower($positioning[0] ?? ''), ['a', 'e', 'i', 'o', 'u'], true)
            ? 'an' : 'a';

        $parts[] = "This property is {$article} {$positioning}.";

        if (!empty($strengths)) {
            $count = count($strengths);
            if ($count === 1) {
                $parts[] = "Key features include {$strengths[0]}.";
            } elseif ($count === 2) {
                $parts[] = "Key features include {$strengths[0]} and {$strengths[1]}.";
            } else {
                $last    = array_pop($strengths);
                $parts[] = 'Key features include ' . implode(', ', $strengths) . ", and {$last}.";
            }
        }

        $hooks = (array) ($profile->ai_marketing_hooks ?? []);
        if (!empty($hooks)) {
            $first = $hooks[0];
            if (isset($first['trait'], $first['value'])) {
                $trait = ucfirst(str_replace('_', ' ', (string) $first['trait']));
                $value = (string) $first['value'];
                $parts[] = "{$trait}: {$value}.";
            }
        }

        if ($locationContext !== null && !empty($locationContext['available_categories'])) {
            $categories = (array) $locationContext['available_categories'];
            $first      = reset($categories);
            $label      = ucfirst(str_replace(['_', 'features'], [' ', ''], (string) $first));
            $parts[]    = "Location data is available for " . trim($label) . " and nearby highlights.";
        }

        return implode(' ', $parts);
    }
}
